### ISSUE TITLE
Make passing Travis required for merge

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/external-snapshotter#10]
Make passing Travis required for merge

xref https://github.com/kubernetes/test-infra/pull/9014#discussion_r209759777

/assign @xing-yang

**Comment by xing-yang** [comment]
I have made "passing travis-ci required before merging".  Let me know if anything is missing.  Thanks!

**Comment by spiffxp** [comment]
@xing-yang you'll need to open a PR against https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml for branch protection and required contexts to be enforced

eg for kubernetes/external-attacher: https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L172-L175

**Comment by xing-yang** [comment]
Will do.  Thanks!

**Comment by xing-yang** [comment]
PR submitted here: https://github.com/kubernetes/test-infra/pull/9072
