### ISSUE TITLE
VolumesnapshotContent RestoreSize is set to `0` for the snapshots created for volumesnapshotgroup

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-snapshotter#1002]
**What happened**:

The RestoreSize of each volumesnapshotcontent is set to `0` even though CSI responds back the size the VolumeGroupSnapshostCreate Response, This might be because the snapshotter create the VSC with empty status and its also reconciling the VSC and Doing GetVolumeSnapshot and updating the size https://github.com/kubernetes-csi/external-snapshotter/blob/533a2ee13a39cc4e568fb9181bdac4c2a7d03bd6/pkg/sidecar-controller/snapshot_controller.go#L282-L296
Not all CSI drivers implement ListSnapshots as it's not a mandatory RPC call.

**What you expected to happen**:

**How to reproduce it**:
The RestoreSize of each volumesnapshotcontent is set to the actual size returned in VolumeGroupSnapshostCreate Response

**Anything else we need to know?**:

**Environment**:
- Driver version: 7.0.0
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Madhu-1** [comment]
@xing-yang is this something that we can fix? i tried to fix it https://github.com/Madhu-1/external-snapshotter/commit/9382f1aaa6786b250e3d9353465d7c222b5f13c2 this way i am not sure if this is the correct approach or not, if yes i can make a PR from it.

**Comment by Madhu-1** [comment]
cc @nixpanic

**Comment by nixpanic** [comment]
Calling the `ListSnapshots` CSI procedure should not be required. The `RestoreSize` of each snapshot is returned as part of the reply to the `CreateGroupSnapshot` CSI procedure (see `repeated Snapshot snapshots = 2` [in the spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#createvolumegroupsnapshot)).

**Comment by Madhu-1** [comment]
@nixpanic sent https://github.com/kubernetes-csi/external-snapshotter/pull/1011 to fix it, PTAL
