### ISSUE TITLE
Populate SourceVolumeMode in individual VolumeSnapshotContents

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#1004]
**What happened**:
There is a TODO here to Populate this field when volume mode conversion is enabled by default. Now that volume mode conversion is enabled by default, we should populate this field.
https://github.com/kubernetes-csi/external-snapshotter/blob/v7.0.0/pkg/sidecar-controller/groupsnapshot_helper.go#L448

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Madhu-1** [comment]
@xing-yang Are you mentioned about `prevent-volume-mode-conversion` flag? if yes,  it is only part of the snapshot-controller argument, as we don't have any flag in csi-snapshotter to check if the mode is enabled should we add a new flag to the csi-snapshotter as well?

**Comment by xing-yang** [comment]
@Madhu-1 I'm thinking we should probably get rid of this flag completely.  @RaunakShah has brought this up.  I need to double check on this.
