### ISSUE TITLE
e2e tests for Volume Group Snapshot

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#1080]

**Comment by xing-yang** [comment]
This issue is about e2e tests.  Here's an example: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/snapshottable.go

We also need to add unit tests.  I'll open another issue for that.

**Comment by manishym** [comment]
@xing-yang can you please take a look? https://github.com/kubernetes/kubernetes/pull/126326
