### ISSUE TITLE
Add metrics for Volume Group Snapshot

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#1081]

**Comment by yati1998** [comment]
Hi @xing-yang ,
Can you please add more details on what metrics need to be added and for what purpose?

**Comment by xing-yang** [comment]
We'll need to add metrics for snapshot-controller, similar to what we've added for volume snapshots. See example here: https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/metrics/metrics_test.go#L256

**Comment by yati1998** [comment]
https://github.com/kubernetes-csi/external-snapshotter/pull/1107, we can close this issue now.

**Comment by Madhu-1** [comment]
@xing-yang can we close this one?
