### ISSUE TITLE
CreateSnapshot 返回失败信息后每隔一秒重新发起调用CreateSnapshot，限速队列并没有起作用

### ISSUE THREAD

**Issue by running-fly** [kubernetes-csi/external-snapshotter#1116]
**What happened**:
The same CreateSnapshot is called repeatedly every second
When creating a snapshot fails
**What you expected to happen**:
  
**How to reproduce it**:

**Anything else we need to know?**:
var (
	
	threads                = flag.Int("worker-threads", 10, "Number of worker threads.")

	retryIntervalStart   = flag.Duration("retry-interval-start", time.Second, "Initial retry interval of failed volume snapshot creation or deletion. It doubles with each failure, up to retry-interval-max. Default is 1 second.")
	retryIntervalMax     = flag.Duration("retry-interval-max", 5*time.Minute, "Maximum retry interval of failed volume snapshot creation or deletion. Default is 5 minutes.")
	
)
**Environment**:
- Driver version:
 external-snapshotter-6.2.1
- Kubernetes version (use `kubectl version`):
- v1.26.3
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liangyuanpeng** [comment]
1.26 is not longer support version. maybe you can try the more high version.
