### ISSUE TITLE
Missing 'groupName' comment in doc.go - wrong group for fake objects

### ISSUE THREAD

**Issue by rollandf** [kubernetes-csi/external-snapshotter#112]
The group name of the APIs is "snapshot.storage.k8s.io" as specified here:

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/apis/volumesnapshot/v1alpha1/register.go#L23

However, "fake" objects are generated with "volumesnapshot"

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/client/clientset/versioned/typed/volumesnapshot/v1alpha1/fake/fake_volumesnapshot.go#L37

It seems that doc.go is missing the comment 
`
// +groupName=snapshot.storage.k8s.io
`

Due to this issue, we cannot use fake entities to do unit tests.

**Comment by xing-yang** [comment]
Thanks for reporting this issue.  A PR is submitted.

**Comment by rollandf** [comment]
Thanks for fixing this!
