### ISSUE TITLE
If driver can't delete PVC when it still has snapshots,  when deleting the PVC,  maybe it can't delete the PVC in the etcd?

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/external-snapshotter#115]
Version:
external-snapshotter: v1.0.1
kubernetes: v1.13.0

Details:
 If driver can't delete PVC when it still has snapshots, when I delete the PVC with snapshots，the PVC in the etcd has been delete，but in fact,  delete the PVC failed.

Expectation：
If driver can't delete PVC when it still has snapshots， it can't delete the pvc in etcd.

**Comment by xing-yang** [comment]
Thanks @zhucan for reporting this issue!  It was a design decision not to prevent PVC with snapshots from being deleted because some drivers do support that, but I think we should re-evaluate and figure out how to handle this better.

**Comment by xing-yang** [comment]
In this case, driver can return success but need to know that PVC already deleted in k8s.  After all snapshots are deleted, driver should delete the volume itself.

We need to add documentation for this.

**Comment by msau42** [comment]
In this case, shouldn't PV object still exist because DeleteVolume() will fail?

Can the presence of PVs in Released state indicate that something in the deletion is not working?  PVC deletion is how we signal to the driver to start volume deletion.

**Comment by xing-yang** [comment]
We should add a test to make sure PVC can be deleted when there are still snapshots.

**Comment by xing-yang** [comment]
We discussed about this in the snapshot meeting.  We want this to be handled consistently.  So driver should return success and both PV and PVC will be deleted successfully.  Driver needs to handle the cleanup of the volume resource on the storage system after all snapshots are deleted.

**Comment by xing-yang** [comment]
/remove-lifecycle rotten
We still need to discuss and figure out a better way to handle this.

**Comment by xing-yang** [comment]
This issue is discussed here as well: https://github.com/kubernetes-csi/external-provisioner/issues/252
