### ISSUE TITLE
Change enable-volume-group-snapshots from a flag to feature gate

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#1176]
**What happened**:
Currently enable-volume-group-snapshots is a flag in snapshot-controller and csi-snapshotter sidecar.

**What you expected to happen**:
Since we will enable the feature by default at some point, it should be a feature gate instead.
See examples in external-provisioner: https://github.com/kubernetes-csi/external-provisioner/blob/0f8b1662e25f37675da1f82acb78cd820b359419/pkg/features/features.go#L21

Since this feature requires a new API group, this feature will be disabled by default when we first move it to beta in 1.32.
Then in 1.33, we can enable the feature gate by default.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Madhu-1** [comment]
Fixed by https://github.com/kubernetes-csi/external-snapshotter/pull/1194

**Comment by pwschuurman** [comment]
> Then in 1.33, we can enable the feature gate by default.

@xing-yang Is there an issue tracking default feature gate enablement?
