### ISSUE TITLE
Missing group name label from VolumeSnapshots that are part of a statically provisioned group snapshot

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#1213]
**What happened**:
VolumeSnapshots from statically provisioned VolumeGroupSnapshot do not have the group name label.
Similarly the label is missing fro VolumeSnapshotContents.
The label is helpful in identifying what individual volume snapshots are part of a group snapshot.

Here's an example VolumeSnapshot and VolumeSnapshotContent.
```
- apiVersion: snapshot.storage.k8s.io/v1
  kind: VolumeSnapshot
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"snapshot.storage.k8s.io/v1","kind":"VolumeSnapshot","metadata":{"annotations":{},"name":"static-snapshot1","namespace":"default"},"spec":{"source":{"volumeSnapshotContentName":"static-content1"}}}
    creationTimestamp: "2024-11-23T03:09:41Z"
    finalizers:
    - snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    - snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
    generation: 1
    name: static-snapshot1
    namespace: default
    resourceVersion: "104810"
    uid: 4c891ced-39d2-44df-9ea3-3e736f92c8da
  spec:
    source:
      volumeSnapshotContentName: static-content1
  status:
    boundVolumeSnapshotContentName: static-content1
    creationTime: "2024-11-23T02:01:52Z"
    readyToUse: true
    restoreSize: 100Mi
    volumeGroupSnapshotName: static-group-snapshot

- apiVersion: snapshot.storage.k8s.io/v1
  kind: VolumeSnapshotContent
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"snapshot.storage.k8s.io/v1","kind":"VolumeSnapshotContent","metadata":{"annotations":{},"name":"static-content1"},"spec":{"deletionPolicy":"Delete","driver":"hostpath.csi.k8s.io","source":{"snapshotHandle":"e8779147-a93e-11ef-9549-66940726f2fd"},"volumeSnapshotRef":{"name":"static-snapshot1","namespace":"default"}}}
    creationTimestamp: "2024-11-23T03:09:41Z"
    finalizers:
    - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
    generation: 2
    name: static-content1
    resourceVersion: "104356"
    uid: e0664c69-954f-4aa7-8b03-dd5ca37e5ee3
  spec:
    deletionPolicy: Delete
    driver: hostpath.csi.k8s.io
    source:
      snapshotHandle: e8779147-a93e-11ef-9549-66940726f2fd
    volumeSnapshotRef:
      name: static-snapshot1
      namespace: default
      uid: 4c891ced-39d2-44df-9ea3-3e736f92c8da
  status:
    creationTime: 1732327312499129161
    readyToUse: true
    restoreSize: 104857600
    snapshotHandle: e8779147-a93e-11ef-9549-66940726f2fd
    volumeGroupSnapshotHandle: e8779136-a93e-11ef-9549-66940726f2fd
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xing-yang** [comment]
@yati1998 I don't know what you meant.  The label is visible in your VolumeSnapshot output.
```
labels:
    groupsnapshot.storage.k8s.io/volumeGroupSnapshotName: new-groupsnapshot-sc
```

**Comment by Madhu-1** [comment]
@xing-yang @leonardoce wont we get into the length problem if we use group name as label value here?

**Comment by xing-yang** [comment]
@Madhu-1 That's a valid concern.  Maybe we should use label first if possible, but if the length is longer than 63, use annotation instead.
The benefits of using label is that you can search and find all objects with the label with one kubectl command.

**Comment by Madhu-1** [comment]
> @Madhu-1 That's a valid concern. Maybe we should use label first if possible, but if the length is longer than 63, use annotation instead. The benefits of using label is that you can search and find all objects with the label with one kubectl command.

Agree even the current client only support list based on the labels. but would it make sense to take two approach based on the length or go with single implementation that supports both?

**Comment by xing-yang** [comment]
Discussed with @msau42 and @gnufied about this. We are going to make VolumeGroupSnapshot an owner of VolumeSnapshot.

**Comment by leonardoce** [comment]
We are using that label internally to look up all the members of a snapshot group. See here:

https://github.com/kubernetes-csi/external-snapshotter/blob/fe82dd2dc3051251ea5e89636bc715be4a969826/pkg/common-controller/groupsnapshot_controller_helper.go#L1439-L1443

We'll need to replace this with an indexer.

Dumb question about the ownership: what is supposed to happen when deleting a VolumeGroupSnapshot with deletionPolicy=Retain?
Do we want the member VolumeSnapshots to be deleted, too? Or will we drop the ownership?

**Comment by xing-yang** [comment]
If it is Retain, we still want the member VolumeSnapshots to be deleted.  Do you see any problems?

**Comment by leonardoce** [comment]
> If it is Retain, we still want the member VolumeSnapshots to be deleted. Do you see any problems?

No, I'm just wrapping my mind around it and trying to understand the behavior we are looking for.
It's fine now. Thanks!
