### ISSUE TITLE
Deletion of VolumeGroupSnapshot leads to DeleteSnapshot CSI call

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-snapshotter#1230]
**What happened**:
When I delete fully established VolumeGroupSnapshot API object, the external-snapshotter calls `DeleteVolumeGroupSnapshot` for the group (that's good) and then `DeleteSnapshot` for each VolumeSnapshot individually (that's forbidden by CSI spec).

I suspect it's caused by cascade deletion of VolumeSnapshot objects because their owner (the group snapshot) was deleted.

**What you expected to happen**:
Only `DeleteVolumeGroupSnapshot` is called. Deletion of VolumeSnapshots that is part of a group should not lead to `DeleteSnapshot`.

**How to reproduce it**:
Create VolumeGroupSnapshot, wait for it to be fully taken and ready and then delete it.

- Driver version: today's master of csi-driver-hostpath
- both external-snapshotter and snapshot-controller are from today's master, a0cef5328866fcf65405aef992802c37f980ece0

**Comment by jsafrane** [comment]
Btw, there should be an e2e test for this.

**Comment by jsafrane** [comment]
[csi-driver-hostpath.log](https://github.com/user-attachments/files/17994668/driver.log)
[external-snapshotter.log](https://github.com/user-attachments/files/17994669/external-snapshotter.log)

**Comment by xing-yang** [comment]
We should fix this problem before cutting the release.

**Comment by jsafrane** [comment]
from the driver log:

```
$ grep Delete csi-driver-hostpath.log

I1203 14:16:28.050250       1 server.go:104] GRPC call: /csi.v1.GroupController/DeleteVolumeGroupSnapshot
I1203 14:16:28.052780       1 server.go:162] gRPCCall: {"Method":"/csi.v1.GroupController/DeleteVolumeGroupSnapshot","Request":{"group_snapshot_id":"743d934b-b176-11ef-a177-76924a05fd4c","snapshot_ids":["743d9399-b176-11ef-a177-76924a05fd4c","743f5352-b176-11ef-a177-76924a05fd4c","744116cd-b176-11ef-a177-76924a05fd4c"]},"Response":{},"Error":"","FullError":null}
I1203 14:16:29.075350       1 server.go:104] GRPC call: /csi.v1.Controller/DeleteSnapshot
I1203 14:16:29.076075       1 server.go:162] gRPCCall: {"Method":"/csi.v1.Controller/DeleteSnapshot","Request":{"snapshot_id":"744116cd-b176-11ef-a177-76924a05fd4c"},"Response":{},"Error":"","FullError":null}
I1203 14:16:29.083300       1 server.go:104] GRPC call: /csi.v1.Controller/DeleteSnapshot
I1203 14:16:29.083413       1 server.go:162] gRPCCall: {"Method":"/csi.v1.Controller/DeleteSnapshot","Request":{"snapshot_id":"743d9399-b176-11ef-a177-76924a05fd4c"},"Response":{},"Error":"","FullError":null}
I1203 14:16:29.645521       1 server.go:104] GRPC call: /csi.v1.Controller/DeleteSnapshot
I1203 14:16:29.645704       1 server.go:162] gRPCCall: {"Method":"/csi.v1.Controller/DeleteSnapshot","Request":{"snapshot_id":"743f5352-b176-11ef-a177-76924a05fd4c"},"Response":{},"Error":"","FullError":null}
```
