### ISSUE TITLE
Leader election lock name should include driver name

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#128]
To be consistent with the other sidecars

**Comment by verult** [comment]
And also to allow for the possibility that multiple drivers run in the same namespac

**Comment by zhucan** [comment]
"external-snapshotter-leader-election" + driverName is ok?

**Comment by xing-yang** [comment]
@zhucan do you want to work on this?  I see that @verult submitted a PR in external-provisioner to add namespace locking.  You can take a look here: https://github.com/kubernetes-csi/external-provisioner/pull/296

**Comment by zhucan** [comment]
> @zhucan do you want to work on this? I see that @verult submitted a PR in external-provisioner to add namespace locking. You can take a look here: [kubernetes-csi/external-provisioner#296](https://github.com/kubernetes-csi/external-provisioner/pull/296)

yeah
