### ISSUE TITLE
`DeletionPolicy` contradictory docs

### ISSUE THREAD

**Issue by nrb** [kubernetes-csi/external-snapshotter#133]
On `VolumeSnapshotClass`, the[ comments](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/apis/volumesnapshot/v1alpha1/types.go#L136-L139) specify that the default behavior is `Delete` if a `DeletionPolicy` is not defined.

However, the `VolumeSnapshotContentRetain` [constant](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/apis/volumesnapshot/v1alpha1/types.go#L254) says that the default behavior is `Retain`.

The [controller sets the value to `Delete`](https://github.com/kubernetes-csi/external-snapshotter/blob/d3243e09b6db9e02fce81bad196449ec86751509/pkg/controller/snapshot_controller.go#L668).

I assume the comments on the `VolumeSnapshotContentRetain` constant should be removed; is that correct?

**Comment by xing-yang** [comment]
I'll take a look.

**Comment by xing-yang** [comment]
The default policy for dynamic provisioning is Delete. That's why the controller sets it to Delete. The default policy for static provisioning is Retain. That's the reasoning for those comments on VolumeSnapshotContentRetain which is still correct (if not override by the policy set in storage class).

I can see that it is very confusing.  I'll try to clarify the comments.  Thanks.

**Comment by xing-yang** [comment]
In the beta version of snapshot API, deletion policy is a required field in both VolumeSnapshotClass and VolumeSnapshotContent.  Therefore we won't have this confusion any more.

**Comment by nrb** [comment]
Thanks!

Since it's required for VolumeSnapshotContent now, is it simply copied from the VolumeSnapshotClass each time a Content object is created?

**Comment by xing-yang** [comment]
Yes, controller will copy it from snapshot class in the case of dynamic provisioning.  For pre-provisioned snapshots, admin has to set it when creating the content manually.
