### ISSUE TITLE
e2e testing for snapshot controller metrics

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes-csi/external-snapshotter#151]
to create e2e test cases for snapshot controller metrics in #142

**Comment by ggriffiths** [comment]
PR https://github.com/kubernetes/kubernetes/pull/96299 adds a framework for testing e2e snapshot controller metrics and a few simple test cases.

Here is the progress on this work:

- [ ] Snapshot controller metrics e2e framework - PR https://github.com/kubernetes/kubernetes/pull/96299
- [ ] Simple positive test cases for snapshot controller metrics  - PR https://github.com/kubernetes/kubernetes/pull/96299
- [ ] Negative metric tests
- [ ] Per-reconciliation metrics tests (once these metrics are implemented)

**Comment by ggriffiths** [comment]
/remove-lifecycle rotten Being worked on in https://github.com/kubernetes/kubernetes/pull/96299

**Comment by ggriffiths** [comment]
Progress on this work:
- [x] Snapshot controller metrics e2e framework - PR kubernetes/kubernetes#96299
- [x] Simple positive test cases for snapshot controller metrics - PR kubernetes/kubernetes#96299
- [ ] Negative metric tests
- [ ] Per-reconciliation metrics tests (once these metrics are implemented)

/remove-lifecycle rotten

**Comment by xing-yang** [comment]
@ggriffiths I thought you've already added e2e tests for this.  Are there still remaining items?

**Comment by ggriffiths** [comment]
We can close this
