### ISSUE TITLE
Add a secret key for ListSnapshot to SnapshotClass

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/external-snapshotter#152]
Once CSI spec is update to add new secret field to `ListSnapshotRequest` (https://github.com/container-storage-interface/spec/issues/370), we should:

1. Add a new key (something like `csi.storage.k8s.io/list-snapshot-secret-name`) to `SnapshotClass`.
2. Update kubernetes-csi docs to reflect what we support.

**Comment by xing-yang** [comment]
This is fixed by this PR: https://github.com/kubernetes-csi/external-snapshotter/pull/252
