### ISSUE TITLE
external-snapshotter should not allow annotation in template for snapshotter-secret-name

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/external-snapshotter#155]
external-snapshotter supports `${volumesnapshot.annotations['ANNOTATION_KEY']}` as a template for `csi.storage.k8s.io/snapshotter-secret-name`. It should not. It is ok for all other secrets (e.g. ListSnapshot secret) but not for the CreateSnapshot secret.

https://github.com/kubernetes-csi/external-snapshotter/blob/a1b3374fac007a0f3a122fc1cef1b9f3c38f1080/pkg/controller/util.go#L216-L220

CC @msau42 @jingxu97 @xing-yang

**Comment by xing-yang** [comment]
Hi @saad-ali, the secret handling logic in external-snapshotter is modeled after the code in external-provisioner.  We do strip prefixed parameters before calling create snapshot.  See here:

https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/controller/csi_handler.go#L70 

I'll add comments to clarify that.  Is that okay?  Thanks.

**Comment by msau42** [comment]
@saad-ali's comment is not about stripping the k8s csi prefix.  It's about allowing `volumesnapshot.annotations` as a template value.  For Volume Create/Delete, we do not allow PVC annotations to be used in the StorageClass secret template.  Very long discussion here: https://github.com/kubernetes-csi/external-provisioner/issues/86

**Comment by xing-yang** [comment]
Thanks @msau42!  I'll take a look of the discussion.

**Comment by msau42** [comment]
Some more discussion: https://github.com/kubernetes-csi/external-provisioner/issues/170

**Comment by xing-yang** [comment]
This is fixed.
