### ISSUE TITLE
Use cached driver name in SnapshotController instead of getting it from CreateSnapshot

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes-csi/external-snapshotter#159]
A comment from @jsafrane in another open PR 
https://github.com/kubernetes-csi/external-snapshotter/pull/153#discussion_r310598971

Specifically, this call can be cached:
https://github.com/kubernetes-csi/external-snapshotter/blob/7e09056156893c55cf45d9059afd8f564bdfed5e/pkg/snapshotter/snapshotter.go#L64

**Comment by ggriffiths** [comment]
This is actually already cached as `snapshotterName` in the controller. We don't use the driverName inside of `external-snapshotter/pkg/snapshotter/snapshotter.go`, it's just passed back upstream to the controller.

Instead of doing this, we can have the controller use it's cached version `ctrl.snapshotterName`

**Comment by jsafrane** [comment]
Sure, removing `driverName` return value is OK.
