### ISSUE TITLE
snapshotter 1.x support for configmap leadership election type

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes-csi/external-snapshotter#168]
Since leases leadership election is only supported in k8s 1.14+, the snapshotter leadership election will not work in k8s 1.13.

Attacher/provisioner sidecars allow non-lease leadership election types in their latest 1.x releases:
https://github.com/kubernetes-csi/external-provisioner/blob/v1.3.0/cmd/csi-provisioner/csi-provisioner.go#L205-L213

https://github.com/kubernetes-csi/external-attacher/blob/release-1.2/cmd/csi-attacher/main.go#L203-L211

**Comment by msau42** [comment]
Snapshotter is still alpha so we don't need to follow backwards compatibility and upgrade requirements like attacher and provisioner do. For recommended k8s versions for snapshotter, follow this table: https://kubernetes-csi.github.io/docs/external-snapshotter.html

**Comment by ggriffiths** [comment]
Makes sense, thanks!
