### ISSUE TITLE
release 0.4.2 image is not available

### ISSUE THREAD

**Issue by k0da** [kubernetes-csi/external-snapshotter#185]
```
docker pull quay.io/k8scsi/csi-snapshotter:v0.4.2
Error response from daemon: manifest for quay.io/k8scsi/csi-snapshotter:v0.4.2 not found
```

Looks like image tag is hardcoded now to 0.4-canary https://github.com/xing-yang/external-snapshotter/blob/d933f30b5138465de83da8fcbe00f29a6f9f8382/Makefile#L19

**Comment by xing-yang** [comment]
I see.  I think the v0.4.2 image needs to be published manually.  We changed the tag to canary because we don't want it to overwrite the 0.4.1 image.

**Comment by k0da** [comment]
Could you please push one? we sync images, based on GH releases, right now our pipeline is broken :(

**Comment by xing-yang** [comment]
Will do.

**Comment by xing-yang** [comment]
Done.
