### ISSUE TITLE
Move APIs and generated clients outside pkg

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#186]
It could also be exported as a go module.

**Comment by yuxiangqian** [comment]
this would need another to resolve

**Comment by xing-yang** [comment]
I think the snapshot-controller should stay with the APIs and generated clients in the same repo.  Otherwise there's no way to validate the APIs and we'll have more problems trying to sync up 3 repos.

**Comment by msau42** [comment]
Yes I think same repo but separate go modules would be great

**Comment by msau42** [comment]
Here's an example of csi-proxy creating a separate go module for their client library: https://github.com/kubernetes-csi/csi-proxy/tree/master/client

**Comment by xing-yang** [comment]
Thanks!  Will take a look.

**Comment by Kartik494** [comment]
> Yes I think same repo but separate go modules would be great

Hi @msau42 According to this we don't have to move apis and generated clients outside pkg?
Rather within pkg we have to create go module for apis and generated client like this [client library](https://github.com/kubernetes-csi/csi-proxy/tree/master/client) Please let me know regarding this 
Thanks

**Comment by msau42** [comment]
While technically you don't need to move it out of pkg, I think it makes more sense from a code organization perspective to move it out to a top level client

**Comment by Kartik494** [comment]
Thanks,  i will follow up on this.

**Comment by xing-yang** [comment]
This is done.
