### ISSUE TITLE
Create a webhook to do extra validation on beta APIs

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#187]
/assign @yuxiangqian

**Comment by humblec** [comment]
@yuxiangqian are you on this ?

**Comment by yuxiangqian** [comment]
@humblec yep, I have it on my plate. thanks.

**Comment by yuxiangqian** [comment]
Update:
A design doc to introduce webhook is under written. review session will be scheduled soon once done.
