### ISSUE TITLE
external-snapshotter start failed,  because of the nil pointer

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/external-snapshotter#194]
https://github.com/kubernetes-csi/external-snapshotter/blob/d5da3c1e527cd356696300222ebd8bf728971ae4/pkg/controller/snapshot_controller.go#L918
 
**The pvc yaml**
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    **volume.beta.kubernetes.io/storage-class: test-sc**
  name: test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30G

if we set the storageclass  with the  metadata.annotations.volume.beta.kubernetes.io/storage-class not spec.storageClassName, when we rebuilding the external-snapshotter sidecar that it will throw nil pointer.
![image](https://user-images.githubusercontent.com/13997135/68836580-a26c9280-06f5-11ea-93f6-ebf7dc695277.png)

**Comment by zhucan** [comment]
@xing-yang

**Comment by xing-yang** [comment]
This should be fixed in master branch already.

**Comment by zhucan** [comment]
@xing-yang Thanks,  copy that
