### ISSUE TITLE
Update client-go to kubernetes-1.16.3

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes-csi/external-snapshotter#200]
We use VolumeSnapshot CRD api and clients in our [Stash](https://github.com/stashed) project. We are trying to use the 1.16.3 client libraries. But we are blocked on this project, since it uses 1.14 client-go. Can you please update the client-go to 1.16.3 ?

Thanks.

**Comment by msau42** [comment]
We probably should update the go-client to 1.17 actually

**Comment by msau42** [comment]
I think what can also help the import dependency issue is if we separate out the client libraries to a separate go module: https://github.com/kubernetes-csi/external-snapshotter/issues/186

**Comment by tamalsaha** [comment]
I think https://github.com/kubernetes/kubernetes/issues/85692 is the real blocker.

More here: https://github.com/kubernetes/kubernetes/issues/85693

**Comment by msau42** [comment]
Is that dependency from the snapshot API package though? If not then I think moving the client libraries to its own go module will help eliminate that dependency

**Comment by tamalsaha** [comment]
The dependency is coming from the following packages:

- github.com/kubernetes-csi/external-snapshotter/pkg/common-controller
- github.com/kubernetes-csi/external-snapshotter/pkg/sidecar-controller
- github.com/kubernetes-csi/external-snapshotter/pkg/utils

So, if the api and client libraries are moved to its own package that will solve my issue. But how is the pkg/ folder going to use those types? Also, when you say move to its own module, do you mean a separate repo, or k8s.io/api repo or same repo multiple go module?

**Comment by msau42** [comment]
I mean moving to its own go module in the same repo.  Then when you import that go module, you shouldn't be picking up the dependencies from things inside pkg/

**Comment by tamalsaha** [comment]
Yeah, that will solve my use-case.
