### ISSUE TITLE
Add more unit tests under pkg/sidecar-controller

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#204]
We need to add more unit tests under pkg/sidecar-controller.

**Comment by xing-yang** [comment]
Hi Nolan, can you assign this to yourself?  I don't know your github handle.

**Comment by ggriffiths** [comment]
I meant to refer to this one @xing-yang in #266

**Comment by Kartik494** [comment]
Hi @xing-yang  since i saw this [PR](https://github.com/kubernetes-csi/external-snapshotter/pull/266) is merged.So is there any work to be done on this issue?
