### ISSUE TITLE
Snapshotter container stuck on connecting

### ISSUE THREAD

**Issue by igorgonibm** [kubernetes-csi/external-snapshotter#208]
We use tag 1.2.2

In logs the following message appears endless number of times:
connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
The logs are:
main.go:89] Version: v1.2.2-0-gd5da3c1e
Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
connection.go:170] Still connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
....

The socket is correct since we have another sidecar container csi-attacher which uses the same socket and it works and sends GRPC requests.
main.go:95] Version: v1.2.1-0-g6dce9d7
connection.go:151] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
common.go:111] Probing CSI driver for readiness
connection.go:180] GRPC call: /csi.v1.Identity/Probe

**Comment by xing-yang** [comment]
What is the k8s version?

**Comment by igorgonibm** [comment]
1,14

**Comment by zhucan** [comment]
@igorgonibm  @xing-yang It works well. k8s version: v1.14.2

**Comment by zhucan** [comment]
@igorgonibm Can you paste the yaml about the snapshotter？

**Comment by igorgonibm** [comment]
The full version is: GitVersion:"v1.14.7"
@zhucan which yaml is it? We just define container given csi-snapshotter image path from operator code.

**Comment by zhucan** [comment]
setup-csi-snapshotter.yaml

**Comment by igorgonibm** [comment]
@zhucan We didn't use such file.. Where can I get it? Is it something in csi-snapshotter sources?

**Comment by zhucan** [comment]
@igorgonibm How do you deploy snapshotter? Isn't it through set-csi-snapshotter yaml？

https://github.com/kubernetes-csi/external-snapshotter/tree/v1.2.2/deploy/kubernetes

**Comment by igorgonibm** [comment]
@zhucan we did it according to https://github.com/kubernetes-csi/external-snapshotter. There was nothing about such yaml. We create snapshotter container from code not yaml.

**Comment by zhucan** [comment]
@igorgonibm I don't understand what you mean. If you deploy the sidecar not through the yaml, 
How did you specify the socket path for the snapshotter？

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/70719697-701e7700-1d2d-11ea-8c10-16b9e279fc53.png)
like this？

**Comment by igorgonibm** [comment]
@zhucan yes exactly. We just give another socket path (as specified above)

**Comment by zhucan** [comment]
@igorgonibm I have not tried this way, why not deploy snapshotter with yaml？

**Comment by igorgonibm** [comment]
@zhucan this is just the way our deployment works. We do it using csi operator in go-lang code.

**Comment by xing-yang** [comment]
I tested csi-snapshotter v1.2.2 image on k8s 1.14.7.  It worked for me.

**Comment by xing-yang** [comment]
I deployed csi-snapshotter using the yaml files below except that I modified the image version from v1.1.0 to v1.2.2 (`image: quay.io/k8scsi/csi-snapshotter:v1.2.2`):
https://github.com/kubernetes-csi/external-snapshotter/tree/v1.2.2/deploy/kubernetes

**Comment by igorgonibm** [comment]
We found the problem. We forgot to add volumeMounts to sidecar definition.
