### ISSUE TITLE
Create swagger.json

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#213]
We got a request to have a swagger.json so that it can be used to generate client code using Swagger Codegen.

**Comment by wing328** [comment]
You may also consider using OpenAPI Generator to generate API clients in different programming languages.

You may name the file as "openapi.json" or "openapi.yaml" instead as the Swagger specification has been donated to OpenAPI Initiative and renamed to OpenAPI Specification: https://en.wikipedia.org/wiki/OpenAPI_Specification

Disclosure: I'm the top contributor to both Swagger Codegen and OpenAPI Generator.

**Comment by anshulahuja98** [comment]
Hi @xing-yang / @humblec / @wing328 
Is there any update wrt this issue?
We were planning to generate csharp client code from the swagger for Volumesnapshot/snapshotcontent etc using https://github.com/kubernetes-client/gen

Is there any alternative for it for now?

**Comment by anshulahuja98** [comment]
> @anshulahuja98 we don't have an update on this.  Using https://github.com/kubernetes-client/gen seems to be fine.

I can't do that without swagger right. Or is there some way that it can be done using CRD YAML.

**Comment by humblec** [comment]
will get this done. thanks.
