### ISSUE TITLE
Requeue the snapshot object

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#214]
This was brought up during the code review by 
@msau42 in https://github.com/kubernetes-csi/external-snapshotter/pull/211.

```
Looking at the caller, I see that we don't requeue the object and instead rely on resync period to retry. I think we should change the behavior to requeue, but we should also make sure the workqueue has proper throttling/backoff as well.
```

Open this issue to track it.  I'll look at this after v2.0 release.

**Comment by xing-yang** [comment]
There's a question raised in issue https://github.com/kubernetes-csi/external-snapshotter/issues/225 that we should do retry immediately after update content status fails.  We should re-visit it when we look at this requeue issue.

**Comment by xing-yang** [comment]
Also for successfully processed snapshot, we should "Forget" it so it won't be queued until another change happens.

**Comment by humblec** [comment]
@xing-yang cant we close this in favor of #225 . Basically retry on update fail and forgetting the requeue once its successful should address this issue as well, Isnt it ? or anything else I missed ?

**Comment by xing-yang** [comment]
Let's keep this one open until that PR is merged.

**Comment by humblec** [comment]
> Let's keep this one open until that PR is merged.

ok.. then lets wait. do we need to add this PR as well in `fix` section of the PR ?

**Comment by xing-yang** [comment]
This is fixed.
