### ISSUE TITLE
Verify snapshot name size limit in CSI spec

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#216]
During code review of https://github.com/kubernetes-csi/external-snapshotter/pull/206, @msau42 raised a comment about verifying snapshot name length.

Verify what is the size limit for a snapshot name in CSI spec.

CSI Spec says 128 max: https://github.com/container-storage-interface/spec/blob/master/spec.md#size-limits.  It also says length of the snapshot name conforms to the length limit of an unicode string.
```
message CreateSnapshotRequest {
  // The suggested name for the snapshot. This field is REQUIRED for
  // idempotency.
  // Any Unicode string that conforms to the length limit is allowed
  // except those containing the following banned characters:
  // U+0000-U+0008, U+000B, U+000C, U+000E-U+001F, U+007F-U+009F.
  // (These are control characters other than commonly used whitespace.)
  string name = 2;
```

Should follow up on this.

**Comment by msau42** [comment]
I think we need to reconsider the 128 limit in the CSI spec. We actually hit the 128 character limit on volumeid recently and will be working on increasing the 128 limit in the spec.

**Comment by xing-yang** [comment]
Sure.  I wonder what use case requires a name to be > 128 char?

**Comment by msau42** [comment]
For PD driver, our ids are fully qualified with project name + zone name. Both those names can be quite long like "northamerica-northeast-1a"

**Comment by xing-yang** [comment]
I see.
