### ISSUE TITLE
Unable to attach or mount volumes 

### ISSUE THREAD

**Issue by liyongxian** [kubernetes-csi/external-snapshotter#219]
I did as follow:
1、kubectl create -f config/crd；
2、kubectl create -f deploy/kubernetes/snapshot-controller
3、kubectl create -f deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml,rbac-external-provisioner.yaml ,setup-csi-snapshotter.yaml.
I created pvc sucessfully.When I used it in Pod, but it was wrong.
**The problem :**
![aaaaa](https://user-images.githubusercontent.com/18571576/71305807-e6993400-2413-11ea-815a-c9c35dbef8c5.png)

**kubectl version**
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**docker info**

Containers: 31
 Running: 14
 Paused: 0
 Stopped: 17
Images: 10
Server Version: 18.06.3-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs

Thanks.

**Comment by xing-yang** [comment]
The deployment example file in the external-snapshotter repo is only intended to show how to create/delete a snapshot.  It does not include external-attacher sidecar and the node-driver-registrar sidecar so you can't test it with a Pod.

To see a full example, take a look of here:
https://github.com/kubernetes-csi/csi-driver-host-path#deployment
