### ISSUE TITLE
Further simplify syncSnapshot

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#221]
During the review of https://github.com/kubernetes-csi/external-snapshotter/pull/201, there's a comment that syncSnapshot() in the common snapshot controller can be simplified further.  Open this issue to track that.

**Comment by humblec** [comment]
@xing-yang do we need to reopen this ?

**Comment by xing-yang** [comment]
This is already addressed as part of other bug fixes.  I'll close it.
