### ISSUE TITLE
Add support ListSnapshots secrets

### ISSUE THREAD

**Issue by bells17** [kubernetes-csi/external-snapshotter#236]
Hi, CSI supported ListSnapshots secrets in [this PR](https://github.com/container-storage-interface/spec/pull/372).
So I want external-snapshotter to support ListSnapshots secrets.

ref: #152

**Comment by xing-yang** [comment]
There is a PR on this: https://github.com/kubernetes-csi/external-snapshotter/pull/162.  It was delayed because we were busy with the snapshot beta work.  Hopefully we can get it in the next release.

**Comment by bells17** [comment]
@xing-yang Oh, Thank you.
I created [PR](https://github.com/kubernetes-csi/external-snapshotter/pull/237)...but should I close this?
(I did not notice that there was PR...)

**Comment by xing-yang** [comment]
Oh, I didn't notice that you've already created a PR.  I'm checking with the author of the other PR and see if he is still interested in working on it.

Leave your PR there now.  Let me sort it out first.  Thanks.

**Comment by bells17** [comment]
I see. Thanks.

**Comment by xing-yang** [comment]
I have checked with the author of the other PR.  You can keep your PR.   I'll review it soon.  Thanks for contributing!

**Comment by tdmanv** [comment]
@bells17 @xing-yang thank you!
