### ISSUE TITLE
Create volume from snapshot - dataSource is empty

### ISSUE THREAD

**Issue by igorgonibm** [kubernetes-csi/external-snapshotter#238]
Our team is working on csi driver and currently adding snapshots support
We succeeded to create snapshots - volumesnapshotcontents are created

But for some reason when trying to create volume using these snapshots the controller CreateSnapshots doesn't receive dataSource info (it is empty)
If we remove dataSource entry from this yaml pv is created successfully so it seems the problem is snapshot related.
Do you have an  idea what can be wrong? Did we miss something in  the yaml?

We use kubernetes 1.14 and csi-snapshotter v1.2.2
Attached pvc yaml. volumesnapshot  specified in the yaml, snapshot25. exists and also corresponding volumesnapshotcontent.

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvccopy
spec:
  storageClassName: gold
  dataSource:
    name: snapshot25
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

Thank you

**Comment by xing-yang** [comment]
Did you enable VolumeSnapshotDataSource feature gate? https://kubernetes-csi.github.io/docs/snapshot-restore-feature.html#kubernetes-cluster-setup

It needs to be manually enabled for k8s version 1.12 to 1.16.  In 1.17, it is enabled by default when it is promoted to Beta.

**Comment by igorgonibm** [comment]
It is enabled already. In /etc/kubernetes/manifests/kube-apiserver.yaml we added - --feature-gates=VolumeSnapshotDataSource=true.
Is there any other place we should enable it too?

**Comment by zhucan** [comment]
I think the kube-controller and  kubelet that it needs the feature-gates @igorgonibm

**Comment by igorgonibm** [comment]
How can I do it? I couldn't find it.

**Comment by igorgonibm** [comment]
How to enable feature gate in kube-controller and kubelet ?

**Comment by zhucan** [comment]
**kube-controller-manager:**
![image](https://user-images.githubusercontent.com/13997135/72510937-448b3100-3885-11ea-886f-f7daf6d55532.png)
**kubelet:**
![image](https://user-images.githubusercontent.com/13997135/72511098-8025fb00-3885-11ea-9795-f2396eeeadda.png)

@igorgonibm

**Comment by humblec** [comment]
@zhucan hope this issue is closed now. Please revert if thats not the case.
