### ISSUE TITLE
Issue With https://github.com/kubernetes-csi/external-snapshotter/blob/master/examples/kubernetes/snapshot.yaml

### ISSUE THREAD

**Issue by Kartik494** [kubernetes-csi/external-snapshotter#245]
When i apply Snapshot.yaml in my enviorment i got error 
root@kmaster:/home/vagrant# kubectl apply -f snapshot.yaml 
error: unable to recognize "snapshot.yaml": no matches for kind "VolumeSnapshot" in version "snapshot.storage.k8s.io/v1beta1"

/kind bug

**Comment by xing-yang** [comment]
Looks like you don't have the v1beta1 snapshot CRDs installed.  See instructions on how to install CRDs here:
https://github.com/kubernetes-csi/external-snapshotter/blob/master/README.md#usage

**Comment by Kartik494** [comment]
Thanks,it is working fine now
