### ISSUE TITLE
Remove volumesnapshot.spec.source.snapshotHandle field.

### ISSUE THREAD

**Issue by bells17** [kubernetes-csi/external-snapshotter#246]
It seems that volumesnapshot.spec.source.snapshotHandle is the same field that has meaning as volumesnapshot.spec.snapshotHandle.

And I noticed volumesnapshot.spec.source.snapshotHandle never had any value set.
So now the GetSnapshotStatus method never calls.
https://github.com/kubernetes-csi/external-snapshotter/blob/4b7aec33d4760138711058c8d94f324188b4e06b/pkg/sidecar-controller/snapshot_controller.go#L256-L264

So I think that should remove volumesnapshot.spec.source.snapshotHandle field.
(if volumesnapshot.spec.source.snapshotHandle and volumesnapshot.spec.snapshotHandle has another role, please teach me about it 🙏 )

**Comment by xing-yang** [comment]
Spec.Source.SnapshotHandle in VolumeSnapshotContent is only specified for pre-provisioned snapshots.    It indicates a desired state.  If you are testing dynamically creating a snapshot, it will be empty.  See "Importing an existing volume snapshot with Kubernetes" section in the blog https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/.

Status.SnapshotHandle in VolumeSnapshotContent indicates actual state.  This field should be populated in both dynamic provisioning and pre-provisioned cases.

**Comment by bells17** [comment]
Thank you for your describe. I understand.
