### ISSUE TITLE
Print useful info in kubectl get <CRD>

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-snapshotter#247]
Current info printed by kubectl is not really useful:

```
$ kubectl get volumesnapshotclass
NAME       AGE
ebs-snap   4m43s

$ kubectl get volumesnapshot
NAME     AGE
mysnap   4m6s

$ kubectl get volumesnapshotcontent
NAME                                               AGE
snapcontent-38c22fb7-ef3c-4d53-b4e2-11bb0868d7f2   4m14s
```

With [additional printer columns](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#additional-printer-columns), it could print e.g. CSI driver (in VolumeSnapshotClass and VolumSnapshotContent) or "Ready" column in VolumeSnapshot. Add more columns as you see fit - check `kubectl get pv / pvc / storageclass` for inspiration.

**Comment by zhucan** [comment]
+1,  Is possible the same as the display of pvc?

**Comment by xing-yang** [comment]
Yes, this is good to have.
