### ISSUE TITLE
Add E2E tests for deleting API objects out of order (finalizers)

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#270]
Test the following finalizers
- "snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection"
- "snapshot.storage.kubernetes.io/volumesnapshot-bound-protection"
- "snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection"
- "snapshot.storage.kubernetes.io/pvc-as-source-protection"

**Comment by yuxiangqian** [comment]
@ggriffiths ping on this issue. Are you still working on this issue？ I saw https://github.com/kubernetes/kubernetes/pull/89705 is now approved. thanks

**Comment by ggriffiths** [comment]
@yuxiangqian I don't think I'll have the bandwidth to work on this until next month. I'll unassign myself for now

**Comment by yuxiangqian** [comment]
@ggriffiths thanks. @AndiLi99 will take a look on this.

**Comment by xing-yang** [comment]
Hi @humblec,

Do you want to work on this in 1.20? We need this for bringing snapshot to GA in 1.20. Thanks.

**Comment by humblec** [comment]
> Hi @humblec,
> 
> Do you want to work on this in 1.20? We need this for bringing snapshot to GA in 1.20. Thanks.

@xing-yang sure.. Let me take that ! thanks for the ping

**Comment by xing-yang** [comment]
@humblec As discussed, I'll un-assign this one from you now and look for a new owner for 1.20.

**Comment by xing-yang** [comment]
This may be better achieved by using the csi mock driver with the javascript hooks:
* Javascript hooks for csi mock driver: https://github.com/kubernetes-csi/csi-test/pull/251
* e2e test example: https://github.com/kubernetes/kubernetes/commit/a4f080861f3586aae0f235e914526807eeea5cfa

**Comment by xing-yang** [comment]
This is done: https://github.com/kubernetes/kubernetes/pull/95863
