### ISSUE TITLE
Add E2E tests for secret fields

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#271]
Test the following secrets:
- Delete snapshot secrets
- ListSnapshots secrets

**Comment by humblec** [comment]
@huffmanca are you on this ? if not, I will take this up.

**Comment by xing-yang** [comment]
Hi @huffmanca, 

Are you going to work on this in 1.20?  We need this for bringing snapshot to GA in 1.20.  Thanks.

**Comment by xing-yang** [comment]
Looking for an owner for this in v1.20.
