### ISSUE TITLE
Lifecycle of VolumeSnapshot Kubernetes objects should be decoupled from that in the storage system 

### ISSUE THREAD

**Issue by ashish-amarnath** [kubernetes-csi/external-snapshotter#272]
## User Story
As a user of CSI volumesnapshots, I would like to use the volumesnapshots to recover from (intentional/unintentional) deletion of my Kubernetes workloads without having to indefinitely retain all of the volumesnapshots.

## Detailed Description
Without using the `DeletionPolicy: Retain` an accidental deletion of the kubernetes namespace will trigger a cascading delete of volumesnapshots all the way through to the storage provider and there is no recovery from this.
However, using a `DeletionPolicy: Retain` can result in an increasing count of volumesnapshots.

Decoupling the lifecycle of the volumesnapshot kubernetes objects from that of the volume snapshots in the storage provider is a good middle ground between the two scenarios.

## Proposal
A new CSI driver parameter could be introduced for TTL, of volume snapshots, to decouple the lifecycle of the volumesnapshot kubernetes objects from that of the volume snapshots in the storage provider. This will be a good middle ground between the two scenarios.
The CSI drivers could possibly store unused volume snapshots (with no volumesnapshotcontent using the snapshot handle) with an expiry longer than that of the kubernetes objects. 

This may be something that is common across CSI drivers.

cc @xing-yang

**Comment by xing-yang** [comment]
Discussed at today's Volume Snapshot WG meeting.

This is asking for a 3rd deletion policy:
1. Delete - delete VolumeSnapshot, VolumeSnapshotContent, and its associated physical snapshot resource on the storage system.
2. Retain -  delete VolumeSnapshot, but keep VolumeSnapshotContent and its associated physical snapshot resource on the storage system.
3. New: SoftDelete or Delete with expiration date? - delete VolumeSnapshot and VolumeSnapshotContent, but keep associated physical snapshot resource with an expiration date.

**Comment by xing-yang** [comment]
AI: add more documentation to clarify this.

**Comment by humblec** [comment]
> Discussed at today's Volume Snapshot WG meeting.
> 
> This is asking for a 3rd deletion policy:
> 
>     1. Delete - delete VolumeSnapshot, VolumeSnapshotContent, and its associated physical snapshot resource on the storage system.
> 
>     2. Retain -  delete VolumeSnapshot, but keep VolumeSnapshotContent and its associated physical snapshot resource on the storage system.
> 
>     3. New: SoftDelete or Delete with expiration date? - delete VolumeSnapshot and VolumeSnapshotContent, but keep associated physical snapshot resource with an expiration date.

I am trying to understand this some more in detail.  When we use `delete` policy,  from the CO's user pov, it is assumed that the underlying volume or storage space is deleted is the expectation.
However this storage space/chunk is NOT limited to snapshot object , it can be the volume too which is attached with `PV` object in a PVC workflow. IMO, if we introduce  the `delete with TTL`   it should be applicable for both PVC and Snapshot workflow and shouldnt be limited to just snapshot in the backend. Because you never know how SPs implement snapshot or its references to parent volume ..etc. @xing-yang @ashish-amarnath @yuxiangqian

**Comment by xing-yang** [comment]
@humblec The existing Delete/Retain policies for VolumeSnapshot/VolumeSnapshotContent/"physical snapshot resource" are consistent with those policies for PVC/PV/"physical volume resource".  If we are thinking about introducing new policies, we do need to consider what that means for PVC/PV as well as they should be consistent.

**Comment by humblec** [comment]
> @humblec The existing Delete/Retain policies for VolumeSnapshot/VolumeSnapshotContent/"physical snapshot resource" are consistent with those policies for PVC/PV/"physical volume resource". If we are thinking about introducing new policies, we do need to consider what that means for PVC/PV as well as they should be consistent.

@xing-yang yeah, that was my ask too and good to know it will be considered for PVC. Didnt notice any kubernetes issue/KEP for similar RFE as we have here, may be I missed it.

**Comment by xing-yang** [comment]
We have not made a decision on how/whether to proceed with this.  So no issues opened.
