### ISSUE TITLE
Add E2E test for pre-provisioned snapshots (both Delete and Retain policies)

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#285]
We need E2E tests for pre-provisioned snapshots with both Delete and Retain policies.

**Comment by AndiLi99** [comment]
@ggriffiths ping on the issue here, are you working on this? I saw you may not have bandwidth here:  https://github.com/kubernetes-csi/external-snapshotter/issues/270#issuecomment-646817439

**Comment by xing-yang** [comment]
@AndiLi99 This issue is fixed by kubernetes/kubernetes#89705

**Comment by xing-yang** [comment]
Actually I think the Deletion policy is only tested with dynamically provisioned snapshots in kubernetes/kubernetes#89705.  Let me open another issue to track the pre-provisioned snapshots e2e tests.
