### ISSUE TITLE
findContentFromStore in snapshot controller potentially allows rebinding a dynamically provisioned VSC to a pre-provisioned VS

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes-csi/external-snapshotter#290]
to reproduce:
1. create a dynamic snapshot (VS1) from a PVC, this should lead to the controller to create a VolumeSnapshotContent( VSC1)
2. Update VSC1's VolumeSnapshotRef such that it points to a different VolumeSnapshot with name VS2, UID left to be empty.
3. create a pre-provisioned snapshot (VS2) which points VSC1, the two should bind.

**Comment by yuxiangqian** [comment]
cc @oleksiys

**Comment by yuxiangqian** [comment]
Just so you know, I have started working on it @xing-yang

**Comment by xing-yang** [comment]
Cool!
