### ISSUE TITLE
Deletion of a VolumeSnapshot object can causes deletion of a unbound VolumeSnapshotContent

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes-csi/external-snapshotter#291]
[checkContentAndBoundStatus](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L222) returns four values:
1. the content (NOT necessarily bound to the given VS)
2. content's deletion policy == Delete, a boolean
3. content bound to given snapshot, a boolean
4. any error

[processSnapshotWithDeletionTimestamp](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L248) calls **checkContentAndBoundStatus**, then calls **checkandRemoveSnapshotFinalizersAndCheckandDeleteContent** without verifying binding

**Comment by xing-yang** [comment]
Reproduced it:

- create a dynamic snapshot (VS1) from a PVC, this should lead to the controller to create a VolumeSnapshotContent( VSC1)
- Update VSC1's VolumeSnapshotRef such that it points to a different VolumeSnapshot with name VS2, UID left to be empty.
- create a pre-provisioned snapshot (VS2) which points VSC1, the two should bind.
- readyToUse from VS1 becomes False as VSC1 no longer points to VS1.
- delete VS1.  VSC1 will be deleted, however, it is bound to VS2 not VS1.

**Comment by xing-yang** [comment]
The fix is merged.  Closing this.
