### ISSUE TITLE
Not able to delete a VolumeSnapshot if it's corresponding VolumeSnapshotContent updates deletion policy from Delete to Retain

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes-csi/external-snapshotter#292]
Steps to reproduce the issue:
1. Create a dynamic VolumeSnapshot refer to a VolumeSnapshotClass with DeletionPolicy as Delete, this should trigger a VolumeSnapshotContent creation for the given PVC, and both VolumeSnapshot and VolumeSnapshotContent should have the following finalizer:
snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
2. Update VolumeSnapshotContent's DeletionPolicy from Delete to Retain, i.e., kubectl edit <volume-snapshot-content-name> and apply.
3. kubectl delete <volume-snapshot-name>. This should effectively remove the VolumeSnapshot from API server with VolumeSnapshotContent untouched. However the VolumeSnapshot will not be deleted from API server due to the finalizer.

Root cause is here:
https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L298

The bound finalizer should have been removed from both VolumeSnapshot and VolumeSnapshotContent even if a content exists.

**Comment by yuxiangqian** [comment]
/cc @xing-yang 
When delete a bi-directionally bound VolumeSnapshot and VolumeSnapshotContent with DeletionPolicy set to "Delete" on the content, the original idea is to wait until the VolumeSnapshotContent is removed from API server before removing the bound finalizer on VolumeSnapshot. However that does not apply to the situation when deletion policy is "Retain".

**Comment by xing-yang** [comment]
The fix is merged.  Closing this.
