### ISSUE TITLE
Support for tags parameter in VolumeSnapshotClass 

### ISSUE THREAD

**Issue by celiawa** [kubernetes-csi/external-snapshotter#295]
In our test environment (azure), we have policy set that only when the resources to be created with some specific tags are allowed to create. 

In azuredisk storageclass we can add tags like below. 
parameters:
  ...
  tags: 'foo=aaa,bar=bbb'

Can we add tags parameter for VolumeSnapshotClass.

**Comment by xing-yang** [comment]
For tags in StorageClass, is it the Azure CSI driver who decides whether to create volume or not?

**Comment by xing-yang** [comment]
Parameters field in VolumeSnapshotClass is similar to that in StorageClass.  It is up to the driver to decide what to add there and how to use them.

**Comment by celiawa** [comment]
Thanks, I'll close it and raise a request to csi.
