### ISSUE TITLE
VolumeSnapshot cannot be deleted when the VolumeSnapshotClass is missing

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-csi/external-snapshotter#306]
**What happened**:
Checking the changelog, there is #275 which should allow deletion of VolumeSnapshot when the VolumeSnapshotClass is missing, but this is not happening.

**What you expected to happen**:
I would expect to be able to delete VolumeSnapshot when its `.spec.volumeSnapshotClassName` is missing.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create PVC

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: source-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["touch /demo/data/sample-file.txt && sleep 3000"]
    volumeMounts:
    - name: source-data
      mountPath: /demo/data
  volumes:
  - name: source-data
    persistentVolumeClaim:
      claimName: source-pvc
      readOnly: false
```

2. Create a `VolumeSnapshot`.

```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: default-snapshot-class
driver: ebs.csi.aws.com
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snapshot-source-pvc
spec:
  volumeSnapshotClassName: default-snapshot-class
  source:
    persistentVolumeClaimName: source-pvc
```

3. Delete the VolumeSnapshotClass.

```
$ k get volumesnapshotclasses.snapshot.storage.k8s.io
NAME                     DRIVER            DELETIONPOLICY   AGE
default-snapshot-class   ebs.csi.aws.com   Delete           2d2h

$ k delete volumesnapshotclasses.snapshot.storage.k8s.io default-snapshot-class
volumesnapshotclass.snapshot.storage.k8s.io "default-snapshot-class" deleted
```

4. Delete the VolumeSnasphot and ensure its deletion fails:

```
$ k delete volumesnapshot snapshot-source-pvc
volumesnapshot.snapshot.storage.k8s.io "snapshot-source-pvc" deleted
```

```
$ k describe volumesnapshot snapshot-source-pvc

Events:
  Type     Reason                  Age    From                 Message
  ----     ------                  ----   ----                 -------
  Warning  GetSnapshotClassFailed  8m26s  snapshot-controller  Failed to get snapshot class with error volumesnapshotclass.snapshot.storage.k8s.io "default-snapshot-class" not found
```

**Anything else we need to know?**:

**Environment**:

- Version: v2.1.0

**Comment by xing-yang** [comment]
#275 only fixed it in the snapshot controller.  There's also a place in the csi snapshotter sidecar that needs to be fixed.  There's WIP PR to address this: https://github.com/kubernetes-csi/external-snapshotter/pull/287

**Comment by ialidzhikov** [comment]
I see that #287 is merged. But it is still not included in any release, right?

**Comment by xing-yang** [comment]
Not yet.  We are still waiting for a few PRs to be merged before cutting the next release.

**Comment by ialidzhikov** [comment]
@xing-yang , is there a target date for the v2.2.0 release?

**Comment by xing-yang** [comment]
I'm mainly waiting for 2 changes to get in before cutting the release:
- the validation web hook: https://github.com/kubernetes-csi/external-snapshotter/pull/353
- move apis and client to a separate package: https://github.com/kubernetes-csi/external-snapshotter/pull/307

**Comment by vpnachev** [comment]
Hello @xing-yang, I see that the linked PRs are merged now and most of the are part of 2.2.0-rcX releases. For when do you plan to cut the final 2.2.0 release?

**Comment by xing-yang** [comment]
There are still a couple of PRs pending.  Also waiting for this changelog PR to be merged: https://github.com/kubernetes-csi/external-snapshotter/pull/332

**Comment by xing-yang** [comment]
Release 3.0.0 is cut.  Closing this issue.

**Comment by ialidzhikov** [comment]
@xing-yang , I see that https://github.com/kubernetes-csi/external-snapshotter/pull/287 is not cherry-picked into `release-2.1` branch (please correct if I am wrong). Is there any chance to have #287 PR cherry-picked into `release-2.1`?

**Comment by ialidzhikov** [comment]
> @xing-yang , I see that #287 is not cherry-picked into `release-2.1` branch (please correct if I am wrong). Is there any chance to have #287 PR cherry-picked into `release-2.1`?

@xing-yang @msau42 any feedback on the above question?

**Comment by xing-yang** [comment]
We could.  @ialidzhikov do you want to submit a PR to backport this fix to release-2.1?

**Comment by ialidzhikov** [comment]
> We could. @ialidzhikov do you want to submit a PR to backport this fix to release-2.1?

https://github.com/kubernetes-csi/external-snapshotter/pull/466

**Comment by ialidzhikov** [comment]
Reopen as the cherry-pick for release-2.1 is still pending.

/reopen
/priority important-soon

**Comment by ialidzhikov** [comment]
Hello @xing-yang 👋 

I see that the cherry-pick PR is now merged. Is there a release date (ETA) for external-snapshotter@v2.1.4 patch release? In Gardener project (https://github.com/gardener) we are looking forward to it! Many thanks in advance and appreciate your support!

**Comment by xing-yang** [comment]
I'm working on the release.

**Comment by ialidzhikov** [comment]
@xing-yang , thank you for the release!
