### ISSUE TITLE
The VolumeSnapshotSpec object/CRD should have a 'Parameters' key-value map property

### ISSUE THREAD

**Issue by gangkui2008** [kubernetes-csi/external-snapshotter#318]
ENV: all `external-snapshotter` releases

from From https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/apis/volumesnapshot/v1beta1/types.go:
```go
// VolumeSnapshotSpec describes the common attributes of a volume snapshot.
type VolumeSnapshotSpec struct {
	// source specifies where a snapshot will be created from.
	// This field is immutable after creation.
	// Required.
	Source VolumeSnapshotSource `json:"source" protobuf:"bytes,1,opt,name=source"`

	// volumeSnapshotClassName is the name of the VolumeSnapshotClass requested by the VolumeSnapshot.
	// If not specified, the default snapshot class will be used if one exists.
	// If not specified, and there is no default snapshot class, dynamic snapshot creation will fail.
	// Empty string is not allowed for this field.
	// TODO(xiangqian): a webhook validation on empty string.
	// More info: https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes
	// +optional
	VolumeSnapshotClassName *string `json:"volumeSnapshotClassName,omitempty" protobuf:"bytes,2,opt,name=volumeSnapshotClassName"`
}
```

The `VolumeSnapshotSpec` does not have a `Parameters` key-value map, which means I can not put some special/customized values (which my CSI driver will handle) in the spec in order to create the snapshot I want.

Currently only the `VolumeSnapshotClass` object has a `Parameters` map and it allows me to put in the keys/values I wants. The `VolumeSnapshotSpec` object should have this map property too. Some keys/values are not proper to be put in the `VolumeSnapshotClass` object.

As a workaround, I can put the special keys/values to the `Parameters` map in `VolumeSnapshotClass` object and create the snapshot, but this means I need to create a lot of   different volume snapshot classes since their `Parameters` are different to each other, this is kind of mis-use of the `VolumeSnapshotClass`. In my perspective, the volume snapshot class should be a relative static resource, you should normally reuse it rather than creating each one per each volume snapshot request, that does not make sense. This problem will be gone if the `VolumeSnapshotSpec` supports a `Parameters` map. The `VolumeSnapshotSpec` object is supposed to be dynamic, and different for each volume snapshot request (since different request may require different `source`). 

Alternatively, I can add a map or additional properties in the `VolumeSnapshotSpec` object by creating my private `external-snapshotter` sidecar based on this repo, which is what we've been doing, but it's painful and kind waste of time, and I will have to check and sync my sidecar with this repo time to time.

The CSI spec, for example, also defines a `parameters` map property for the `CreateSnapshotRequest`, it intends user to put any keys/values she/he wants, so the CSI driver can handle them. But it's not possible if the `VolumeSnapshotSpec` object does not have this corresponding `parameters` map property. It will be more convenient if it has one.

Thanks very much for reviewing and considering my suggestion.

**Comment by xing-yang** [comment]
VolumeSnapshot/VolumeSnapshotContent follows the PVC/PV model.  Opaque parameters are passed thru StorageClass when creating a PVC.  Similarly opaque parameters are passed thru VolumeSnapshotClass when creating a VolumeSnapshot.  Parameters field in the CSI spec maps to the StorageClass or VolumeSnapshot in k8s.  The reason that we don't have another parameters field directly in VolumeSnapshotSpec or PersistentVolumeClaimSpec is to support workload portability.  To add a new first class field, we need to have a very strong use case for that.  What exactly are the key/values that you want to add?  What are they for?

**Comment by gangkui2008** [comment]
We are developing a CDP(Continuous Data Protection) product, in which we allow user to specify a timestamp to create the snapshot based on for an existing volume (e.g. capture a snapshot of a volume with its 2 minutes ago's state). This timestamp could be different for each volume snapshot request, even for the same volume. This timestamp should be put in the `VolumeSnapshotSpec` instead of `VolumeSnapshotClass` from my perspective. Any values important to the volume but irrelevant to the `Class` should be put in the `Spec` object instead of the `Class` object I think.

**Comment by xing-yang** [comment]
When the snapshot is cut, there is a timestamp in VolumeSnapshot status which is returned by the CSI driver.  Why can't you use that timestamp?

**Comment by gangkui2008** [comment]
I might not explained the timestamp I used well. The timestamp in VolumeSnapshot status, called `creationTime`, means "when this snapshot was created", it's updated and returned by the CSI driver.

The timestamp I mentioned, which will be specified by end user of our product, I will call it `protectionTime`, means "on what time of this volume do you want to create a snapshot".  They're totally different. The CDP volume is like a timeline, you can rewind your data to any time past on this timeline. A typical scenario, say I have a CDP volume/PV running in production, and now (2020-05-23T22:22:29Z) I want to create a snapshot on 2020-05-22T22:22:29Z (one day ago) with that volume (e.g. I just realized something went wrong after that time, so I want to rewind my data to that time), so I will set protectionTime=2020-05-22T22:22:29Z and CSI driver will set creationTime=2020-05-23T22:22:29Z. All I want to say, it's end user to decide and provide this `protectionTime` beforehand, not CSI driver afterwards.

**Comment by yuxiangqian** [comment]
@gangkui2008 thank you for providing the use case.
After reading all the threads, I am not convinced VolumeSnapshotSpec *should* have an opaque key-val map in it and there are good reasons why we do not want that in the API. The k-v opaque map in volumesnapshotclass/storageclass is specifically introduced to fit the reality that different storage vendors need different input to provision/snapshot/resize a volume such that a unified CSI interface is possible.
From the use case you mentioned, (correct me if I am wrong), it sounds to me the underlying storage system has some kinda of "scheduled" or "continuous" process (outside of Kubernetes) to checkpoint/snapshot a volume. And those checkpoints could be later on be used to restore a volume to that state. And it sounds to me that your system is trying to utilize this functionality to "map" those checkpoints to K8s snapshots by supplying a "desired snapshot" timestamp to the storage system. And as those desired snapshot timestamps are dynamic, so it does not fit into the VolumeSnapshotClass opaque k-v map.
While I agree using VolumeSnapshotClass opaque k-v map to pass those timestamps is certainly a pain and a misuse of it, I also disagree those should be part of VolumeSnapshotSpec. IMO, your system is trying to "statically" bind or import an existing snapshot on the storage system, have you thought about utilizing the static binding feature? can you elaborate when you call CSI with such. a desired timestamp, what would the underlying storage system do?
