### ISSUE TITLE
Cannot create snapshot from existing snapshot content

### ISSUE THREAD

**Issue by igorgonibm** [kubernetes-csi/external-snapshotter#321]
1) created snapshot class with retain deletion (class_retain.yaml)
2) created snapshot (snapshot_retain.yaml)
3) snapshot content was created succerssfully
4) deleted the snapshot
5) snapshot content was not deleted (as expected)
6) created new snapshot from this snapshot content as source
7) snapshot stays not ready and controller didn't receive CreateSnapshot request

All relevant yamls and logs attached
[from_content_logs.zip](https://github.com/kubernetes-csi/external-snapshotter/files/4758020/from_content_logs.zip)

**Comment by igorgonibm** [comment]
Changed version as requested. Controller log says content is bound to a different snapshot. Attached logs.
[211.zip](https://github.com/kubernetes-csi/external-snapshotter/files/4763393/211.zip)

**Comment by xing-yang** [comment]
What is the result of "kubectl get volumesnapshot snap-from-content -o yaml"?

**Comment by xing-yang** [comment]
See this error here: 
```
I0611 07:49:20.384094       1 snapshot_controller.go:124] syncContent [snapcontent-9a7fcab2-21f0-4c44-b74f-603de0b9e90d]: snapshot default/snap-from-content has different UID, the old one must have been deleted
```
It says your content still has the UID from the previous snapshot which is different from the UID from the new snapshot.

For pre-provisioned snapshot, you need to create a new VolumeSnapshotContent.  You can't use the old VolumeSnapshotContent which was created from the dynamic provisioning.

**Comment by igorgonibm** [comment]
Oh I didn't se this limitation.
Is there an  example how to create VolumeSnapshotContent from the scratch?

**Comment by xing-yang** [comment]
There's an example in this blog.  Search for the section titled "Importing an existing volume snapshot with Kubernetes":

https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/

**Comment by igorgonibm** [comment]
Thank you. Created new objects according to the ink. Still get error. "snapshot-controller  Failed to check and update snapshot: VolumeSnapshotContent [imp-snap-cont] is bound to a different snapshot"

[new.zip](https://github.com/kubernetes-csi/external-snapshotter/files/4765220/new.zip)

**Comment by igorgonibm** [comment]
It seems there is a mistake in the import snapshot example in the  link you specified:
- In VolumeSnapshotConent volumeSnapshotRef:->name value is test-snapshot but it should be  manually-created-snapshot
- In VolumeSnapshot volumeSnapshotContentName is test-content but it should be manually-created-snapshot-content

**Comment by xing-yang** [comment]
Glad it worked.

Yeah, the VolumeSnapshotRef name should be changed to manually-created-snapshot in the example.

**Comment by igorgonibm** [comment]
And the volumeSnapshotContentName should be changed too, right?
