### ISSUE TITLE
Can not delete imported snapshot - wrong secret

### ISSUE THREAD

**Issue by roysahar-ibm** [kubernetes-csi/external-snapshotter#325]
Scenario -
Import a volumesnapshotcontent from existing snapshot on storage.
Create a volumesnapshot with the imported volumesnapshotcontent.
Delete the volumesnapshot failed.
Looks like our csi driver does not receive correct secret (storage address/endpoint argument is empty).
Attached all logs and yamls.
[delete_snap_imported.zip](https://github.com/kubernetes-csi/external-snapshotter/files/4818674/delete_snap_imported.zip)

**Comment by xing-yang** [comment]
In your secret yaml file, you have stringData:
```
kind: Secret
apiVersion: v1
metadata:
  name: br-secret
  namespace: kube-system
type: Opaque
stringData:
  management_address: XXXXXXXXXX # Array management addresses
  username: XXXXXXXXXX   # Array username
data:
  password: XXXXXXXXXX            # Array password Passw0rd
```

I can't find stringData defined in the Secret API:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L4768

Where did you find this Secret API definition that has stringData?

Can you show the results of "kubectl describe secret"?

**Comment by xing-yang** [comment]
Snapshotter only retrieves "data" from Secret, not "stringData".

**Comment by roysahar-ibm** [comment]
> kubectl describe secret

Name:         br-secret
Namespace:    kube-system
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
username:            5 bytes
management_address:  21 bytes
password:            10 bytes

**Comment by xing-yang** [comment]
What about "kubectl get secret -o yaml"?

**Comment by roysahar-ibm** [comment]
> kubectl get secret -o yaml

apiVersion: v1
data:
  management_address: XXXXXXXXXXXXXXXXXXXXXXX
  password: XXXXXXXXXXXXXXXXXXXXXXX
  username: XXXXXXXXXXXXXXXXXXXXXXX
kind: Secret
metadata:
  creationTimestamp: "2020-06-22T21:47:41Z"
  name: br-secret
  namespace: kube-system
  resourceVersion: "2289"
  selfLink: /api/v1/namespaces/kube-system/secrets/br-secret
  uid: d6ddab60-dc59-4f12-87d6-5e74483a97b2
type: Opaque

**Comment by xing-yang** [comment]
Did you get password correctly in your driver?  Are management_address and username both empty?  How does the management_address look like?  Is it like 1.2.3.4:12?

Can you try to create secret like this?

```
kind: Secret
apiVersion: v1
metadata:
  name: br-secret
  namespace: kube-system
type: Opaque
data:
  management_address: XXXXXXXXXX # Array management addresses
  username: XXXXXXXXXX   # Array username
  password: XXXXXXXXXX            # Array password Passw0rd
```

**Comment by xing-yang** [comment]
I found where "stringData" is defined:
https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5511

"stringData" only allows you write data.  It gets merged into "data" when the secret is created, however, that data is not readable.  If you want "management_address" to be retrieved from secret at delete snapshot time, you need to store "management_address" under "data", not "stringData".

**Comment by roysahar-ibm** [comment]
> I found where "stringData" is defined:
> https://github.com/kubernetes/api/blob/master/core/v1/types.go#L5511
> 
> "stringData" only allows you write data. It gets merged into "data" when the secret is created, however, that data is not readable. If you want "management_address" to be retrieved from secret at delete snapshot time, you need to store "management_address" under "data", not "stringData".

Could you please write an example of secret yaml with "data" instead of "stringData"?

**Comment by xing-yang** [comment]
```
kind: Secret
apiVersion: v1
metadata:
  name: br-secret
  namespace: kube-system
type: Opaque
data:
  management_address: XXXXXXXXXX # Array management addresses
  username: XXXXXXXXXX   # Array username
  password: XXXXXXXXXX            # Array password Passw0rd
```

**Comment by roysahar-ibm** [comment]
> ```
> kind: Secret
> apiVersion: v1
> metadata:
>   name: br-secret
>   namespace: kube-system
> type: Opaque
> data:
>   management_address: XXXXXXXXXX # Array management addresses
>   username: XXXXXXXXXX   # Array username
>   password: XXXXXXXXXX            # Array password Passw0rd
> ```

Hi,
The new template of secret does not help, still getting:

I0623 18:18:38.322463       1 snapshot_controller_base.go:144] enqueued "manually-created-snapshot-content" for sync
I0623 18:18:38.322483       1 snapshot_controller_base.go:159] contentWorker[manually-created-snapshot-content]
I0623 18:18:38.322506       1 util.go:169] storeObjectUpdate updating content "manually-created-snapshot-content" with version 27162
I0623 18:18:38.322522       1 snapshot_controller.go:58] synchronizing VolumeSnapshotContent[manually-created-snapshot-content]
I0623 18:18:38.322545       1 snapshot_controller.go:569] Check if VolumeSnapshotContent[manually-created-snapshot-content] should be deleted.
I0623 18:18:38.322557       1 snapshot_controller.go:61] VolumeSnapshotContent[manually-created-snapshot-content]: the policy is Delete
I0623 18:18:38.322566       1 snapshot_controller.go:102] schedule to delete snapshot, operation named delete-manually-created-snapshot-content
I0623 18:18:38.322570       1 snapshot_controller.go:112] scheduleOperation[delete-manually-created-snapshot-content]
I0623 18:18:38.322591       1 snapshot_controller.go:367] deleteCSISnapshotOperation [manually-created-snapshot-content] started
I0623 18:18:38.322596       1 snapshot_controller.go:218] getCSISnapshotInput for content [manually-created-snapshot-content]
I0623 18:18:38.322600       1 snapshot_controller.go:477] getSnapshotClass: VolumeSnapshotClassName [snpc-testcreatesnapshotsanity]
I0623 18:18:38.322611       1 connection.go:182] GRPC call: /csi.v1.Controller/DeleteSnapshot
I0623 18:18:38.322615       1 connection.go:183] GRPC request: {"snapshot_id":"SVC:60050760718106998000000000009926"}
I0623 18:18:38.325076       1 connection.go:185] GRPC response: {}
I0623 18:18:38.325539       1 connection.go:186] GRPC error: rpc error: code = Internal desc = an internal exception occurred : Could not identify the type for endpoint: ['']
E0623 18:18:38.325596       1 goroutinemap.go:150] Operation for "delete-manually-created-snapshot-content" failed. No retries permitted until 2020-06-23 18:18:46.325571208 +0000 UTC m=+2048.059795298 (durationBeforeRetry 8s). Error: "failed to delete snapshot \"manually-created-snapshot-content\", err: failed to delete snapshot content manually-created-snapshot-content: \"rpc error: code = Internal desc = an internal exception occurred : Could not identify the type for endpoint: [''] \""
I0623 18:18:38.325628       1 event.go:281] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"manually-created-snapshot-content", UID:"9eedc139-c16d-4a4a-ab8b-dfcfac9b4c09", APIVersion:"snapshot.storage.k8s.io/v1beta1", ResourceVersion:"27162", FieldPath:""}): type: 'Warning' reason: 'SnapshotDeleteError' Failed to delete snapshot
I0623 18:18:53.322858       1 reflector.go:432] github.com/kubernetes-csi/external-snapshotter/pkg/client/informers/externalversions/factory.go:117: Watch close - *v1beta1.VolumeSnapshotClass total 0 items received

**Comment by xing-yang** [comment]
I wonder if you have some special character that can't be recognized by the secret.  Is it a string or array?  Any special char?

**Comment by roysahar-ibm** [comment]
> I wonder if you have some special character that can't be recognized by the secret. Is it a string or array? Any special char?

No special chars.
All strings (for user, server, and password)

**Comment by igorgonibm** [comment]
@xing-yang just to mention. We use the secrets in this format for other operations in our driver. 
Create snapshot works with it. And also delete snapshot works (when it is not imported one)
thank you

**Comment by xing-yang** [comment]
What are the results of "kubectl get volumesnapshot -o yaml" and "kubectl get volumesnapshotcontent -o yaml"?

When a snapshot is dynamically provisioned, the secret's name and namespace will be added as annotation to the content if they are specified in the class. 

If a snapshot is pre-provisioned, user has to make ensure the secret annotation is on the content.

When deleting the snapshot (if deletion policy is delete), the secret name and namespace will be retrieved from the content annotation and data in the secret will be read and passed to the CSI driver to delete the snapshot.  This logic to read the secret and pass to the driver is the same for dynamically provisioned snapshot and pre-provisioned ones.  Unless if the annotation is different or the secret itself is changed, I don't know why it works for dynamic but not for pre-provisioned.

**Comment by roysahar-ibm** [comment]
> kubectl get volumesnapshot -o yaml

**volumesnapshot:**
apiVersion: v1
items:
- apiVersion: snapshot.storage.k8s.io/v1beta1
  kind: VolumeSnapshot
  metadata:
    creationTimestamp: "2020-06-25T07:28:51Z"
    finalizers:
    - snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    - snapshot.storage.kubernetes.io/volumesnapshot-bound-protection
    generation: 1
    name: test-snapshot
    namespace: default
    resourceVersion: "10243"
    selfLink: /apis/snapshot.storage.k8s.io/v1beta1/namespaces/default/volumesnapshots/test-snapshot
    uid: ae8c4d0b-ecf0-42a9-8bfd-a18323f7e4c5
  spec:
    source:
      volumeSnapshotContentName: manually-created-snapshot-content
  status:
    boundVolumeSnapshotContentName: manually-created-snapshot-content
    creationTime: "2020-06-25T07:29:52Z"
    readyToUse: true
    restoreSize: "0"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**volumesnapshotcontent:**
apiVersion: v1
items:
- apiVersion: snapshot.storage.k8s.io/v1beta1
  kind: VolumeSnapshotContent
  metadata:
    creationTimestamp: "2020-06-25T07:29:52Z"
    finalizers:
    - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
    generation: 2
    name: manually-created-snapshot-content
    resourceVersion: "10241"
    selfLink: /apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/manually-created-snapshot-content
    uid: e4f241de-0e22-4558-85c1-2500276b711e
  spec:
    deletionPolicy: Delete
    driver: block.csi.ibm.com
    source:
      snapshotHandle: SVC:60050760718106998000000000009BDA
    volumeSnapshotClassName: snpc-testcreatesnapshotsanity
    volumeSnapshotRef:
      name: test-snapshot
      namespace: default
      uid: ae8c4d0b-ecf0-42a9-8bfd-a18323f7e4c5
  status:
    creationTime: 1593070192800557242
    readyToUse: true
    restoreSize: 0
    snapshotHandle: SVC:60050760718106998000000000009BDA
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by xing-yang** [comment]
You need to add secret annotations to your VolumeSnapshotContent manually for pre-provisioned snapshots.

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  annotations:
    snapshot.storage.kubernetes.io/deletion-secret-name: <secret-name>
    snapshot.storage.kubernetes.io/deletion-secret-namespace: <secret-namespace>
```

**Comment by roysahar-ibm** [comment]
Hi,
It worked thanks.

**Comment by roysahar-ibm** [comment]
Worked when adding secret annotations on volumesnapshotcontent.
