### ISSUE TITLE
will add 'additionalPrinterColumns' for snapshot?

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/external-snapshotter#328]
like this: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

**Comment by Kartik494** [comment]
Hi @zhucan there is already "additionalPrinterColumns" present in [yaml](https://github.com/kubernetes-csi/external-snapshotter/blob/master/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml#L12), could you clarify more on this?
