### ISSUE TITLE
release v2.2.0-alpha1?

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/external-snapshotter#330]
For https://github.com/kubernetes-csi/external-provisioner/pull/450 I'd like to import a revision of the external-snapshotter which supports the client-go API from Kubernetes >= 1.18. The code has been merged into master, so I could use that, but doing a formal release might be cleaner.

IMHO it is not necessary to bump the major version number: the usual purpose of that is to support co-existence of incompatible module versions, but that doesn't work here because there can be only one copy of client-go. So all it does is signal a breaking change, which will be obvious once code no longer compiles after an update and can also be documented in the release notes.

**Comment by xing-yang** [comment]
I'm waiting for a couple of PRs to get merged before cutting the next release.  If you need it sooner, we can cut a RC version first.

**Comment by pohly** [comment]
Do you have an estimate when that next regular release might be ready?

There's no immediate need for a RC, but something by the end of this week might be good.

**Comment by xing-yang** [comment]
RC build is cut: https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v2.2.0-rc1
