### ISSUE TITLE
VolumeSnapshotContent with Retain policy cannot be deleted

### ISSUE THREAD

**Issue by smitaraut** [kubernetes-csi/external-snapshotter#336]
I created a VolumeSnapshot dynamically with deletionPolicy as "Retain". Then I deleted the VolumeSnapshot, it got deleted but the corresponding VolumeSnapshotContent remained, which is expected.
Now I explicitly tried to delete the VolumeSnapshotContent but it never gets deleted.

One observation is that the "volumesnapshotcontent-bound-protection" finalizer is still there on the object. The code to remove this finalizer is never getting invoked in case of Retain policy. The culprit seems to be sidecar-controller/snapshot_controller.shouldDelete(). The only conditions when it can return true are-

        if content.Spec.Source.SnapshotHandle != nil && content.Spec.VolumeSnapshotRef.UID == "" 
and 

	if metav1.HasAnnotation(content.ObjectMeta, utils.AnnVolumeSnapshotBeingDeleted) 

Neither of these are true in case of the VolumeSnapshotContent in concern and hence the finalizer removal code is never invoked. However if I manually delete the finalizer by editing the object, the VolumeSnapshotContent gets deleted.

Snapshotter image version used: v2.1.1
Kubernetes version: v1.18.2

**Comment by xing-yang** [comment]
Can you try this with snapshot-controller:canary and csi-snapshotter-canary images?

**Comment by smitaraut** [comment]
Problem was that the controller manifest file given at below location pointed to controller image v2.0.1
[https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v2.1.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
](https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v2.1.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml)

When I changed the image to 2.1.1 the problem could no longer be recreated.

**Comment by xing-yang** [comment]
It's good to know that 2.1.1 works.
Yeah, we need to update those images.
