### ISSUE TITLE
Provide an option to pass snapshot metadata to csi driver

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-snapshotter#341]
When external snapshotter sends a request to the csi-driver it doesn't contain any additional information about the snapshot name, snapshot namespace, or the snapshot content name, it would be nice if we can provide an option to do the same. currently the same feature is available in external-provisioner to pass the PVC metadata (PVC name, namespace, and PV name) as additional parameters in createvolume requests when `--extra-create-metadata`.

cc @xing-yang 

Let me know if it sounds good, I can work on it.

**Comment by xing-yang** [comment]
Can you provide use cases for the need for these metadata?  Why are they needed?  If we decide to pass these 3 types of metadata, why don't we also pass other metadata?

I see that external-provisioner has them, but I didn't follow the initial introduction of those metadata.  So I'd like to know why those were added to the external-provisioner side as well.

**Comment by msau42** [comment]
It was added in external-provisioner to retain the in-tree behavior of being able to label the underlying disk resource with the Kubernetes workload information

**Comment by xing-yang** [comment]
We don't have in-tree implementation of volume snapshots.  Does it make sense to do the same thing for volume snapshots?

I remember that we actually have tags in our very early snapshot implementation in external-storage repo, but we were asked to drop it when working on the alpha design.

**Comment by msau42** [comment]
I think it makes sense to be able to label all the underlying disk/snapshot resources similarly. It would help associate the underlying resource with the Kubernetes object.

**Comment by Madhu-1** [comment]
Yes even we have a requirement, we need want to replicate the snapshot object to remote kubernetes cluster and reuse the underlying storage snapshot for disaster recovery. Using the snapshot name and namespace name as part of  CreateSnapshot help us to name the backend and use it in the remote cluster.

**Comment by xing-yang** [comment]
I’m not against this and I think it is useful, but I want to make sure that we are using a consistent criteria to determine what metadata should or should not be passed to the CSI driver.  We have got other requests to pass additional metadata to CSI driver such as this one here: https://github.com/kubernetes-csi/external-snapshotter/issues/318

CC @saad-ali  @jingxu97  @yuxiangqian Any objections on passing the snapshot metadata (snapshot name/namespace and content name) to the CSI driver when creating a snapshot?

**Comment by humblec** [comment]
IMO, like  external provisioner allow the `extra-metadada` we could have the same facility here on snapshot too.

**Comment by yuxiangqian** [comment]
While I do see it's legit request to pass K8s names to for labeling on underlying resources in storage system like PVs/Snapshots, I dislike the idea of letting the side car controller to understand more opaque parameters from the class.(though we are already doing that for secrets, but that's for filtering out). Mixing-usage of the prefix also seems to be a bit confusing. I am not sure if snapshot class parameters have to be in the picture here as I do not see those parameters would drive the controller's behavior. As long as the flag has been set to true, the controller will add those pairs from the current implementation. Maybe move "RemovePrefixedParameters" up to sidecar's snapshot_controller.go before invoking handler.CreateSnapshot makes it a bit more cleaner.

**Comment by chrishenzie** [comment]
PR has since been updated. If you can take another look I appreciate it.
