### ISSUE TITLE
Create volumesnapshot from snapshot content of retain volumesnapshot failed

### ISSUE THREAD

**Issue by roysahar-ibm** [kubernetes-csi/external-snapshotter#345]
Scenario:
---------
* Create pvc.
* Create volumesnapshotclass with "deletionPolicy: Retain".
* Create volumesnapshot from the created pvc.
* Delete the volumesnapshot, its volumesnapshotcontent remain as should be by design.
* Create a volumesnapshot with the content that remain ==> Failed:
 "Snapshot failed to bind   VolumeSnapshotContent, Could not bind snapshot snap-testcreatesnapshotsanity and content   snapcontent-b8d40545-5c72-4df3-ad3d-7a9e227667b3, the VolumeSnapshotRef does not match."

volumesnapshotcontent
----------------------
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  annotations:
    snapshot.storage.kubernetes.io/deletion-secret-name: svc-secret
    snapshot.storage.kubernetes.io/deletion-secret-namespace: kube-system
  creationTimestamp: "2020-08-01T14:10:30Z"
  finalizers:
  - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  generation: 1
  name: snapcontent-b8d40545-5c72-4df3-ad3d-7a9e227667b3
  resourceVersion: "2972"
  selfLink: /apis/snapshot.storage.k8s.io/v1beta1/volumesnapshotcontents/snapcontent-b8d40545-5c72-4df3-ad3d-7a9e227667b3
  uid: 559f5d1d-ba54-4340-a9ef-fdb1738fd773
spec:
  deletionPolicy: Retain
  driver: block.csi.ibm.com
  source:
    volumeHandle: SVC:6005076071810699800000000000D790
  volumeSnapshotClassName: snpc-testcreatesnapshotsanity
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1beta1
    kind: VolumeSnapshot
    name: snap-testcreatesnapshotsanity
    namespace: default
    resourceVersion: "2841"
    uid: b8d40545-5c72-4df3-ad3d-7a9e227667b3
status:
  creationTime: 1596291081310089000
  readyToUse: true
  restoreSize: 1073741824
  snapshotHandle: SVC:6005076071810699800000000000D791

volumesnapshot
--------------
apiVersion: v1
items:
- apiVersion: snapshot.storage.k8s.io/v1beta1
  kind: VolumeSnapshot
  metadata:
    creationTimestamp: "2020-08-01T14:34:38Z"
    finalizers:
    - snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
    generation: 1
    name: snap-testcreatesnapshotsanity
    namespace: default
    resourceVersion: "6411"
    selfLink: /apis/snapshot.storage.k8s.io/v1beta1/namespaces/default/volumesnapshots/snap-testcreatesnapshotsanity
    uid: ee9ab273-1d8e-41a4-bd04-43abe7e37bd1
  spec:
    source:
      volumeSnapshotContentName: snapcontent-b8d40545-5c72-4df3-ad3d-7a9e227667b3
    volumeSnapshotClassName: snpc-testcreatesnapshotsanity
  status:
    error:
      message: Snapshot failed to bind VolumeSnapshotContent, Could not bind snapshot
        snap-testcreatesnapshotsanity and content snapcontent-b8d40545-5c72-4df3-ad3d-7a9e227667b3,
        the VolumeSnapshotRef does not match
      time: "2020-08-01T14:34:38Z"
    readyToUse: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by xing-yang** [comment]
This works as designed.  We do not support binding a new VolumeSnapshot to a pre-existing VolumeSnapshotContent.  You'll have to create a new VolumeSnapshotContent and then create a new VolumeSnapshot to bind with the new content.  For the existing VolumeSnapshotContent, make sure its policy is Retain and delete it.
