### ISSUE TITLE
Generate api clients for Java

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#359]
Some consumers of the snapshots api are written in Java, so providing a Java client would be useful.

/kind feature

**Comment by Kartik494** [comment]
Hi @xing-yang @msau42   As These are the kubernetes client supported [libraries](https://kubernetes.io/docs/reference/using-api/client-libraries/#officially-supported-kubernetes-client-libraries) , so for snapshots api we have to add the support Likewise mentioned in the [docs](https://github.com/kubernetes-client/java#installation) ? Please suggest is this the right approach for providing java client!

**Comment by xing-yang** [comment]
@Kartik494 Yes.
