### ISSUE TITLE
Add e2e stress test

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#361]
That creates and restores a lot of snapshots.

Can use https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/stress.go as a starting point.

**Comment by xing-yang** [comment]
Hi @Kartik494,

Are you going to work on this in 1.20?  We need this for bringing snapshot to GA in 1.20.  Thanks.

**Comment by Kartik494** [comment]
Hi @xing-yang I am working on some other issues (https://github.com/kubernetes-csi/external-snapshotter/issues/368)  (https://github.com/kubernetes-csi/external-snapshotter/issues/359)  too ,I am unassigning myself if someone else would like to work on this.
Thanks

**Comment by chrishenzie** [comment]
Please see https://github.com/kubernetes/kubernetes/pull/95971

**Comment by xing-yang** [comment]
It is done.
