### ISSUE TITLE
Allow SP to record some opaque parameters in the snapshot content object.

### ISSUE THREAD

**Issue by humblec** [kubernetes-csi/external-snapshotter#379]
At present volumesnapshot object does not have a provision to record parameters which can be consumed later by the SP for its own use.  Like in PVC -> PV workflow, the volumeattribute ( volumeContext in createvolumeresponse) can carry some information which is opaque in the PV.  Like that , volumesnapshot/content object should have a provision to keep similar data. This is missing atm ( no snapshotcontext or similar stuff), and there is no way to retrieve such information later when SP want to make use of it.  Like in SC , SnapshotClass could carry this information, but considering snapshotclass is not tied to lifecycle of snapshot of snapshotcontent, we can not rely on that. 

@xing-yang @msau42 @jsafrane  @saad-ali thoughts?

**Comment by Madhu-1** [comment]
currently, CSI spec doesn't the csi driver to return the context in CreateSnapshotResponse, isn't it better to open an issue in CSI spec repo?

**Comment by xing-yang** [comment]
volume_context is needed in ControllerPublishVolume, NodeStageVolume, NodePublishVolume, and ValidateVolumeCapabilities RPCs.  We don't have such RPCs for volume snapshot that need snapshot_context.
