### ISSUE TITLE
Document how to use quota with snapshot CRs

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#382]
Add documentation in README to explain how to use quota with VolumeSnapshot resources:
See example here for custom resources: https://kubernetes.io/docs/concepts/policy/resource-quotas/#object-count-quota

Since the support is only added for namespaced CRD's, we can only use quota for VolumeSnapshot resources, but not VolumeSnapshotContent and VolumeSnapshotClasses.

**Comment by boddumanohar** [comment]
I would like to take-up this task
