### ISSUE TITLE
The volume was created through snapshot rollback, causing K8S POD to fail to start

### ISSUE THREAD

**Issue by fantastic2085** [kubernetes-csi/external-snapshotter#403]
A volume is recovered by snapshot rollback, but CSI needs to add the Flatten feature. Kernel version 3.10.0-1127.el7.x86_64 does not support this feature, causing K8S POD to fail to start.The CSI version is 3.0.0

![image](https://user-images.githubusercontent.com/4116773/96536744-5348bd80-12c7-11eb-92b8-6477ce48d4a8.png)
How can flatten be banned?

**Comment by xing-yang** [comment]
CSI only supports creating a new volume from snapshot.  CSI does not support snapshot rollback.  Can you provide more details on what steps you took to rollback snapshot?
