### ISSUE TITLE
Use driver name from PV instead of from StorageClass to validate

### ISSUE THREAD

**Issue by yuxiangqian** [kubernetes-csi/external-snapshotter#404]
In current implementation, [SetDefaultSnapshotClass](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L1189) relies on PVC's StorageClass to find the driver name. Instead its more appropriate to rely on PV's driver name as StorageClass can be updated after a volume has been provisioned.

Per discussion in https://github.com/kubernetes/kubernetes/issues/94312

**Comment by msau42** [comment]
Should also evaluate where else we depend on storageclass and see if we can remove that dependency
