### ISSUE TITLE
snapshot-validation-webhook should reload server certificate on update

### ISSUE THREAD

**Issue by misterikkit** [kubernetes-csi/external-snapshotter#422]
If the server certificate for snapshot-validation-webhook is updated, we should begin using the new certificate instead of the old.

This is required if we are to support credential rotation. For example, an external service may update the k8s secret with this pod's certificate.

hat tip to @msau42 for pointing out that [controller runtime][1] already has this feature.

[1]: https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/webhook/internal/certwatcher

**Comment by msau42** [comment]
/kind bug
/assign @yuxiangqian @xing-yang 

Please add this to your GA task list

**Comment by msau42** [comment]
and we should backport the fix

**Comment by xing-yang** [comment]
Sure

**Comment by xing-yang** [comment]
Discussed with @yuxiangqian about this.  We can watch `/etc/snapshot-validation-webhook/certs` for cert rotation and restart the webhook server when it happens.

**Comment by msau42** [comment]
For my understanding, is there a reason why we don't use controller-runtime for the webhook (which already handles rotation?)

**Comment by ggriffiths** [comment]
I briefly looked into that package while looking at this issue. One thing I noticed while looking into the controller-runtime webhook is that it assumes the cert and key are required to be in the same directory. 
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/server.go#L53-L61

The current snapshotter implementation supports direct file paths:
https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/validation-webhook/webhook.go#L51-L54

So, switching to use the controller-runtime webhook would introduce this breaking change. If that change is okay, then I'm not aware of any other reasons (though I'm new to this webhook pkg).

**Comment by xing-yang** [comment]
@yuxiangqian can you answer this question?  Is this because we are not using kubebuilder?

**Comment by yuxiangqian** [comment]
> For my understanding, is there a reason why we don't use controller-runtime for the webhook (which already handles rotation?)
>

I think the main reason is the current snapshot controllers are hand written. One of the best way of using controller-runtime is to use kubebuilder to autogen controller/webhook skeleton. Andi has tried that option and it was too much work on getting it to work in the current code structure.
