### ISSUE TITLE
Add metric for detecting metrics operation leaks in snapshot controller

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes-csi/external-snapshotter#434]
It is possible that operation leaks can occur if logic changes happen in the snapshot controller. We should add a metric to count how many snapshot operations are cached. If this count does not decrease after any operation is finished, we have an operation cache leak.

_Originally mentioned by @msau42 in https://github.com/kubernetes-csi/external-snapshotter/pull/409#discussion_r532979019_

**Comment by msau42** [comment]
Another thing to investigate is if golang itself has any tools/metrics that could help us so we don't have to do something custom.

**Comment by ggriffiths** [comment]
Yes, will look into that as part of this.

**Comment by ggriffiths** [comment]
/remove-lifecycle stale
Picking up this work soon.

**Comment by ggriffiths** [comment]
/remove-lifecycle stale
PR opened for this
