### ISSUE TITLE
transport is closing

### ISSUE THREAD

**Issue by GongWilliam** [kubernetes-csi/external-snapshotter#45]
hey there , can anybody tell me what problem is this ? any information would be appreciated.

I1018 13:25:25.835377       1 snapshot_controller.go:304] createSnapshot[default/new-snapshot-demo]: started
I1018 13:25:25.835403       1 snapshot_controller.go:279] scheduleOperation[create-default/new-snapshot-demo[45f5dfea-d2d9-11e8-b369-5254008caa0c]]
I1018 13:25:25.835507       1 snapshot_controller.go:447] createSnapshot: Creating snapshot default/new-snapshot-demo through the plugin ...
I1018 13:25:25.835531       1 snapshot_controller.go:455] createSnapshotOperation [new-snapshot-demo]: VolumeSnapshotClassName [csi-smtx-snapclass]
I1018 13:25:25.835548       1 snapshot_controller.go:769] getSnapshotClass: VolumeSnapshotClassName [csi-smtx-snapclass]
I1018 13:25:25.879883       1 snapshot_controller.go:738] getVolumeFromVolumeSnapshot: snapshot [new-snapshot-demo] PV name [pvc-18289bde-d2d9-11e8-b369-5254008caa0c]
I1018 13:25:25.879971       1 connection.go:192] CSI CreateSnapshot: snapshot-45f5dfea-d2d9-11e8-b369-5254008caa0c
I1018 13:25:25.880031       1 connection.go:259] GRPC call: /csi.v0.Identity/GetPluginInfo
I1018 13:25:25.881293       1 connection.go:261] GRPC response: name:"com.csi" vendor_version:"0.1"
I1018 13:25:25.881412       1 connection.go:262] GRPC error: <nil>
I1018 13:25:25.881432       1 connection.go:259] GRPC call: /csi.v0.Controller/CreateSnapshot
I1018 13:25:27.934872       1 connection.go:261] GRPC response:
I1018 13:25:27.935230       1 connection.go:262] GRPC error: rpc error: code = Unavailable desc = transport is closing

**Comment by zhucan** [comment]
maybe your csi driver is not healthy， please check the "sock"

**Comment by abrden** [comment]
I'm having the same problem. @GongWilliam any info on how to solve it? I already checked the csi-sock but I don't think that's the issue, my csi driver is responding to `GRPC call: /csi.v0.Identity/GetPluginInfo` like yours, but not to `GRPC call: /csi.v0.Controller/CreateSnapshot` :/

**Comment by FengyunPan2** [comment]
any thoughts?
