### ISSUE TITLE
YAML manifests should have multiple document delimiter

### ISSUE THREAD

**Issue by tsunny** [kubernetes-csi/external-snapshotter#455]
Found document delimiter(`---`) missing in few manifests. This causes malformed YAML when loading it in ruby.

Files with missing document delimiter:
- https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml#L11
- https://github.com/tsunny/external-snapshotter/blob/master/deploy/kubernetes/csi-snapshotter/rbac-external-provisioner.yaml#L11
- https://github.com/kubernetes-csi/external-snapshotter/blob/v3.0.3/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml#L8
- https://github.com/kubernetes-csi/external-snapshotter/blob/v3.0.3/deploy/kubernetes/webhook-example/webhook.yaml#L1

**Comment by grosser** [comment]
technically not needed since they are single resources, but nice for consistency 👍
