### ISSUE TITLE
CreateSnapshot being called several times when only one Snapshot is wanted.

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes-csi/external-snapshotter#465]
I am testing the csi-snapshotter metrics. And I had this little experiment in my env. Basically I just created one VolumeSnapshot. And the snapshot was created successfully.
When I check my snapshotter metrics, it seems that it has recorded a lot of CreateVolume event. And I checked my driver log, it also has a lot of CreateVolume call like 20ish times.

I checked with @msau42 and she mentioned this has been discussed here: 
https://github.com/kubernetes-csi/external-snapshotter/pull/165#discussion_r318373725

So this is just a follow-up to discuss what should we do about it.

**Comment by xing-yang** [comment]
Which version of external-snapshotter are you using?

**Comment by Jiawei0227** [comment]
I am using v3.0.1, does this get fixed in v4?

**Comment by msau42** [comment]
My understanding is that this is inherent due to 'CreateSnapshot' being overloaded as a 'GetSnapshot' use case, so it won't be fixed until we add a GetSnapshot call in CSI

**Comment by xing-yang** [comment]
ListSnapshots with snapshot_id serves the same purpose as GetSnapshot so we don't really need a new GetSnapshot RPC. The reason that we decided not to use ListSnapshots is that it is optional.  CreateSnapshot is idempotent so it serves the same purpose as GetSnapshot.

CC @yuxiangqian

**Comment by daresheep** [comment]
Dears,

Is there any updates? 

i had testing on V4,  and this issue already exist.

i had a big PVC about  30G, and i create snapshot for this pvc.  it create a lot of snap files.

![image](https://user-images.githubusercontent.com/8828158/106549779-a54ae180-654c-11eb-83f8-d5594f3fad96.png)
![image](https://user-images.githubusercontent.com/8828158/106549853-ce6b7200-654c-11eb-98c3-91ea9d17d5b9.png)
![image](https://user-images.githubusercontent.com/8828158/106549874-e0e5ab80-654c-11eb-85d1-133548e6800e.png)

**Comment by xing-yang** [comment]
@daresheep Which CSI driver are you using?  CreateSnapshot must be idempotent. This means if CreateSnapshot is called multiple times for the same create snapshot request, the storage system should only create 1 snapshot, not multiple snapshots.  This looks like a problem with the CSI driver and the storage system.

**Comment by daresheep** [comment]
thank you so much for your replay.

The csi driver is https://github.com/kubernetes-csi/csi-driver-host-path and the  version is  V1.5.0 relase  4 days ago.

I'll try lower version for this later.

Thanks  again.

**Comment by xing-yang** [comment]
@daresheep can you open an issue for the csi hostpath driver here?  https://github.com/kubernetes-csi/csi-driver-host-path/issues

**Comment by daresheep** [comment]
Ok,  The issue created here:

https://github.com/kubernetes-csi/csi-driver-host-path/issues/243
