### ISSUE TITLE
1-20-on-kubernetes-1-20 is failing for release-2.1 branch

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes-csi/external-snapshotter#472]
Currently `1-20-on-kubernetes-1-20` job is failing for the `release-2.1` branch.

Here are several PRs in which this was discussed and tried to be addressed without success:
- https://github.com/kubernetes-csi/external-snapshotter/pull/471
- https://github.com/kubernetes/test-infra/pull/20792

/kind bug
/priority important-soon

**Comment by pohly** [comment]
It probably also fails for release-3.0 and release-4.0. Which of these are still supported?

**Comment by xing-yang** [comment]
Both release-3.0 and release-4.0 are supported.  release-4.0 should not have the problem as it supports v1 CRDs.  release-3.0 might have a problem.

**Comment by pohly** [comment]
Fix for release-3.0 is here: https://github.com/kubernetes-csi/external-snapshotter/pull/474

**Comment by ialidzhikov** [comment]
@pohly , I see that all related PRs are merged. Can this be closed now?

**Comment by pohly** [comment]
I think so.

/close
