### ISSUE TITLE
Move validation webhook to distroless:static

### ISSUE THREAD

**Issue by msau42** [kubernetes-csi/external-snapshotter#482]
Right now it's using "distroless:base" which installs glibc and openssl packages, which have frequent vulnerabilities. Investigate if we can move to "distroless:static".

**Comment by xing-yang** [comment]
@yuxiangqian do you know if there's any specific reason why "distroless:base" is used instead of "distroless:static" for the validation webhook image?
https://github.com/kubernetes-csi/external-snapshotter/blob/master/cmd/snapshot-validation-webhook/Dockerfile#L1

**Comment by yuxiangqian** [comment]
I am not aware of/can recall any specific reason why "base" is used over "static"
from this [documentation](https://github.com/GoogleContainerTools/distroless/blob/master/base/README.md), it seems to be fine to switch to use static as the webhook is implemented in Go. We should definitely test the behavior though.

**Comment by xing-yang** [comment]
Fixed by #550
