### ISSUE TITLE
Support for in-tree volumes migrated with CSIMigration feature-gate

### ISSUE THREAD

**Issue by mitchellhuang** [kubernetes-csi/external-snapshotter#489]
It appears that snapshot-controller does not support snapshotting volumes that have been migrated to CSI with the CSIMigration/CSIMigrationAWS feature-gate. When attempting to snapshot a migrated volume it will error:

```
cannot find CSI PersistentVolumeSource for volume pvc-b9e3ba60-6dd1-4f73-94e4-04db040598a7
```

You can see [here](https://github.com/kubernetes-csi/external-snapshotter/blob/533ed88/pkg/common-controller/snapshot_controller.go#L650) where the error occurs because the migrated PV spec does not contain `Spec.CSI.VolumeHandle`. It is instead located at `Spec.AwsElasticBlockStore.VolumeID`.

Is supporting migrated in-tree volumes within scope of this project? It seems like we can support migrated volumes using CSI translation methods like `TranslateInTreePVToCSI` found in the the main kubernetes [source code](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/csi-translation-lib/plugins/aws_ebs.go#L124).

Migrated In-tree PV Spec:

```
  spec:
    accessModes:
    - ReadWriteOnce
    awsElasticBlockStore:
      fsType: ext4
      volumeID: vol-010b07de49ba5b821
    capacity:
      storage: 10Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: nginx
      namespace: default
      resourceVersion: "11167"
      uid: 7ef0cf5c-425a-4a56-87de-39c84ac4df1a
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.ebs.csi.aws.com/zone
            operator: In
            values:
            - eu-west-1a
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard
    volumeMode: Filesystem
```

CSI PV Spec:

```
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 50Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: prometheus-storage-prometheus-prometheus-0
      namespace: kube-system
      resourceVersion: "3755"
      uid: b9e3ba60-6dd1-4f73-94e4-04db040598a7
    csi:
      driver: ebs.csi.aws.com
      fsType: ext4
      volumeAttributes:
        storage.kubernetes.io/csiProvisionerIdentity: 1617335526227-8081-ebs.csi.aws.com
      volumeHandle: vol-01ab50e8eec150f48
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.ebs.csi.aws.com/zone
            operator: In
            values:
            - eu-west-1c
    persistentVolumeReclaimPolicy: Delete
    storageClassName: standard-csi
    volumeMode: Filesystem
```

**Comment by xing-yang** [comment]
VolumeSnapshot is only supported for CSI drivers.  It is never supported for in-tree volume plugins.  So this feature is not covered by CSIMigration.

**Comment by mitchellhuang** [comment]
Hi @xing-yang, the in-tree volumes that are migrated by the CSIMigration feature-gate are ultimately run on CSI once enabled, so I believe this is within scope. I have submitted a PR to enable compatibility for snapshot-controller using the official csi-translation-lib. It maintains existing compatibility with native CSI volumes and is a relatively simple code change. Hopefully you and the maintainers will find this within scope of the project. Thanks!

**Comment by xing-yang** [comment]
CSI migration is intended to support features that are already supported by in-tree drivers.  It is not intended to add new CSI features.

**Comment by mitchellhuang** [comment]
Ahh, I see, understood, we will fork internally then.

**Comment by andyzhangx** [comment]
> Ahh, I see, understood, we will fork internally then.

@mitchellhuang have you maintained a forked external-snapshotter with snapshot support? I would like to have snapshot feature enabled with in-tree also, thanks.

**Comment by circy9** [comment]
@xing-yang Is there any plan from k8s to fully deprecate CSI migration? Or is the plan to allow CSI migrated PVs to exist for unlimited time?
