### ISSUE TITLE
Add VolumeSnapshot.Name & VolumeSnapshot.Namespace to Parameters fields in CreateSnapshotRequest

### ISSUE THREAD

**Issue by mowangdk** [kubernetes-csi/external-snapshotter#495]
Snapshot-controller pass the newly generated snapshot name（snapshot+uid） instead of the original VolumeSnapshot.Name to CSI. This makes it very difficult to trace PVC usages base on the backend snapshot resources.

Can we add VolumeSnapshot.Name & VolumeSnapshot.Namespace to Parameters fields in CreateSnapshotRequest for tag backend snapshot resource?

**Comment by xing-yang** [comment]
VolumeSnapshot Name/Namespace and VolumeSnapshotContent Name can all be passed into CreateSnapshotRequest.  See doc here:
https://kubernetes-csi.github.io/docs/external-snapshotter.html#volumesnapshot-and-volumesnapshotcontent-parameters

**Comment by mowangdk** [comment]
> VolumeSnapshot Name/Namespace and VolumeSnapshotContent Name can all be passed into CreateSnapshotRequest. See doc here:
> https://kubernetes-csi.github.io/docs/external-snapshotter.html#volumesnapshot-and-volumesnapshotcontent-parameters

thanks~
