### ISSUE TITLE
what's differences between v1beta1 and v1 (v3.0.3-> v4.0.0)

### ISSUE THREAD

**Issue by mowangdk** [kubernetes-csi/external-snapshotter#501]
I want to know what is the difference between version 3.0.3 and version 4.0.0  and What should I pay attention to when upgrading from version 3.0.3 to 4.0.0 （Sorry I didn't find the relevant document~

**Comment by xing-yang** [comment]
You can the release notes here:
https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v4.0.0
https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v3.0.3

**Comment by mowangdk** [comment]
ok, thx~
