### ISSUE TITLE
Startup code that gets a namespace fails if there are no RBAC rules

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes-csi/external-snapshotter#514]
This is a bug introduced in https://github.com/kubernetes-csi/external-snapshotter/pull/504 (thanks @zhucan for finding that out) where during startup we attempt to list volumesnapshots in the `kube-system` namespace, if there are no RBAC rules for this request then 

https://github.com/kubernetes-csi/external-snapshotter/blob/f235e24b75fafb26df8734be9a2a9f6c869ae771/cmd/snapshot-controller/main.go#L70-L78

Will always return a non nil error

Proposed solutions:
- remove the volumesnapshots request, it might be good enough to test both volumesnapshotcontents and volumesnapshotclasses
- add the RBAC rules required to do `kubeClient.CoreV1().Namespaces().Get(context.TODO(), "kube-system", metav1.GetOptions{})`
- @msau42 suggested scoping volumesnapshots to the empty namespace (which makes it list across all namespaces)

**Comment by msau42** [comment]
I think if you call `List` with an empty string namespace, that lists the objects in all namespaces.

**Comment by mauriciopoppe** [comment]
@msau42 in an experiment doing the request with an empty string namespace is equal to listing in the `default` namespace

```
root@vm-bootstrap--6ecffb9bde2ccf8-8c33e55b6b8ff853:~# kubectl get volumesnapshots.v1.snapshot.storage.k8s.io --v=6
I0507 17:48:06.456362 3306944 loader.go:375] Config loaded from file:  bmctl-workspace/ci-6ecffb9bde2ccf8/ci-6ecffb9bde2ccf8-kubeconfig
I0507 17:48:06.474599 3306944 round_trippers.go:444] GET https://10.200.0.5:443/apis/snapshot.storage.k8s.io/v1/namespaces/default/volumesnapshots?limit=500 200 OK in 9 milliseconds
No resources found in default namespace.

root@vm-bootstrap--6ecffb9bde2ccf8-8c33e55b6b8ff853:~# kubectl -n "" get volumesnapshots.v1.snapshot.storage.k8s.io --v=6
I0507 17:48:15.311437 3307020 loader.go:375] Config loaded from file:  bmctl-workspace/ci-6ecffb9bde2ccf8/ci-6ecffb9bde2ccf8-kubeconfig
I0507 17:48:15.330039 3307020 round_trippers.go:444] GET https://10.200.0.5:443/apis/snapshot.storage.k8s.io/v1/namespaces/default/volumesnapshots?limit=500 200 OK in 10 milliseconds
No resources found in default namespace.
```

**Comment by msau42** [comment]
I think kubectl may behave differently than client-go. If you try "" in client-go, are you able to see objects from other namespaces?
