### ISSUE TITLE
Prow: ensure that canary controller is tested

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/external-snapshotter#516]
It looks like the code in prow.sh which is meant to select the canary version of the driver fails to do so:
https://github.com/kubernetes-csi/csi-driver-host-path/blob/54431443245c9fd46048ba5f89324e2e8d7efefb/release-tools/prow.sh#L341-L348

It selects "master" as `CSI_SNAPSHOTTER_VERSION`, just like the canary Prow job does in:
https://github.com/kubernetes/test-infra/blob/9901b188a14600d62641c14c0d9003dae9fbdf9b/config/jobs/kubernetes-csi/csi-driver-host-path/csi-driver-host-path-config.yaml#L2527-L2528

But the YAML files from the master branch install the latest stable 4.x version of the controller.  What seems to be missing in prow.sh is patching the image when installing the YAML file:
https://github.com/kubernetes-csi/csi-driver-host-path/blob/54431443245c9fd46048ba5f89324e2e8d7efefb/release-tools/prow.sh#L818-L821

**Comment by Kartik494** [comment]
Hi @pohly  , i have a confusion on this [line](https://github.com/kubernetes-csi/csi-driver-host-path/blob/54431443245c9fd46048ba5f89324e2e8d7efefb/release-tools/prow.sh#L343) actually in that [file](https://github.com/kubernetes/test-infra/blob/9901b188a14600d62641c14c0d9003dae9fbdf9b/config/jobs/kubernetes-csi/csi-driver-host-path/csi-driver-host-path-config.yaml#L321) the kubernetes 1.21 and 1.20 Job  contain CSI snapshotter version v4.0.0 .  So if we uses CSI_PROW_KUBERNETES  = v1.20 then it also install the release 4.0 . As per [document](https://github.com/kubernetes/test-infra/blob/9901b188a14600d62641c14c0d9003dae9fbdf9b/config/jobs/kubernetes-csi/csi-driver-host-path/csi-driver-host-path-config.yaml#L2419) the CSI_PROW_HOSTPATH_CANARY is set to canary , so this condition will be true and gave the output as master even if we dont uses the latest release 

Thanks

**Comment by Kartik494** [comment]
Hi @pohly for patching the  canary for snapshot controller , i need to add a kustomization.yaml file in the  [repo](https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes/snapshot-controller) and then made changes in [prow.sh](https://github.com/kubernetes-csi/csi-driver-host-path/blob/54431443245c9fd46048ba5f89324e2e8d7efefb/release-tools/prow.sh#L818-L821) to use `kubectl apply -k` instead .Is this the right approach , Please suggest 
Thanks

**Comment by pohly** [comment]
You need to create a kustomization in prow.sh which replaces the image.

While at it, perhaps use the same approach in https://github.com/kubernetes-csi/csi-driver-host-path/blob/54431443245c9fd46048ba5f89324e2e8d7efefb/release-tools/prow.sh#L780-L817

In other words, always use `kubectl apply -k <my local kustomization>` and just change what's in that kustomization.yaml.

**Comment by pohly** [comment]
This code here uses `--kustomize` to add labels to YAML files. You probably can copy it and then just change what's in the kustomization.yaml to replace the image.

https://github.com/kubernetes-csi/csi-driver-host-path/blob/2a06cb4c6636c994002837ec75147deeed3430e5/deploy/util/deploy-hostpath.sh#L173-L207
