### ISSUE TITLE
There's no Event for a sucessfully created snapshot 

### ISSUE THREAD

**Issue by alibo** [kubernetes-csi/external-snapshotter#522]
`Snapshot-controller` creates a new normal event with type `Normal` and reason `CreatingSnapshot` after `VolumeSnapshotContent` is created:

https://github.com/kubernetes-csi/external-snapshotter/blob/f255fe7b46bd5410370537319879d06f2bf1a156/pkg/common-controller/snapshot_controller.go#L704-L705

However, when the snapshot is created successfully, the snapshot controller/sidecar only changes `ReadyToUse` field to `true`, but it doesn't create a new event to inform the user the snapshot is created. In other words, it still says the following message when describing the snapshot until the event is deleted:

```
Status:
  Bound Volume Snapshot Content Name:  snapcontent-7e011c44-462e-4fc4-bb2e-47b28e881619
  Creation Time:                       2021-05-23T10:34:08Z
  Ready To Use:                        true
  Restore Size:                        2Gi
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  10m   snapshot-controller  Waiting for a snapshot test-ns/test-volume-1621766047 to be created by the CSI driver.
```

Related PR: https://github.com/kubernetes-csi/external-snapshotter/pull/289

**Comment by xing-yang** [comment]
Good point.  I think we should add an event when the snapshot is created successfully.

**Comment by xing-yang** [comment]
> Failure events are also not displayed. Snapshot controller doesn't create a new event to inform the user the failure event while we can see the failure events in snapshotter pod logs.

We do add events when failure occurs.  If you think an event is missing for a particular failure, please report a separate issue so we can fix it.

**Comment by xing-yang** [comment]
By the way, events will disappear after a period of time while logs will persist.  So it also depends on when you checked the events.

**Comment by akashpatel2** [comment]
Our K8s cluster monitoring framework heavily use Events; in this case we are getting only Snapshot Create event, and after successful snapshot create, we are not getting 'successful snapshot create event', I think we should fix this issue.
