### ISSUE TITLE
Question about VolumeSnapshot API

### ISSUE THREAD

**Issue by mrwwheat7** [kubernetes-csi/external-snapshotter#523]
Hi team,

I am using k8s 1.21 version, and when I am declaring
`apiVersion: snapshot.storage.k8s.io/v1 kind: VolumeSnapshotClass` in yaml file, it will throw the error: `no matches for kind "VolumeSnapshotClass" in version "snapshot.storage.k8s.io/v1"`. But after I apply the volumesnapshot [CRD](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd), it works.

According to the blog (https://kubernetes.io/blog/2020/12/10/kubernetes-1.20-volume-snapshot-moves-to-ga/), looks like Kubernetes Volume Snapshot has been moved to GA, why do we still need to apply the volumesnapshot CRD file? Isn't this feature enabled by default?

Thanks!

**Comment by xing-yang** [comment]
@mrwwheat7 VolumeSnapshot is a CRD so not every K8S distro deploys the CRDs by default.  In the blog, we talked about a feature gate.  That feature gate is controlling a DataSource field in the PVC spec.
