### ISSUE TITLE
external-snapshotter constantly retrying CreateSnapshot calls on error w/o backoff

### ISSUE THREAD

**Issue by ggriffiths** [kubernetes-csi/external-snapshotter#533]
Creating a snapshot from a non-existing volume will repro this. @jsafrane discovered this, opening this issue for tracking.

**Comment by travisghansen** [comment]
Ran into this as well. If further info can be helpful let me know.

**Comment by ggriffiths** [comment]
@travisghansen did you repro this by creating a snapshot from a non-existing volume? Want to make sure it's the same cause.

**Comment by travisghansen** [comment]
In my case the api call to the backing storage system had some invalid options in the payload resulting in a failure. I would effectively pass the failed api response back up to the grpc client (this repo?) and observe that over and over at a rapid pace.

**Comment by shrac** [comment]
Hi, ran into this issue while there was a permissions issue and create snapshot call has failed. Attached logs (enabled verbose logging in snapshotter) if they might help. 

[snapshotter_logs.txt](https://github.com/kubernetes-csi/external-snapshotter/files/7526825/snapshotter_logs.txt)

I see an `enqueued "snapcontent-c5a12581-b9c7-430e-9c61-9bcb576a60d4" for sync ` everytime as part of `setAnnVolumeSnapshotBeingCreated` method - Not sure if this is expected.

As there is a create snapshot call almost every 150ms, the underlying API is getting throttled. Also there are too many mutations to the snapshot object. As the API throttling is generally at a customer tenant level this might impact other customer scenarios as well. Any update on the issue/fix ?

**Comment by anshulahuja98** [comment]
> Hi, ran into this issue while there was a permissions issue and create snapshot call has failed. Attached logs (enabled verbose logging in snapshotter) if they might help.
> 
> [snapshotter_logs.txt](https://github.com/kubernetes-csi/external-snapshotter/files/7526825/snapshotter_logs.txt)
> 
> I see an `enqueued "snapcontent-c5a12581-b9c7-430e-9c61-9bcb576a60d4" for sync ` everytime as part of `setAnnVolumeSnapshotBeingCreated` method - Not sure if this is expected.
> 
> As there is a create snapshot call almost every 150ms, the underlying API is getting throttled. Also there are too many mutations to the snapshot object. As the API throttling is generally at a customer tenant level this might impact other customer scenarios as well. Any update on the issue/fix ?

+1
The controller seems to be in a bad state, and can bring the cluster health by throttling the vendor APIs


> I need to see why this is happening and will send a PR to address it afterwards.
@ggriffiths  any update on this fix?

**Comment by ggriffiths** [comment]
Yes, that is the same issue @shrac. I'm looking into the root cause of this issue, no update yet.

**Comment by xing-yang** [comment]
Does this still happen with the latest code in the master branch?

**Comment by xing-yang** [comment]
@anshulahuja98 The following error should not occur any more with the code in the master branch.

```
I1111 12:01:13.229378       1 snapshot_controller.go:167] updating VolumeSnapshotContent[snapcontent-c5a12581-b9c7-430e-9c61-9bcb576a60d4] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-c5a12581-b9c7-430e-9c61-9bcb576a60d4": the object has been modified; please apply your changes to the latest version and try again
```

@ggriffiths This should be fixed with the "patch" fix?

**Comment by anshulahuja98** [comment]
Can you point me to the PR that fixed it? I am not very clear as to what fixed it.
And when can we expect the new release with the required fix.
Current version is 4.2.1 from August

**Comment by anshulahuja98** [comment]
cc @andyzhangx  @shrac

**Comment by xing-yang** [comment]
@anshulahuja98 This following PR changes "update" to "patch". That reduces the error "the object has been modified".
https://github.com/kubernetes-csi/external-snapshotter/pull/526

**Comment by ggriffiths** [comment]
There are two issues being discussed here:
1. Object has been modified issue:
```
I1111 12:01:13.229378       1 snapshot_controller.go:167] updating VolumeSnapshotContent[snapcontent-c5a12581-b9c7-430e-9c61-9bcb576a60d4] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-c5a12581-b9c7-430e-9c61-9bcb576a60d4": the object has been modified; please apply your changes to the latest version and try again
```
This has been fixed for all common cases in snapshotter master, which will be in v5.0.0. The version v4.2.1 will not have this fix. 

2. #533 - this issue is unrelated to the above error. I've reproduced it in master without the `object has been modified error`. The object are constantly being re-queued without backoff, even though backoff is configured. I'm still looking into why that is the case.

I've been busy the past few weeks, but I'm hoping to continue looking into this one again soon.

**Comment by zhucan** [comment]
@ggriffiths How to set the backoff to the snapshot-controller?

**Comment by ggriffiths** [comment]
Retry flags are defined here:
https://github.com/kubernetes-csi/external-snapshotter/blob/master/cmd/csi-snapshotter/main.go#L85-L86

**Comment by zhucan** [comment]
@xing-yang @ggriffiths Maybe ecause of the https://github.com/kubernetes-csi/external-snapshotter/blob/c3585a99384ce2fba588e9b05c9b227ad7259796/pkg/sidecar-controller/snapshot_controller.go#L328 to update the snapshotcontent. 

After the snapshot was created failed, it will to remove the "snapshot.storage.kubernetes.io/volumesnapshot-being-created"  and update the snapshotcontent.

**Comment by zhucan** [comment]
![image](https://user-images.githubusercontent.com/13997135/150497761-27daf39f-802e-4013-93b7-e0242d1c4457.png)
If we don't remove the annotion "snapshot.storage.kubernetes.io/volumesnapshot-being-created" and not update the snapshotcontent, the retry interal is 1s. 2s, 4s, 8s,16s,32s,64s,128s,256s, 5min.

**Comment by xing-yang** [comment]
I see.  So it is not really a normal requeue due to the failure but it is a new update that triggers the requeue.  If we don't remove the annotation "snapshot.storage.kubernetes.io/volumesnapshot-being-created" and don't update the snapshotcontent, how does the snapshotter know the creation has failed?  If the annotation is not removed, the snapshotter will think the storage system is still working on the snapshot creation. CreateSnapshot will be called to query the snapshot status.  One thing to explore is to see if we can use ListSnapshots instead of CreateSnapshot (if ListSnapshots is supported by CSI driver) to check snapshot status.

**Comment by xing-yang** [comment]
Another idea to explore is to compare the old obj vs the new obj when update is triggered. If the annotation "snapshot.storage.kubernetes.io/volumesnapshot-being-created" is the only thing being removed, maybe we don't need to go through CreateSnapshot again.

**Comment by zhucan** [comment]
> Another idea to explore is to compare the old obj vs the new obj when update is triggered. If the annotation "snapshot.storage.kubernetes.io/volumesnapshot-being-created" is the only thing being removed, maybe we don't need to go through CreateSnapshot again.

I agree it

**Comment by zhucan** [comment]
> Another idea to explore is to compare the old obj vs the new obj when update is triggered. If the annotation "snapshot.storage.kubernetes.io/volumesnapshot-being-created" is the only thing being removed, maybe we don't need to go through CreateSnapshot again.

If we can  only compare the annotations of the snapshotcontent, if they are different, we don't re-queue.

**Comment by xing-yang** [comment]
>> Another idea to explore is to compare the old obj vs the new obj when update is triggered. If the annotation "snapshot.storage.kubernetes.io/volumesnapshot-being-created" is the only thing being removed, maybe we don't need to go through CreateSnapshot again.

> whether we can only compare the annotations of the snapshotcontent, if they are different, we don't re-queue. @xing-yang

I think we need to check if the annotation "snapshot.storage.kubernetes.io/volumesnapshot-being-created" is the only thing being removed and if that's the only change. If there are other changes, we still need to process it.
