### ISSUE TITLE
Fix external-snapshotter sidecar container RBAC rule

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#55]
We don't need "create", "delete", "update" for PV and PVC resources in the external-snapshotter RBAC rule.  We only need "get", "list", "watch".  We should clean up the following rbac.yaml file.

https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/rbac.yaml

**Comment by wackxu** [comment]
Will  fix this

**Comment by pohly** [comment]
Once this is fixed, please ensure that it propagates also to those places which use the modified file:
- https://github.com/kubernetes/kubernetes/pull/69036
- https://github.com/kubernetes-csi/docs/blob/master/book/src/Example.md#create-rbac-rules-for-csi-snapshotter

**Comment by pohly** [comment]
If you want, file a bug against kubernetes-csi/docs and assign it to me.
