### ISSUE TITLE
Helm chart for CRDs and snapshot controller?

### ISSUE THREAD

**Issue by gman0** [kubernetes-csi/external-snapshotter#551]
Are there any plans to offer snapshot CRDs, controller, etc. as a single Helm chart? If not, would you accept contributions in this area?

I realize that all these currently external components (CRDs, controller) will probably be incorporated in Kubernetes some time in the future, so maybe it doesn't make sense having to maintain a Helm chart for these.

**Comment by xing-yang** [comment]
@gman0 Thanks for your willingness to contribute!  We are discussing about this.

**Comment by WanzenBug** [comment]
Hey @gman0

FYI: I recently worked on exactly this: https://github.com/piraeusdatastore/helm-charts/

My main motivation was helping users of Piraeus to enable snapshotting on their cluster, but I'd be happy if there was a "official" solution.

**Comment by gman0** [comment]
@WanzenBug thank you! That is exactly my motivation as well, but I just started working on this. From the first glance, your solution looks great, it even seems to offer deployment for the webhook. Would you like to take over this ticket? Of course that is if sig-storage folks think this indeed makes sense.

**Comment by Xyaren** [comment]
I would also really appreciate there being a helm chart, as it makes updating so much easier.

**Comment by kfox1111** [comment]
Using helm to manage it would be preferable for us. It would make it easy to customize for our environment and keep it up to date.

**Comment by xing-yang** [comment]
We have yaml files that are used by CI. If we have helm charts, can the charts be used to generate yaml files so that they don't go out of sync?

**Comment by kfox1111** [comment]
yeah. You can run something like: 'helm template external-snapshotter > static.yaml' to generate them.

**Comment by dashjay** [comment]
I use helm chart 2.1.2 then I found that: old version of deployment can create crds(Related to volumesnapshot ) by them themselves.
Recently, our storage has been depleted, so we want to set up a new ceph cluster.

I found following questions:
 - new `csi-snapshotter` will not apply a crd into cluster,
 - and not any crds in helm chart.
 - I found that new crds remove the support for v1alpha1.

Because crds of snapshotter not change so much, and there are not many new features, I think we can provide a conversion webhook help users smoothly deprecate versions.

**Comment by nariman-maad** [comment]
Yes, helm is more convenient for automation.

**Comment by trallnag** [comment]
I agree that a Helm chart would be more convenient. Although I also see that maintaining a proper chart requires more resources. The charts provided by @WanzenBug work great btw.

```hcl
resource "helm_release" "webhook" {
  name       = "snapshot-validation-webhook"
  chart      = "snapshot-validation-webhook"
  repository = "https://piraeus.io/helm-charts/"
  version    = var.webhook_chart_version

  namespace        = local.namespace
  atomic           = true
  cleanup_on_fail  = true
  force_update     = true
  max_history      = 5

  values = [yamlencode({
    image = {
      tag = "v${var.app_version}"
    }

    tls = {
      autogenerate = true
      renew = false
    }

    nodeSelector = var.node_selector
  })]

  depends_on = [
    kubectl_manifest.crds,
  ]
}

resource "helm_release" "controller" {
  name       = "snapshot-controller"
  chart      = "snapshot-controller"
  repository = "https://piraeus.io/helm-charts/"
  version    = var.controller_chart_version

  namespace        = local.namespace
  atomic           = true
  cleanup_on_fail  = true
  force_update     = true
  max_history      = 5

  values = [yamlencode({
    image = {
      tag = "v${var.app_version}"
    }

    nodeSelector = var.node_selector
  })]

  depends_on = [
    kubectl_manifest.crds,
    helm_release.webhook,
  ]
}
```
