### ISSUE TITLE
VolumeSnapshotContent update failed

### ISSUE THREAD

**Issue by mowangdk** [kubernetes-csi/external-snapshotter#557]
Clusters often report the following event when dynamically creating VolumeSnapshot. Has anyone encountered it before? 
It eventually end up in ready state. but the warning event is annoying.

snapshot-controller ver: v3.0.2
ps: VolumeSnapshotContent is not modified outside of the snapshot sidecars

```
17m         Warning   SnapshotCreationFailed        volumesnapshotcontent                                          Failed to create snapshot: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-fb38ffb1-d756-4482-b60e-f28783bb3002: "snapshot controller failed to update snapcontent-fb38ffb1-d756-4482-b60e-f28783bb3002 on API server: Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-fb38ffb1-d756-4482-b60e-f28783bb3002\": the object has been modified; please apply your changes to the latest version and try again"
```

**Comment by xing-yang** [comment]
There's another issue opened for this: https://github.com/kubernetes-csi/external-snapshotter/issues/525
cc @ggriffiths

**Comment by mowangdk** [comment]
> There's another issue opened for this: #525
> cc @ggriffiths

ok, thx~
