### ISSUE TITLE
snapshot request to controller service is not guarantee consistency

### ISSUE THREAD

**Issue by hoyho** [kubernetes-csi/external-snapshotter#566]
In current design, when a user request to create a snapshot in kubernetes cluster, the volume data is not guarantee consistency.
consider following step:
1.  Create PVC and Pod and assume volume mounted and being use (more specifically , we can assume the volume format as xfs)
2.  Do some IO operation inside the pod with the volume：
 
![企业微信截图_16278959047804](https://user-images.githubusercontent.com/8370967/127859001-21dd18fe-21d4-448e-9209-323d780eeaf4.png)

3.  create a snapshot
4.  external-snapshotter sidecar is listening the CR and  then call CSI driver to create a snapshots via storage backend.
5.  However, If the CSI driver or storage backend create snapshots right now, there's some data cache need to sync to backend, or they may be still in pagecache and causes data lost. (That means snapshots required the user to call `echo 3 > /proc/sys/vm/drop_caches` or `fsync` or something before the snapshots, which may not sound as a real "snapshots").

snap result without sync IO：
![企业微信截图_16278959933848](https://user-images.githubusercontent.com/8370967/127859094-a665ed79-0f4d-4775-96d7-e9b96d75a186.png)

6. gRPC call to controllerServer is unlike call to nodeServer. It is not possible to sync IO IMO. 

If there's any solution to promise that?

**Comment by xing-yang** [comment]
The underlying Storage System will need to ensure it is crash consistent.

**Comment by hoyho** [comment]
That's not easy to make sure that from storage side.
At least I see someone have face the problem too https://github.com/ceph/ceph-csi/issues/1532
Do you think is it possible to introduce a new interface to NodeServer in CSI spec?

**Comment by xing-yang** [comment]
There was a proposal about this a while back in the CSI spec:
https://github.com/container-storage-interface/spec/pull/407
We still have not reached consensus on going forward with it yet. 

We are working on adding a pod inline definition to do the quiesce.  See here: https://github.com/kubernetes/enhancements/pull/1995
