### ISSUE TITLE
Unable to map original PVC from the snapshot object after PVC rerreation

### ISSUE THREAD

**Issue by humblec** [kubernetes-csi/external-snapshotter#567]
Snapshot objects are created from a PVC and snapshot object record the source PVC name in the snapshot object spec. However if there is a situation of PVC recreation,  ie PVC get recreated with the same name after snapshot has been created/taken, there is no way to identify the `original` PVC reference from the snapshot object or we miss the backtracking facility here. The PVC name reference brings us to the new PVC ( recreated with the same name of source PVC) which gives kind of wrong information about the source of the snapshot. Can we record the original PVC unique identifier (`UID` in this case) in the snapshot object , so that we are free from errors like reading wrong PVC in situations like this ? 

Cc @xing-yang

**Comment by xing-yang** [comment]
Hi @humblec, do you need this information to info user that PVC still has VolumeSnapshots and therefore the volume may not be able to be deleted if the snapshot is dependent on the volume on the StorageSystem?  In Kubernetes, since we treat PVC and VolumeSnapshot as independent of each other, you should not need to find the original PVC after the VolumeSnapshot is created. This is similar to Cloning in that way.

**Comment by xing-yang** [comment]
CC @yuxiangqian

**Comment by humblec** [comment]
> Hi @humblec, do you need this information to info user that PVC still has VolumeSnapshots and therefore the volume may not be able to be deleted if the snapshot is dependent on the volume on the StorageSystem?

> Not really, this information is not used to *block* any operations like source PVC deletion as such, however its more or less used for a listing of snapshots of a PVC , listing of PVCs from snapshots...etc. 
 
>In Kubernetes, since we treat PVC and VolumeSnapshot as independent of each other, you should not need to find the original PVC after the VolumeSnapshot is created. This is similar to Cloning in that way.
>

True, however considering snapshot object is having a reference to the `source PVC` by its `name`, which is not the unique identity of the PVC object, I was thinking we could have a reference by UID, so that at any point in time, a storage admin can refer the PVC from which snapshot is taken or snapshot is based on. 

While considering cloning, eventhough the semantics remain same, the use case  point of view, it is bit different, that said, once the clone is attempted and new pvc is created, ideally we dont have to map to the source PVC anymore. But in case of snapshot, these objects are kind of 'unusable' ( from app/user pov) till we restore to a new volume. At that time, the reference helps to track where it is based.

**Comment by xing-yang** [comment]
Maybe we can consider adding the PVC UUID in the VolumeSnapshot Status field.
@yuxiangqian What do you think?

**Comment by humblec** [comment]
> Maybe we can consider adding the PVC UUID in the VolumeSnapshot Status field.
> @yuxiangqian What do you think?

@xing-yang Indeed, thats what I was proposing to, so that the spec field remains unchanged and avoid big API change, but if someone want to map , we have the UID recorded in the status which should serve the requirement!

**Comment by humblec** [comment]
@xing-yang @yuxiangqian if we are fine to add a new field in `status` something like `DataSourceUID` or similar , I can work on the same . Please share your thoughts.

**Comment by xing-yang** [comment]
@humblec This is an API change.  Need to go thru lots of discussions first.

**Comment by humblec** [comment]
> @humblec This is an API change. Need to go thru lots of discussions first. I added to today's DP WG agenda.

Sure. nw, lets get consensus first . Thanks @xing-yang

**Comment by yuxiangqian** [comment]
Per discussion in the data protection working group:
1. There is way to make the connection, not ideal however but for example snapshot content resource has reference to underlying volume id, which can also potentially be used to match against underlying PV's volume ID.
2. The main use case here is that end users of VolumeSnapshot feature to be able to trace back the origin PVC.
a further discussion will followup on this issue.

**Comment by humblec** [comment]
Thanks @yuxiangqian for summarizing the discussion. 

> Per discussion in the data protection working group:
> 
>     1. There is way to make the connection, not ideal however but for example snapshot content resource has reference to underlying volume id, which can also potentially be used to match against underlying PV's volume ID.

True, there is a way to map the `volumeID` of the PV ( which indirectly could help to map the pvc) , however it is bit tedious.

Steps required to get the mapping of PVC and snapshot looks something like below;

1. We need to get the volumesnapshot resource to get the volumeSnapshotcontent name.
2. Then we need to get volumesnapshotContent resource to get the volume handle name(spec->source->VolumeHandle).
3. Once we have that , then we need to get the PVC name from the volumesnapshot and pull the PVC resource to get the PV name.
4. From the PV resource then we get the volume handle name(spec->csi->volumeHandle).

and at last, we need to do the equality check to figure out if the mapping is correct.

This is not a really scalable approach if we have 1000's of snapshots created then we need to poll 4x API just to get this mapping from snapshot to PVC.

> 
>     2. The main use case here is that end users of VolumeSnapshot feature to be able to trace back the origin PVC.
>        a further discussion will followup on this issue.

Yes, when there are many snapshots and PVCs around, the UI/Console referred here helps a user/admin to filter and list which snapshots belong to which PVCs and vice versa

**Comment by humblec** [comment]
Considering we have to continue this discussion and probability of solving it, I am reopening this.

**Comment by humblec** [comment]
@xing-yang @yuxiangqian we discussed this in different meetings/forums, I see its difficult to justify the use case behind the need for an expanded spec , especially being an API change which has to be discussed in length. But at the same time, as discussed, this is an issue with some kind of UI/rendering interfaces while there are many snapshot instances / PVC instances and if the mentioned scenario occurs. It would be appreciated if you can share your opinion on , is it worth to reconsider this requirement , so that I can take it forward.
