### ISSUE TITLE
Add CSI secret templates as annotation in volumeSnapshotContent

### ISSUE THREAD

**Issue by mkimuram** [kubernetes-csi/external-snapshotter#577]
There was a discussion in the meeting on PVC/Snapshot transfer about the model that __operation on volumeSnapshotContent should not rely on information in SnapshotClass after volumeSnapshotContent is created__. The reason for it is that SnapshotClass can be changed/deleted after the volumeSnapshotContent is created, as a result, the controllers might not rely on the current information in SnapshotClass.

In the case of  volumeSnapshotContent transfer, SecretRef in volumeSnapshotContent may be modified based on the templates after transferred. Therefore, these templates should be kept in volumeSnapshotContent as annotations.

Similar issue for PVC has already been opened [here](https://github.com/kubernetes-csi/external-provisioner/issues/654).

**Comment by xing-yang** [comment]
We are not depending on SnapshotClass after VolumeSnapshotContent is created.  Deletion secret is added to content as annotation and that will be used at deletion time.
