### ISSUE TITLE
missing required field "signerName

### ISSUE THREAD

**Issue by lajiao117** [kubernetes-csi/external-snapshotter#587]
use the deploy sh :https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/webhook-example/create-cert.sh

As im using the newest kubernetes Version 1.22.0 i have to use the apiVersion certificates.k8s.io/v1 instead of certificates.k8s.io/v1beta1. After deployment of webhook-create-signed-cert.sh i got this failure:

Warning: certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest

the new sh:

cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
EOF

which signerName should i choose? is this ok?

**Comment by xing-yang** [comment]
If you use `apiVersion: certificates.k8s.io/v1` in the script, does it work?

**Comment by xing-yang** [comment]
We should update "https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/webhook-example/create-cert.sh" to use "apiVersion: certificates.k8s.io/v1" instead.

**Comment by Kartik494** [comment]
@lajiao117 Thanks for Suggestions i have created a PR for the same

**Comment by lajiao117** [comment]
> /assign



I use csr v1 and use this signerName: kubernetes.io/kube-apiserver-client ，the webhook logs this err:
2021/09/09 06:30:21 http: TLS handshake error from 10.244.0.0:30789: remote error: tls: bad certificate

i use csr v1beta1, it works well

**Comment by lajiao117** [comment]
@Kartik494

**Comment by Kartik494** [comment]
I have checked on my environment here i got the error as  `error: unable to recognize "STDIN": no matches for kind "CertificateSigningRequest" in version "certificates.k8s.io/v1beta1"
`  even after adding `signerName` field . For this to work in my environment i need to use `v1` and use field `signerName` to get the expected output

**Comment by Kartik494** [comment]
@xing-yang Could you please take a look here and validate this.
Thanks

**Comment by xing-yang** [comment]
@lajiao117 can you verify if this PR has fixed the problem for you?  https://github.com/kubernetes-csi/external-snapshotter/pull/588

**Comment by lajiao117** [comment]
> @lajiao117 can you verify if this PR has fixed the problem for you? #588

@xing-yang the PR didn't fix the problem,i use the PR script ,the webhook logs this err:
2021/09/09 06:30:21 http: TLS handshake error from 10.244.0.0:30789: remote error: tls: bad certificate, so i switched to the old v1beta1 version

**Comment by xing-yang** [comment]
@lajiao117 I thought v1beta1 is no longer supported in k8s v1.22.  I don't know how it can work for you?  Can you share the script you used?

**Comment by lajiao117** [comment]
@xing-yang i just use https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/webhook-example/create-cert.sh, 
cat <<EOF | kubectl create -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: ${csrName}
spec:
  groups:
  - system:authenticated
  request: $(cat ${tmpdir}/server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

my k8s version is v1.21.2,the v1bate version can be used in v1.21

**Comment by lajiao117** [comment]
@xing-yang i tried other CertificateSigningRequest also(https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/), but can't  fix the problem

**Comment by xing-yang** [comment]
So if the existing script work for you in 1.21.2, then you can continue to use it.  What is the problem we need to fix?

**Comment by lajiao117** [comment]
> So if the existing script work for you in 1.21.2, then you can continue to use it. What is the problem we need to fix?

i need to use it in 1.22+,my users may use the k8s v1.22+

**Comment by xing-yang** [comment]
Do you have an environment in 1.22?

**Comment by lajiao117** [comment]
> Do you have an environment in 1.22?

yes, but the exists script can't be use in v1.22+

**Comment by xing-yang** [comment]
Have you tested PR #588 in v1.22?

**Comment by lajiao117** [comment]
i tested in v.21, i will try it in the v1.22 tomorrow

**Comment by lajiao117** [comment]
> Have you tested PR #588 in v1.22?

 certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest

the v1 version is supported in  k8s v1.21 2 @xing-yang

**Comment by xing-yang** [comment]
@Kartik494 Can you investigate why your PR does not work in K8S v1.21.2?

**Comment by Kartik494** [comment]
@xing-yang Sure i will investigate and let you know on this

**Comment by Kartik494** [comment]
Hi @lajiao117 @xing-yang  , I have Checked in my environment on both the versions 1.21.2 and 1.22. 
When i use version 1.21.2 with csr `v1beta1` with or without `signername` then it is running successful.But in case when i have to run csr as `v1` then i need to provide signername also.The signername you provide in issue description running fine in my environment too.
And from k8s enviorment 1.22+  we have to use csr `v1` with `signername`.

**Comment by Kartik494** [comment]
@lajiao117 from k8s 1.22+ we need to use csr as `v1` .If you want to run in on k8s < 1.22 then you can use csr as `v1beta1` or `v1`. But when you use csr as `v1` then then you make sure you must provide `signername` and when you are using csr as `v1beta1` then providing `signername`  seems optional to me. Can you try with this in your environment?
Thanks!

**Comment by lajiao117** [comment]
@Kartik494  i know the  k8s 1.22+ need to use crr v1 and tried, but i don know which signername  i should choose

**Comment by Kartik494** [comment]
@lajiao117 i don't have exact idea on this as of now.But the `signerName: kubernetes.io/kube-apiserver-client` you described in the issue description works fine for running the script and testing.You can use this to test.
Thanks

**Comment by lajiao117** [comment]
@Kartik494 i used  `signerName: kubernetes.io/kube-apiserver-client` the webhook logs this err:
2021/09/09 06:30:21 http: TLS handshake error from 10.244.0.0:30789: remote error: tls: bad certificate

**Comment by Kartik494** [comment]
@lajiao117 it's strange why this is not working in your environment and i think this error is not related to `signerName`. you could investigate on this. Else it's seems fine for me. @xing-yang Could you please check in your environment for clarification. Thanks

**Comment by xing-yang** [comment]
@lajiao117 Can you comment whether this PR #588 fixed your problem?

**Comment by lajiao117** [comment]
> @lajiao117 Can you comment whether this PR #588 fixed your problem?

@xing-yang yes, i used that,it works well

**Comment by Kartik494** [comment]
@lajiao117 I think it's better to keep it open for now.We could wait for PR to be merged

**Comment by lajiao117** [comment]
> @lajiao117 I think it's better to keep it open for now.We could wait for PR to be merged

ok, @Kartik494
