### ISSUE TITLE
Could we add VolumeSnapshot name & namespace in DeleteSnapshot & GetSnapshotStatus interface?

### ISSUE THREAD

**Issue by mowangdk** [kubernetes-csi/external-snapshotter#591]
we want to use these infos in ```ListSnapshots``` & ```DeleteSnapshot``` methods for check custom labels in VolumeSnapshots. Is it possible to pass this information like the ```CreateSnapshot``` interface?

**Comment by mowangdk** [comment]
> In CSI spec, CreateSnapshotResponse will include a snapshot_id returned by the CSI Driver. This snapshot_id is unique on the storage system and should be able to identify the snapshot on the storage system.

We are using the method you mentioned.  but why didn’t we add a params(map) to the interfaces?

**Comment by xing-yang** [comment]
Snapshot_id is enough to identify the snapshot on the storage system. Why do you need additional parameters?
