### ISSUE TITLE
snapshot from pvc is getting failed

### ISSUE THREAD

**Issue by noamgreen** [kubernetes-csi/external-snapshotter#592]
HI 
try to restore Vol from snapshot using external-snapshotter and getting this error 

" ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner W0928 10:43:31.003139       1 warnings.go:70] snapshot.storage.k8s.io/v1beta1 VolumeSnapshot is deprecated; use snapshot.storage.k8s.io/v1 VolumeSnapshot
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner W0928 10:43:31.003224       1 controller.go:958] Retrying syncing claim "79f8d20d-78de-4339-8df4-47c504fef3fe", failure 1
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner E0928 10:43:31.003242       1 controller.go:981] error syncing claim "79f8d20d-78de-4339-8df4-47c504fef3fe": failed to provision volume with StorageClass "ebs-sc": error getting handle for DataSource Type VolumeSnapshot by Name static-snapshot-demo: error getting snapshot static-snapshot-demo from api server: volumesnapshots.snapshot.storage.k8s.io "static-snapshot-demo" not found
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner I0928 10:43:31.003262       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"perf-pr-9420-2-mongo-scanner", Name:"ebs-snapshot-restored-claim", UID:"79f8d20d-78de-4339-8df4-47c504fef3fe", APIVersion:"v1", ResourceVersion:"90048334", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ebs-sc": error getting handle for DataSource Type VolumeSnapshot by Name static-snapshot-demo: error getting snapshot static-snapshot-demo from api server: volumesnapshots.snapshot.storage.k8s.io "static-snapshot-demo" not found
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner I0928 10:43:33.003384       1 controller.go:1332] provision "perf-pr-9420-2-mongo-scanner/ebs-snapshot-restored-claim" class "ebs-sc": started
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner I0928 10:43:33.003533       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"perf-pr-9420-2-mongo-scanner", Name:"ebs-snapshot-restored-claim", UID:"79f8d20d-78de-4339-8df4-47c504fef3fe", APIVersion:"v1", ResourceVersion:"90048334", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "perf-pr-9420-2-mongo-scanner/ebs-snapshot-restored-claim"
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner W0928 10:43:33.010239       1 warnings.go:70] snapshot.storage.k8s.io/v1beta1 VolumeSnapshot is deprecated; use snapshot.storage.k8s.io/v1 VolumeSnapshot
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner W0928 10:43:33.010328       1 controller.go:958] Retrying syncing claim "79f8d20d-78de-4339-8df4-47c504fef3fe", failure 2
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner E0928 10:43:33.010348       1 controller.go:981] error syncing claim "79f8d20d-78de-4339-8df4-47c504fef3fe": failed to provision volume with StorageClass "ebs-sc": error getting handle for DataSource Type VolumeSnapshot by Name static-snapshot-demo: error getting snapshot static-snapshot-demo from api server: volumesnapshots.snapshot.storage.k8s.io "static-snapshot-demo" not found
ebs-csi-controller-574c8fb7bf-4mfjb csi-provisioner I0928 10:43:33.010372       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"perf-pr-9420-2-mongo-scanner", Name:"ebs-snapshot-restored-claim", UID:"79f8d20d-78de-4339-8df4-47c504fef3fe", APIVersion:"v1", ResourceVersion:"90048334", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "ebs-sc": error getting handle for DataSource Type VolumeSnapshot by Name static-snapshot-demo: error getting snapshot static-snapshot-demo from api server: volumesnapshots.snapshot.storage.k8s.io "static-snapshot-demo" not found

"

i am using EKS 1.21 
external-snapshotter release-4.2
aws-ebs-csi-driver v1.3.0 

my use case is to restore snapshot to vol and mount it to mongo as DB 

any help will be nice :-) 

[perf-pr-9420-2-PVC-mongodb-app-scanner.txt](https://github.com/kubernetes-csi/external-snapshotter/files/7243286/perf-pr-9420-2-PVC-mongodb-app-scanner.txt)
[perf-pr-9420-2-VS-scanner.txt](https://github.com/kubernetes-csi/external-snapshotter/files/7243287/perf-pr-9420-2-VS-scanner.txt)
[perf-pr-9420-2-VSC-scanner.txt](https://github.com/kubernetes-csi/external-snapshotter/files/7243288/perf-pr-9420-2-VSC-scanner.txt)
[VolumeSnapshotClass.txt](https://github.com/kubernetes-csi/external-snapshotter/files/7243289/VolumeSnapshotClass.txt)

**Comment by xing-yang** [comment]
What is the version of external-provisioner?

**Comment by pabrahamusa** [comment]
I am facing the same issue from EKS 1.20 snapshotter v4.2.1 . I am trying to create a PVC from snapshot

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 500Gi
  dataSource:
    name: pvc-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
```

Error: 

1 snapshot_controller.go:223] Failed to get snapshot class ebs-csi-aws for snapshot content pvc-snapshot: volumesnapshotclass.snapshot.storage.k8s.io "ebs-csi-aws" not found
ebs-csi-controller-74b4f95f5c-b8wsc csi-snapshotter E1111 15:19:59.969451       1 snapshot_controller.go:122] checkandUpdateContentStatus [pvc-snapshot]: error occurred failed to get snapshot class ebs-csi-aws for snapshot content pvc-snapshot: volumesnapshotclass.snapshot.storage.k8s.io "ebs-csi-aws" not found

Following command is not returning anything. 
kubectl get volumesnapshotclasses.snapshot.storage.k8s.io

I installed snapshotter with following command
k apply -f external-snapshotter/client/config/crd/ 

I am wondering whether this is because I missed some CRDS?

Regards,
Matt

**Comment by pabrahamusa** [comment]
I see that I was missing the following but adding it still not resolving the issue

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: ebs-csi-aws
driver: ebs.csi.aws.com
deletionPolicy: Retain

```

```
kubectl get VolumeSnapshotContent
NAME                                READYTOUSE   RESTORESIZE    DELETIONPOLICY   DRIVER            VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                      VOLUMESNAPSHOTNAMESPACE   AGE
pvc-snapshot   true         536870912000   Retain           ebs.csi.aws.com   ebs-csi-aws           pvc-snapshot   solr                      17m
```


```
kubectl get VolumeSnapshot 
NAME                                READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT               RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT   CREATIONTIME   AGE
pvc-snapshot                            data-explore-solrcloud-0-snapshot                 ebs-csi-aws                                      18m
```

**Comment by pabrahamusa** [comment]
I found that my csi-snapshotter was using old image so I updated it to v4.2.1 and now VolumeSnapshotContent seems to be populated correctl but not VolumeSnapshot

```
kubectl get VolumeSnapshotContent
NAME                                READYTOUSE   RESTORESIZE    DELETIONPOLICY   DRIVER            VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                      VOLUMESNAPSHOTNAMESPACE   AGE
pvc-snapshot   true         536870912000   Retain           ebs.csi.aws.com   ebs-csi-aws           pvc-snapshot   solr
```

```
kubectl get VolumeSnapshot -n solr
NAME                                READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT               RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT   CREATIONTIME   AGE
pvc-snapshot                            pvc-snapshot                 ebs-csi-aws                                      14s
```

**Comment by pabrahamusa** [comment]
Finally found the issue was around awb-ebs-csi-driver external-snapshotter , I have to install the controller separately and everything started working fine
