### ISSUE TITLE
If "update" no longer use, should we cleanup it?

### ISSUE THREAD

**Issue by zhucan** [kubernetes-csi/external-snapshotter#602]
https://github.com/kubernetes-csi/external-snapshotter/blob/caef201192f6e4c748fa8d67b8de3886d3bb3997/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml#L38

**Comment by zhucan** [comment]
@xing-yang

**Comment by xing-yang** [comment]
@ggriffiths Do we still use "update" in some places?

**Comment by ggriffiths** [comment]
Yes, we still use Update in a number of places for now. If we run into more update errors, we can replace the rest with patch.
