### ISSUE TITLE
request a new release for arm64 support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/external-snapshotter#614]
current master branch should already supports arm64 build, need to cut a new release for arm64 support
@xing-yang thanks.

**Comment by xing-yang** [comment]
Can you wait until 1.23 release?  There's a RC build: https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v5.0.0-rc1.  Can you use that first?

**Comment by xing-yang** [comment]
We use RC images for CI now:
https://github.com/kubernetes-csi/external-snapshotter/commit/d880aa1a741131855306aa8567456f18f4c49c93

**Comment by andyzhangx** [comment]
> @andyzhangx Can you wait until 1.23 release? There's a RC build: https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v5.0.0-rc1. Can you use that first?

sure, thanks.
