### ISSUE TITLE
Take advantage of `csi_secret` in CSI 1.0

### ISSUE THREAD

**Issue by saad-ali** [kubernetes-csi/external-snapshotter#62]
CSI 1.0 decorates senstive fields with `csi_secret`. Let's take advantage of this feature to programmatically ensure no sensitive fields are ever logged by this side car container.

**Comment by pohly** [comment]
PR open against external-provisioner: https://github.com/kubernetes-csi/external-provisioner/pull/171

Needs to be reviewed there and then could be copied into external-snapshotter.
