### ISSUE TITLE
can not delete VolumeSnapshot and VolumeSnapshotContent after deleting VolumeSnapshotClass still happen

### ISSUE THREAD

**Issue by cwyj** [kubernetes-csi/external-snapshotter#629]
version info:
csi-provisioner:v2.0.4
csi-snapshotter:v3.0.2
snapshot-controller:v3.0.3

snapshot-controller error log:
snapshot_controller_base.go:192] Failed to sync snapshot "default/new-snapshot-test", will retry again: snapshot controller failed to update new-snapshot-test on API server: failed to update object (Update for snapshot.storage.k8s.io/v1beta1, Kind=VolumeSnapshot) managed fields: failed to update ManagedFields: failed to convert old object: request to convert CR to an invalid group/version: snapshot.storage.k8s.io/v1

kubectl describe  VolumeSnapshot new-snapshot-test
Name:         new-snapshot-test
Namespace:    default
Labels:       <none>
Annotations:  API Version:  snapshot.storage.k8s.io/v1beta1
Kind:         VolumeSnapshot
Metadata:
  Creation Timestamp:             2021-11-30T06:15:21Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2021-12-15T02:00:13Z
  Finalizers:
    snapshot.storage.kubernetes.io/volumesnapshot-as-source-protection
  Generation:  2
  Managed Fields:
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:source:
          .:
          f:persistentVolumeClaimName:
        f:volumeSnapshotClassName:
    Manager:      kubectl
    Operation:    Update
    Time:         2021-11-30T06:15:21Z
    API Version:  snapshot.storage.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
      f:status:
        .:
        f:boundVolumeSnapshotContentName:
        f:creationTime:
        f:readyToUse:
        f:restoreSize:
    Manager:         snapshot-controller
    Operation:       Update
    Time:            2021-11-30T06:16:14Z
  Resource Version:  249075043
  Self Link:         /apis/snapshot.storage.k8s.io/v1beta1/namespaces/default/volumesnapshots/new-snapshot-test
  UID:               616cf6fa-30c3-470d-84f4-34198a7feefb
Spec:
  Source:
    Persistent Volume Claim Name:  pvc-template-test-rbd2-0
  Volume Snapshot Class Name:      csi-snapclass-default
Status:
  Bound Volume Snapshot Content Name:  snapcontent-616cf6fa-30c3-470d-84f4-34198a7feefb
  Creation Time:                       2021-11-30T06:15:28Z
  Ready To Use:                        true
  Restore Size:                        5Gi
Events:                                <none>

**Comment by Kartik494** [comment]
@cwyj Could you provide deployment yaml files you are using . so that i can check this in my environment.

**Comment by Kartik494** [comment]
Hi @cwyj Could you please close this issue , if no more query required from your side on this.
