### ISSUE TITLE
setup-controller image are not sync with release setup-snapshot-controller.yaml file

### ISSUE THREAD

**Issue by Jainbrt** [kubernetes-csi/external-snapshotter#630]
Steps to reproduce : 

1. Downloaded below  setup-snapshot-controller.yaml file for v4.2.1 release 

https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.2.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

2. Check the k8s.gcr.io/sig-storage/snapshot-controller image 

it shows version v4.2.0, while it should match to 4.2.1. 

Expected behavior : 

```
k8s.gcr.io/sig-storage/snapshot-controller:v4.2.0

should be replace with 

k8s.gcr.io/sig-storage/snapshot-controller:v4.2.1
```

Impact : volumesnapshot are not coming in ready state

**Comment by xing-yang** [comment]
@SmruthiManjunath can you take a look of this?

**Comment by SmruthiManjunath** [comment]
"/assign"

**Comment by xing-yang** [comment]
This is fixed.
