### ISSUE TITLE
Nor clear if csi-snapshotter is needed and when, not to mention the weird namespacing

### ISSUE THREAD

**Issue by pkit** [kubernetes-csi/external-snapshotter#632]
It's not clear from the docs what's the purpose of `csi-snapshotter` `StatefulSet` and how it should be configured.
Is it needed for `ebs` driver or not for example?

**Comment by xing-yang** [comment]
That's just a deployment example. For ebs driver, you should take a look of the ebs driver doc and see what's recommended way to deploy.

**Comment by pkit** [comment]
Thanks.
I found out that it's installed in ebs driver anyway.

Still I couldn't find any docs on how it should be used in all the specific cases.
It seems like the world didn't catch on to the split of `external-snapshotter` yet.

**Comment by xing-yang** [comment]
We only provide a deployment example using CSI hostpath driver. For specific CSI drivers, driver maintainer will provide deployment steps. This is the same with all other CSI sidecars. 
https://github.com/kubernetes-csi/csi-driver-host-path#csi-hostpath-driver
