### ISSUE TITLE
docker image for snapshot-validation-webhook:v5.0.0 is not present

### ISSUE THREAD

**Issue by PSjoe** [kubernetes-csi/external-snapshotter#637]
There appears to be no docker image for the web hook 5.0.0 release:

```
docker pull k8s.gcr.io/sig-storage/snapshot-validation-webhook:v5.0.0
Error response from daemon: manifest for k8s.gcr.io/sig-storage/snapshot-validation-webhook:v5.0.0 not found: manifest unknown: Failed to fetch "v5.0.0" from request "/v2/sig-storage/snapshot-validation-webhook/manifests/v5.0.0".
```

The release tag docs suggest there should be:  https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v5.0.0

**Comment by xing-yang** [comment]
For some reason, the snapshot validation webhook image for v5.0.0 was not automatically created.  I'm still investigating.  For now, please use v5.0.0-rc1 or v4.2.1.

**Comment by xing-yang** [comment]
Keep this open until the image is published.

**Comment by xing-yang** [comment]
k8s.gcr.io/sig-storage/snapshot-validation-webhook:v5.0.0 is available now.
