### ISSUE TITLE
Validation-webhook of `v1beta1.VolumeSnapshotContent` not work

### ISSUE THREAD

**Issue by astraw99** [kubernetes-csi/external-snapshotter#638]
In my cluster, the VolumeSnapshotContent version is:
```
volumesnapshotcontents    snapshot.storage.k8s.io/v1beta1
```

the client lib is: `github.com/kubernetes-csi/external-snapshotter/client/v4 v4.2.0`
K8s Client Version: `v1.21.0`, Server Version: `v1.18.4-tke.3`

Issue is: 
we can edit the immutable fields like `snapcontent.Spec.Source.VolumeHandle` or `snapcontent.Spec.Source.SnapshotHandle`, by kubectl or apiserver update request and response OK.

PTAL if the validation-webook needs to config properly or it is a bug.

**Comment by bobbywatson3** [comment]
I just encountered this behavior as well. I was able to change the `snapshotHandle` of a `VolumeSnapshotContent`. I expected this to raise an error. Instead, the `snapshotHandle` was changed in the installed kubernetes manifest, but it doesn't look like the underlying snapshot was changed. This was in use by a volumesnapshot that was associated with a PVC that was attached to a running pod, so I don't even know what the desired behavior would be if it were actually possible to change the underlying snapshot handle.

**Comment by xing-yang** [comment]
Both snapshot-validation-webhook v4.2.0 and v3.0.3 have logic to validate immutability:
```
https://github.com/kubernetes-csi/external-snapshotter/blob/v4.2.0/pkg/validation-webhook/snapshot.go#L286-L290
https://github.com/kubernetes-csi/external-snapshotter/blob/v3.0.3/pkg/validation-webhook/snapshot.go#L190-L194
```

Have you deployed snapshot-validation-webhook?  Can you share what image of snapshot-validation-webhook is deployed?  Please note that is a different image from snapshot-controller and csi-snapshotter.

**Comment by RaunakShah** [comment]
Potentially related to https://github.com/kubernetes-csi/external-snapshotter/issues/705?

**Comment by xing-yang** [comment]
> Potentially related to https://github.com/kubernetes-csi/external-snapshotter/issues/705?

No, #705 is fixing the latest logic added to the webhook.  This was reported long before that logic was added.
