### ISSUE TITLE
snapshot controller v4.2.1 crash due to fail list v1 volumesnapshots to invalid group/version: snapshot.storage.k8s.io/v1alpha1

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/external-snapshotter#646]
snapshot controller v4.2.1 crash due to fail list v1 volumesnapshots to invalid group/version: snapshot.storage.k8s.io/v1alpha1

@xing-yang any guide about how to mitigate this issue? I believe user has installed `snapshot.storage.k8s.io/v1alpha1` crds and created related object and we could not find those `v1alpha1` CRDs any more.

To mitigate this issue, shall we install `snapshot.storage.k8s.io/v1alpha1` crds, and delete those object manually? and how can I install `snapshot.storage.k8s.io/v1alpha1` crds nowadays.

 - detailed error msg:
```
I0118 09:25:32.514655       1 main.go:121] Version: v4.2.1-0-g6fc14b4f
I0118 09:25:32.520631       1 main.go:162] Start NewCSISnapshotController with kubeconfig [/etc/kubernetes/kubeconfig/kubeconfig.yaml] resyncPeriod [15m0s]
E0118 09:25:32.577351       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:32.684614       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:32.841880       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:33.074159       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:33.418613       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:33.931435       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:34.696931       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:35.843745       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:37.558643       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:40.129282       1 main.go:82] Failed to list v1 volumesnapshots with error=request to convert CR from an invalid group/version: snapshot.storage.k8s.io/v1alpha1E0118 09:25:40.129316       1 main.go:178] Exiting due to failure to ensure CRDs exist during startup: timed out waiting for the condition
```

**Comment by xing-yang** [comment]
We documented that user should delete snapshots created using v1alpha1 CRD and uninstall v1alpha1 CRD before upgrading to v1beta1:
https://github.com/kubernetes-csi/external-snapshotter#upgrade-from-v1alpha1-to-v1beta1

I'm not sure if there are better approaches.

**Comment by xing-yang** [comment]
Yes, you could manually install v1alpha1 CRDs and delete them manually.  You can take a look of earlier docs.

**Comment by andyzhangx** [comment]
@xing-yang do you know where v1alpha1 CRDs are? I could not find it under https://github.com/kubernetes-csi/external-snapshotter/tree/v1.2.2/deploy/kubernetes

**Comment by Madhu-1** [comment]
It was getting created by the external snapshotter https://github.com/kubernetes-csi/external-snapshotter/blob/b3f591d85cce516e431c70e5337d5c67611ae2fe/cmd/csi-snapshotter/create_crd.go#L28

**Comment by dashjay** [comment]
Can we provide a converter help to migrate elegantly, as document of k8s: [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion)

**Comment by xing-yang** [comment]
We discussed about this in the past and decided not to support v1alpha1 conversion.

We documented that user should delete snapshots created using v1alpha1 CRD and uninstall v1alpha1 CRD before upgrading to v1beta1:
https://github.com/kubernetes-csi/external-snapshotter#upgrade-from-v1alpha1-to-v1beta1
