### ISSUE TITLE
VolumeSnapshot Storage Quota

### ISSUE THREAD

**Issue by ctml91** [kubernetes-csi/external-snapshotter#663]
Hello!

Is it possible today (or in the future) for ResourceQuotas to support storage snapshots based on size as opposed to object count? For my purpose I don't particularly find setting the [ResourceQuota using object count](https://github.com/kubernetes-csi/external-snapshotter#setting-quota-limits-with-snapshot-custom-resources) for storage objects to be very useful (though I am sure it can be for some). The impact on a snapshot in terms of resources is storage space, so having a mechanism to control that space would be ideal. I understand there are probably some challenges with scoping of CRDs (VolumeSnapshotContents) and I am not here to offer a solution unfortunately, but perhaps there are some clever folks out there who may be able to?

Ideally any VolumeSnapshots have an impact on a `ResourceQuotas` `requests.storage` quota, possible by extending resource requests for storage into the CRD using the size of the PVC or underlying VolumeSnapshotContents. Much like PersistentVolumeClaims which have an impact on `requests.storage` in a quota, they themselves are mapped to other cluster resources (PersistentVolumes) so would the same be possible for VolumeSnapshots? For our use case, I can't see us allowing snapshots to be used in a cluster without having precise control of the storage consumption of different users. Thanks for hearing me out.

**Comment by xing-yang** [comment]
@ctml91 I looked at this long time ago, but didn't find a solution for it due to the challenges you've already discovered.  Storage Quota is not designed to consider CRDs, so there isn't a way to support snapshot quota currently.

**Comment by ctml91** [comment]
Thanks for your feedback @xing-yang ! 

Completely understand there might be some limitations in the design of quotas and/or volumesnapshots. Unfortunately it's above be level of understanding and I am surely oversimplifying, but is it not possible to extend the interface providing `requests.storage` from core to be consumed in a VolumeSnapshot that the `Quota` can pickup? Or is it not suitable for a `VolumeSnapshot` because it has specifically been designed for PersistentVolumeClaims and PV's and as a result not something external-snapshotter can implement without changes to core? Hopefully it can be a future consideration, if not in external-snapshotter then in core to make it a possibility.

**Comment by jsafrane** [comment]
Another thing I was warned not to do: we should not copy quota code into snapshot-controller and webhook admission. It's a complex and heavily optimized code and the implementation should stay on a single place (k/k).
