### ISSUE TITLE
Webhook to ensure single default VolumeSnapshotClass

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-snapshotter#667]
**Is your feature request related to a problem?/Why is this needed**

When users create two or more default VolumeSnapshotClasses, any subsequent VolumeSnapshot they create is then pending with `Failed to set default snapshot class with error 2 default snapshot classes were found` event.

It would be cool to have an admission webhook that would prevent creation / update of the second default VolumeSnapshotClass.

**Describe the solution you'd like in detail**
A simple webhook that makes sure that there is only one default VolumeSnapshotClass for a given CSI driver, returning a nice error to users when they try to make two default snapshot classes.

**Describe alternatives you've considered**

**Additional context**

Suggested workflow for changing the default VolumeSnapshotClass for a CSI driver would be:

1. Delete the defaulting annotation from the "old" default VolumeSnapshotClass.
2. Add the annotation to the "new" default VolumeSnapshotClass.

As you can see, there is a (brief?) moment when the snapshot-controller will not see any default class and it won't be able to process VolumeSnapshots that don't have any class set (yet). I *assume* the controller will re-sync these snapshots after step 2. is completed and file the new default VolumeSnapshotClass in them. Please test this scenario carefully.

**Comment by jsafrane** [comment]
/help-wanted
This is quite standalone work that does not need to have detailed knowledge about external-snapshotter nor snapshot-controller. And there is an existing [snapshot-validation-webhook](https://github.com/kubernetes-csi/external-snapshotter/tree/master/cmd/snapshot-validation-webhook) + its deployment files that can be used as a good example.

**Comment by shawn-hurley** [comment]
@jsafrane I would like to take this on, is there any need for a KEP or something or do you imagine the webhook would live in this repo?

**Comment by xing-yang** [comment]
@jsafrane How is this handled for default StorageClass?

**Comment by jsafrane** [comment]
There is one open design question: shall it be part of the existing VolumeSnapshot validation webhook binary or a separate one? I'm inclined to put it into the existing one, but I don't have a strong opinion about it.

**Comment by xing-yang** [comment]
I vaguely remember there was a reason to allow more than 1 default VolumeSnapshotClasses when we were developing that part of code.  I'll need to dig more into this.  @jingxu97 @yuxiangqian Do you remember anything about this?

**Comment by xing-yang** [comment]
I found it.  We actually added notes in the VolumeSnapshotClass API to explain why multiple default VolumeSnapshotClasses may be needed.  See here:
https://github.com/kubernetes-csi/external-snapshotter/blob/v5.0.1/client/apis/volumesnapshot/v1/types.go#L85-L86

**Comment by shawn-hurley** [comment]
@xing-yang does this mean that the validation has to check for a single default per-driver then?

**Comment by xing-yang** [comment]
@shawn-hurley Yes.
