### ISSUE TITLE
Fail to delete VolumeSnapshotContent without VolumeSnapshot

### ISSUE THREAD

**Issue by blackpiglet** [kubernetes-csi/external-snapshotter#678]
I'm using a Backup/Restore tools with CSI volume snapshot. 

The current behavior of the B/R tools is using VolumeSnapshotContent as a place holder for future potential cleanup the snapshot on cloud provider, so in some cases, k8s clusters may only have VolumeSnapshotContent without VolumeSnapshot.

When deletion of the standalone VolumeSnapshotContent is triggered, only deletionTimestamp is added, then the VolumeSnapshotContent would hang forever.

I saw this comment from external-snapshotter repository, but I didn't find related logic to handle "snapshot == nil" situation. 

https://github.com/kubernetes-csi/external-snapshotter/blob/v5.0.1/pkg/common-controller/snapshot_controller.go#L123-L126

``` go
	// Check if snapshot exists in cache store
	// If getSnapshotFromStore returns (nil, nil), it means snapshot not found
	// and it may have already been deleted, and it will fall into the
	// snapshot == nil case below
	var snapshot *crdv1.VolumeSnapshot
	snapshot, err = ctrl.getSnapshotFromStore(snapshotName)
	if err != nil {
		return err
	}
```

So I'm not sure whether current result is the supposed behavior of snapshot controller. 

#### Additional Information
snapshot-controller and csi-snapshotter version: v5.0.1
k8s version: v1.23
Cloud provider: GKE and AKS

**Comment by xing-yang** [comment]
Can you do a "kubectl describe" of the VolumeSnapshotContent?
Also can you provide logs from csi-snapshotter sidecar?

**Comment by xing-yang** [comment]
By the way, do you try to "create" or "delete" VolumeSnapshotContent?  The issue title says "create" but the description talks about "delete".

**Comment by Kartik494** [comment]
Hi @xing-yang it seems like we don't have logic for `snapshot==nil` case but we are mentioning in the [comment](https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/common-controller/snapshot_controller.go#L124-L126) that if we don't get snapshot from  `getSnapshotFromStore()` then it will check for `snapshot==nil` case. Should we proceed forward to add the condition for that case?

**Comment by xing-yang** [comment]
@Kartik494 I need to take a look at the logs first to understand what happened.

**Comment by Kartik494** [comment]
@xing-yang  yes , Sure thing.
