### ISSUE TITLE
User "system:serviceaccount:kube-system:snapshot-controller" cannot list resource "volumesnapshots" in API group "snapshot.storage.k8s.io" at the cluster scope

### ISSUE THREAD

**Issue by mconigliaro** [kubernetes-csi/external-snapshotter#722]
I'm following the instructions here on a brand new AWS EKS cluster (`v1.22.6-eks-14c7a48`): https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html

When I deployed snapshot-controller from the `v6.0.1` tag, I noticed the following error in my `snapshot-controller-*` pod logs, which is preventing the deploy from succeeding:

`E0526 18:56:41.753296       1 main.go:87] Failed to list v1 volumesnapshots with error=volumesnapshots.snapshot.storage.k8s.io is forbidden: User "system:serviceaccount:kube-system:snapshot-controller" cannot list resource "volumesnapshots" in API group "snapshot.storage.k8s.io" at the cluster scope`

**Comment by mconigliaro** [comment]
I get the same error when using what's tagged with `v6.0.0` and `v5.0.1`.

**Comment by xing-yang** [comment]
What RBAC rules have you installed?

**Comment by mconigliaro** [comment]
I installed the following:



1. https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.0.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
1. https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.0.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
1. https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.0.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
1. https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.0.1/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
1. https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.0.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml




Probably unrelated, but I can also confirm #649. The version in `setup-snapshot-controller.yaml` for the `v6.0.1` tag seems wrong: `gcr.io/k8s-staging-sig-storage/snapshot-controller:v5.0.1`. I changed it manually and now I see:

`I0526 19:31:21.459145       1 main.go:125] Version: v6.0.1`

Same permission error though.

**Comment by mconigliaro** [comment]
I think I figured it out. I'm using [kubectl_manifest](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest) to apply these. I just noticed this:

`TIP: This resource only supports a single yaml resource.`

Your RBAC file contains many in the same document.
