### ISSUE TITLE
Incorrect image version in setup-snapshot-controller.yaml

### ISSUE THREAD

**Issue by mconigliaro** [kubernetes-csi/external-snapshotter#723]
The image version in [setup-snapshot-controller.yaml](https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml) (e.g. `v5.0.1`) is out of sync with what's available in the [repository](gcr.io/k8s-staging-sig-storage/snapshot-controller) (e.g `v6.0.1`).

**Comment by RaunakShah** [comment]
@mconigliaro would you like to create a PR to update the YAMLs?
