### ISSUE TITLE
Is it possible to take snapshots of all pvc's available in cluster?

### ISSUE THREAD

**Issue by saiharshitachava** [kubernetes-csi/external-snapshotter#726]
Is it possible to take snapshots of all pvc's available in cluster? CAn I give a * on persistentVolumeClaimName which will take all pvc snapshots for me?

apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: test-snapshot
spec:
  volumeSnapshotClassName: test-snapclass
  source:
    persistentVolumeClaimName: ebs-claim

**Comment by Madhu-1** [comment]
No this is not possible. you need to create volumesnapshot object per pvc.

**Comment by humblec** [comment]
@saiharshitachava its 1:1 mapping , so regular expression like above is not supported. I am closing this one for now.. please feel free to reopen or create new issue.
