### ISSUE TITLE
v6.0.1 controller seems to break k8s e2e tests

### ISSUE THREAD

**Issue by mattcary** [kubernetes-csi/external-snapshotter#736]
See https://testgrid.k8s.io/sig-storage-kubernetes#volume-snapshot. The failures started after https://github.com/kubernetes/kubernetes/pull/110204 was merged, which updated the controller from v4 to v6.

Failures for the mock csi driver tests are due to the VolumeSnapshot not being ready, but the snapshot-controller logs show that the VolumeSnapshotContents are being marked as ready. Maybe something changed between v4 and v6 in the processing somehow?

I can continue to dig but if anyone else has any ideas on what's going on please chime in!

/assign
/cc @humblec 
/cc @xing-yang 

(@xing-yang it appears the RBAC problem you saw is a read herring, it's happening when things are shut down and there's a race between the controller getting killed and the rbac getting destroyed. The reason for the test failure seems to be this snapshot contents vs snapshot not ready problem)

**Comment by mattcary** [comment]
Ah... I was looking for error messages around that, but I guess the tests just aren't going to find the new resources.

**Comment by humblec** [comment]
@mattcary @xing-yang shall I drop a PR to fix the same?

**Comment by xing-yang** [comment]
Here's an issue to track this: https://github.com/kubernetes/kubernetes/issues/112694

**Comment by mattcary** [comment]
/close

Tests are passing now
