### ISSUE TITLE
Shortnames conflict

### ISSUE THREAD

**Issue by vassav-nn** [kubernetes-csi/external-snapshotter#754]
**What happened**:
No resources found in default namespace.

**What you expected to happen**:
List of VirtualService

**How to reproduce it**:
kubectl get vs

**Anything else we need to know?**:

kubectl api-resources | grep vs
**virtualservices                   vs**                  networking.istio.io/v1beta1            true         VirtualService
volumesnapshotclasses             vsclass,vsclasses   snapshot.storage.k8s.io/v1             false        VolumeSnapshotClass
volumesnapshotcontents            vsc,vscs            snapshot.storage.k8s.io/v1             false        VolumeSnapshotContent
**volumesnapshots                   vs**                  snapshot.storage.k8s.io/v1             true         VolumeSnapshot

**Environment**:
- Driver version: controller-gen.kubebuilder.io/version: v0.4.0
- Kubernetes version (use `kubectl version`): v1.21.9 or v1.22.6
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`): Linux cent7 3.10.0-957.el7.x86_64
- Install tools: kubectl v1.24.0
- Others:
    shortNames:
    - vs

**Comment by ggriffiths** [comment]
Unfortunately, there isn't much that can be done about this.

CRD short names aren't reserved, so any community CRD short name can conflict with another. 

As a workaround, you can start setting up your cluster(s) with Instio CRDs first and install the snapshot CRDs second. This will allow Istio CRDs to claim the short name.

**Comment by vassav-nn** [comment]
> Unfortunately, there isn't much that can be done about this.
> 
> CRD short names aren't reserved, so any community CRD short name can conflict with another.
> 
> As a workaround, you can start setting up your cluster(s) with Istio CRDs first and install the snapshot CRDs second. This will allow Istio CRDs to claim the short name.

Or you can rename vs to vsn for example.

**Comment by ggriffiths** [comment]
I'm assuming we wouldn't want to rename `vs` to `vsn` as that isn't backwards compatible, but will defer to @xing-yang .

**Comment by xing-yang** [comment]
> I'm assuming we wouldn't want to rename vs to vsn as that isn't backwards compatible, but will defer to @xing-yang .

Right, we don't want to make backward incompatible changes.
