### ISSUE TITLE
v6.1.0 images not available

### ISSUE THREAD

**Issue by Jeinhaus** [kubernetes-csi/external-snapshotter#769]
**What happened**:

When following the docker pull commands from the [v6.1.0 release](https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.1.0) the image cannot be found:

```bash
❯ docker pull k8s.gcr.io/sig-storage/snapshot-controller:v6.1.0
Error response from daemon: manifest for k8s.gcr.io/sig-storage/snapshot-controller:v6.1.0 not found: manifest unknown: Failed to fetch "v6.1.0" from request "/v2/sig-storage/snapshot-controller/manifests/v6.1.0".
```

**What you expected to happen**:

The `docker pull` command to succeed.

**How to reproduce it**:

```bash
docker pull k8s.gcr.io/sig-storage/snapshot-controller:v6.1.0
docker pull k8s.gcr.io/sig-storage/csi-snapshotter:v6.1.0
docker pull k8s.gcr.io/sig-storage/snapshot-validation-webhook:v6.1.0
```

**Comment by Jeinhaus** [comment]
Same thing with the registry referenced in the [setup-snapshot-controller.yaml](https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml):

```bash
❯ docker pull registry.k8s.io/sig-storage/snapshot-controller:v6.1.0
Error response from daemon: manifest for registry.k8s.io/sig-storage/snapshot-controller:v6.1.0 not found: manifest unknown: Failed to fetch "v6.1.0" from request "/v2/sig-storage/snapshot-controller/manifests/v6.1.0".
```

**Comment by tgip-work** [comment]
Same for me.

This works for me:

```shell
docker pull gcr.io/k8s-staging-sig-storage/snapshot-controller:v6.1.0
docker pull gcr.io/k8s-staging-sig-storage/snapshot-controller:v6.1.0@sha256:823c75d0c45d1427f6d850070956d9ca657140a7bbf828381541d1d808475280
```

Also see [https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/GLOBAL/snapshot-controller](https://console.cloud.google.com/gcr/images/k8s-staging-sig-storage/GLOBAL/snapshot-controller)


Also for older version:
`docker pull gcr.io/k8s-staging-sig-storage/snapshot-controller:v6.0.1@sha256:a49993c3325b4bb010e52b8e661ebc62b9d45ebceae6e432d3ee637a4833bae7`

**Comment by xing-yang** [comment]
Can you try now?  The images should be there now.

**Comment by Jeinhaus** [comment]
Yes, I can confirm, that the images linked in the release are available now.
I'm still a bit confused about the image linked in the release page and the ones referenced in the [setup-snapshot-controller.yaml](https://github.com/kubernetes-csi/external-snapshotter/blob/ba73208e901b26b47a28e259626c5d802118f6f8/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml#L36).

**Comment by xing-yang** [comment]
I'll update the release page to use registry.k8s.io.  Both should work.  It is a re-direction but we are supposed to use registry.k8s.io now.

**Comment by Jeinhaus** [comment]
Thank you. :tada:
