### ISSUE TITLE
Error with VolumeSnapshotContent.snapshot.storage.k8s.io spec.sourceVolumeMode: Invalid value: "null"

### ISSUE THREAD

**Issue by 7309766** [kubernetes-csi/external-snapshotter#773]
**What happened**:
Created two resources:

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: my-ebs-csi-snapshot-class-handle
driver: ebs.csi.aws.com
deletionPolicy: Retain
—-
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: ebs-volume-snapshot-test
  namespace: monitoring
spec:
  volumeSnapshotClassName: my-ebs-csi-snapshot-class-handle
  source:
    persistentVolumeClaimName: test-pvc

$ kubectl describe volumesnapshot

[....]
Error:
    Message:     Failed to create snapshot content with error snapshot controller failed to update ".." on API server: VolumeSnapshotContent.snapshot.storage.k8s.io "snapcontent-602046fe-7f53-4dde-8608-23ffe783cc06" is invalid: spec.sourceVolumeMode: Invalid value: "null": spec.sourceVolumeMode in body must be of type string: "null"

**What you expected to happen**:
A snapshot should be created.

**How to reproduce it**:
snapshot-controller:v6.1.0
EKS k8s version: v1.19.16-eks-a05fdea

**Anything else we need to know?**:

**Environment**:
snapshot-controller:v6.1.0
EKS k8s version: v1.19.16-eks-a05fdea
aws-ebs-csi-driver

- Others:

**Comment by RaunakShah** [comment]
I ran this on CSI host path driver and was able to provision the snapshot:

```
% kubectl get pvc,volumesnapshot
NAME                            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
persistentvolumeclaim/csi-pvc   Bound    pvc-f1a4c129-e0ff-4295-a552-8afa68687c83   1Gi        RWO            csi-hostpath-sc   4m5s

NAME                                                              READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS            SNAPSHOTCONTENT                                    CREATIONTIME   AGE
volumesnapshot.snapshot.storage.k8s.io/ebs-volume-snapshot-test   true         csi-pvc                             1Gi           csi-hostpath-snapclass   snapcontent-f38875fb-9c2a-4c31-a95a-df45a7f41ebe   2m52s          2m52s
```

This is my snapshotter and provisioner versions:
```
% kubectl describe sts | grep -i image 
...
    Image:      csi-provisioner:v3.3.0
    Image:      k8s.gcr.io/sig-storage/snapshot-controller:v6.1.0
```

Can you confirm that you enabled `--prevent-volume-mode-conversion` In both of these containers?

**Comment by RaunakShah** [comment]
You need to enable it on snapshot-controller as well as external-provisioner. 

But were you running into this issue before the flags were enabled?

**Comment by 7309766** [comment]
> You need to enable it on snapshot-controller as well as external-provisioner.
> 
> But were you running into this issue before the flags were enabled?

No, this flag was omitted

**Comment by RaunakShah** [comment]
Can you paste the logs of snapshot-controller without the feature flag enabled?

**Comment by 7309766** [comment]
> Can you paste the logs of snapshot-controller without the feature flag enabled? I want to trace where you are running into an error
Here
https://pastebin.com/kjwjMqQu

**Comment by RaunakShah** [comment]
@7309766 can you also tell me what version of snapshot CRDs have been installed on the cluster?

**Comment by 7309766** [comment]
> @7309766 can you also tell me what version of snapshot CRDs have been installed on the cluster?

    controller-gen.kubebuilder.io/version: v0.8.0
    api-approved.kubernetes.io: "https://github.com/kubernetes-csi/external-snapshotter/pull/665"
