### ISSUE TITLE
Restore volumesnapshot

### ISSUE THREAD

**Issue by samuelkerchouni** [kubernetes-csi/external-snapshotter#792]
Hello,

I have an issue with VolumeSnapshot on my GKE 1.22.

My goal is to backup / restore volumesnapshot on other namespace to duplicate my database on postgres

I explain my process  : 
  - I create a volumesnapshot on my source namespace
  - I get volume Handle of my volumesnapshotcontent
  - I copy/past my volume Handle to create a new volumesnapshotcontent 
  - I create my new volumesnapshotcontent
  - I create my new volumesnapshot from volumesnapshotcontent 
  - I create my pvc with like source my volumesnapshot

I create my deployment with my pvc just created before. 

My pod is ok, my files is here, database UP.

I do the same on another namespace, still ok. again & again without any error.

After a few moment, my PVC failed to create because volumesnapshot is failed with this error : 

"Message:     Failed to check and update snapshot content: failed to list snapshot for content pg-gke-snapshot-content-namespace: "can not fi
nd snapshot for snapshotID projects/project-id/global/snapshots/snapshot-43fedc39-60d4-47a3-ad6z-a6953e8ad266" 

The volume handle is good, the source volumesnapshot is still available and true. 

If i delete the source volumesnapshot and recreate it, get new Handle & replace it, it's work and same after a moment, failed ...

Do we have a quota on volumesnapshot ? or expiration ? I try to understand.. 

Thanks for your help. If needed i can give you the yaml files .

**Comment by xing-yang** [comment]
In the final step - "I create my pvc with like source my volumesnapshot", is the PVC in a namespace that is different from VolumeSnapshot created in step 1?
What did you do to the VolumeSnapshot created in step 1 after the final step?  Do you have 2 VolumeSnapshots, one in the source namespace and the other in the destination namespace, both point to the same snapshot on the storage system?
Did you delete the VolumeSnapshot at any step?  Is the Deletion Policy set to "Delete" or "Retain"?

**Comment by samuelkerchouni** [comment]
Hi,
Thanks for your reply and your help 

In the final step - "I create my pvc with like source my volumesnapshot", is the PVC in a namespace that is different from VolumeSnapshot created in step 1? -> Yes it's my new volumesnapshot in the target namespace ( build from volumesnapshotcontent )

What did you do to the VolumeSnapshot created in step 1 after the final step? ->  I keep the source volumesnapshot furthermore  it's still "true" and also available.

Do you have 2 VolumeSnapshots, one in the source namespace and the other in the destination namespace, both point to the same snapshot on the storage system -> yes true i have a source snapshot in source namespace and target snapshot in target namespace , i create a volumesnapshot target from my volumesnapshotcontent target from volumesnapshotcontent source.

Did you delete the VolumeSnapshot at any step? -> never delete the volumesnapshot source, but i delete/recreate it, it's works for a moment also..

 Is the Deletion Policy set to "Delete" or "Retain"? -> Set to "Delete"

If you want i can send you the yaml file to do it.

Thanks again for your help.

Sam

**Comment by samuelkerchouni** [comment]
Hi @xing-yang,
How are you ? Do you have some news about my issue ?
Thanks a lot, have a nice day
Sam
