### ISSUE TITLE
no snapshot-validation-webhook image for 6.2.0

### ISSUE THREAD

**Issue by WanzenBug** [kubernetes-csi/external-snapshotter#803]
The webhook image for release 6.2.0 is not available:

```
$ docker pull registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.0
Error response from daemon: manifest for registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.0 not found: manifest unknown: Failed to fetch "v6.2.0"
```

In contrast, the `snapshot-controller` image is available:
```
$ docker pull registry.k8s.io/sig-storage/snapshot-controller:v6.2.0
v6.2.0: Pulling from sig-storage/snapshot-controller
fc251a6e7981: Pull complete 
7b7c94814810: Pull complete 
Digest: sha256:2fdd2e646bdda56c9e728d4758c037088f69275815ee10d0b45ae3f4e3cac314
Status: Downloaded newer image for registry.k8s.io/sig-storage/snapshot-controller:v6.2.0
registry.k8s.io/sig-storage/snapshot-controller:v6.2.0
```

**Comment by msau42** [comment]
It looks like the build timed out: https://k8s-testgrid.appspot.com/sig-storage-image-build#post-external-snapshotter-push-images

We'll probably need to address this next week with a new tag.

**Comment by onedr0p** [comment]
Could it be retried?

**Comment by msau42** [comment]
I think the retry will fail when trying to repush snapshot-controller:v6.2.0 which already exists.

**Comment by briantopping** [comment]
FYI Gardener is waiting on this as well, this release has corrections for several CVEs.

**Comment by xing-yang** [comment]
v6.2.1 is released.  snapshot-validation-webhook image v6.2.1 is available.
