### ISSUE TITLE
Images for v6.2.1 not available

### ISSUE THREAD

**Issue by trallnag** [kubernetes-csi/external-snapshotter#805]
**What happened**:

The following images are not available as of now:

```
registry.k8s.io/sig-storage/snapshot-controller:v6.2.1
registry.k8s.io/sig-storage/csi-snapshotter:v6.2.1
registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.1
```

Getting errors like this:

> Failed to pull image "registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.1": rpc error: code = NotFound desc = failed to pull and unpack image "registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.1": failed to resolve reference "registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.1": registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.2.1: not found

**Comment by xing-yang** [comment]
This is fixed now.

**Comment by trallnag** [comment]
thanks
