### ISSUE TITLE
add support for json format logging

### ISSUE THREAD

**Issue by dmpe** [kubernetes-csi/external-snapshotter#813]
**Is your feature request related to a problem?/Why is this needed**

I would like that snapshot controller logs its information in JSON format instead currently in simple "text" format

```
I0224 10:26:28.314917 1 snapshot_controller_base.go:187] enqueued "nexus/nexus-data-nexus-0-6lgr9" for sync
```

is hard to send properly to ElasticSearch....

**Describe the solution you'd like in detail**

by using some parameter such as `--log-format=json` I am able to configure snapshot controller to output logs in JSON format.

**Additional context**

Using snapshot-controller v6.1.0 at the moment and I did not found such option.

#contextual logging -> https://kubernetes.io/blog/2022/05/25/contextual-logging/

Thanks.

**Comment by jdfalk** [comment]
This issue still exists and is something necessary for our logging systems to correctly aggregate the logs and not flood our logging systems with duplicate messages.
