### ISSUE TITLE
Add secrets in CreateVolumeGroupSnapshots

### ISSUE THREAD

**Issue by xing-yang** [kubernetes-csi/external-snapshotter#834]

**Comment by xing-yang** [comment]
Currently nothing is passed through snapshotterCredentials.  There's a TODO here:
https://github.com/kubernetes-csi/external-snapshotter/blob/master/pkg/sidecar-controller/groupsnapshot_helper.go#L368

See this PR as an example: https://github.com/kubernetes-csi/external-snapshotter/pull/165/

**Comment by Madhu-1** [comment]
@carlory can you please update on this one, without this support we cannot implement volumegroup in cephcsi driver.

**Comment by Madhu-1** [comment]
@carlory great thank you, will take care of this one.

/assign @Madhu-1
