### ISSUE TITLE
external-snapshotter imports older version of snapshot client

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-snapshotter#839]
**What happened**:

In today's go.mod I can see that it imports older version of external-snapshotter/client:

https://github.com/kubernetes-csi/external-snapshotter/blob/98b244f0d421c493d840ce7822b0a720ac8ac67f/go.mod#L13C2
```
require (
...
	github.com/kubernetes-csi/external-snapshotter/client/v6 v6.1.0
```

And in the end, the older version is even [vendored](https://github.com/kubernetes-csi/external-snapshotter/tree/98b244f0d421c493d840ce7822b0a720ac8ac67f/vendor/github.com/kubernetes-csi/external-snapshotter/client/v6).

**What you expected to happen**:
Ideally, go.mod should not `require` the client API, it should use the one from the repo.

**Comment by nixpanic** [comment]
That line is already in place, so the copy of the files in `vendor/` should have the same version as `client/`.

https://github.com/kubernetes-csi/external-snapshotter/blob/98b244f0d421c493d840ce7822b0a720ac8ac67f/go.mod#L76

**Comment by jsafrane** [comment]
You're right, `replace` fixes it
/close
