### ISSUE TITLE
Missing docker images for 6.2.2 release?

### ISSUE THREAD

**Issue by james-callahan** [kubernetes-csi/external-snapshotter#842]
**What happened**:
I'm not able to see the new 6.2.2 docker image anywhere.

Trying to use the docker registry in [the github release](https://github.com/kubernetes-csi/external-snapshotter/releases/tag/v6.2.2)
```
$ skopeo inspect docker://registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2 --raw
FATA[0000] Error parsing image name "docker://registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2": reading manifest v6.2.2 in registry.k8s.io/sig-storage/csi-snapshotter: manifest unknown: Failed to fetch "v6.2.2" 
```
Trying to use the docker regsitry in the README:
```
$ skopeo inspect docker://k8s.gcr.io/sig-storage/csi-snapshotter
FATA[0001] Error parsing image name "docker://k8s.gcr.io/sig-storage/csi-snapshotter": reading manifest latest in k8s.gcr.io/sig-storage/csi-snapshotter: manifest unknown: Failed to fetch "latest" from request "/v2/sig-storage/csi-snapshotter/manifests/latest". 
```
Double checking if AWS have it:
```
$ skopeo inspect docker://public.ecr.aws/eks-distro/kubernetes-csi/external-snapshotter/csi-snapshotter:v6.2.1-eks-1-27-3 | jq .RepoTags | sort | tail
  "v6.2.1-eks-1-26-6",
  "v6.2.1-eks-1-26-7",
  "v6.2.1-eks-1-26-8",
  "v6.2.1-eks-1-26-9",
  "v6.2.1-eks-1-26-latest",
  "v6.2.1-eks-1-27-1",
  "v6.2.1-eks-1-27-2",
  "v6.2.1-eks-1-27-3",
  "v6.2.1-eks-1-27-4",
  "v6.2.1-eks-1-27-latest",
```

**What you expected to happen**:

The docker image should have been uploaded as part of the release process

**How to reproduce it**:

Try and pull the docker image for this project

**Anything else we need to know?**:

The README probably needs updating to `registry.k8s.io`?
https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/

**Environment**:
- Driver version: 6.2.2
- Kubernetes version (use `kubectl version`): N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools:
- Others:

**Comment by xing-yang** [comment]
The images will be available once this PR is merged: https://github.com/kubernetes/k8s.io/pull/5334

**Comment by nixpanic** [comment]
The PR has been merged and images are available:

```
$ skopeo inspect docker://registry.k8s.io/sig-storage/csi-snapshotter:v6.2.2 | head
{
    "Name": "registry.k8s.io/sig-storage/csi-snapshotter",
    "Digest": "sha256:becc53e25b96573f61f7469923a92fb3e9d3a3781732159954ce0d9da07233a2",
    "RepoTags": [
        "sha256-0d8d81948af4897bd07b86046424f022f79634ee0315e9f1d4cdb5c1c8d51c90.sig",
        "sha256-291334908ddf71a4661fd7f6d9d97274de8a5378a2b6fdfeb2ce73414a34f82f.sig",
        "sha256-714aa06ccdd3781f1a76487e2dc7592ece9a12ae9e0b726e4f93d1639129b771.sig",
        "sha256-780754d371551de7f3c7f24b3250f70ee0b1d57bdcba022ec4526f302927cacf.sig",
        "sha256-ad16874e2140256a809cada2b4ac3d931d5b73b0bee23ed0f8d60bdd778cfec2.sig",
        "sha256-becc53e25b96573f61f7469923a92fb3e9d3a3781732159954ce0d9da07233a2.sig",
```

/close

**Comment by james-callahan** [comment]
> The README probably needs updating to `registry.k8s.io`?

This still needs to be done.
![image](https://github.com/kubernetes-csi/external-snapshotter/assets/35791147/efb2a2a8-1200-430e-8a2b-b9a6c4376777)
