### ISSUE TITLE
ObjectMeta fields missing from CRDs

### ISSUE THREAD

**Issue by bjschafer** [kubernetes-csi/external-snapshotter#845]
The CRD yaml files in `client/config/crd` ([e.g.](https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml)) do not allow for standard metadata, according to their schemae.

However, looking at the struct definitions under `client/apis` ([e.g.](https://github.com/kubernetes-csi/external-snapshotter/blob/master/client/apis/volumesnapshot/v1/types.go#LL211C4-L211C4)), they correctly embed (and thus support) `metav1.ObjectMeta` -- and the docs reflect this as well.

This isn't problematic at first glance, because the controller recognizes and knows how to handle `ObjectMeta` in an applied resource. We only noticed it because we have a CI linter that validates applied resources against the schema as defined in the CRD.

I'll submit a PR to resolve this discrepancy.

**Comment by xing-yang** [comment]
The manifest was generated as documented below.  There are some manual steps involved after running the script.  If you are submitting a PR, please make sure to update the doc for any manual step:
https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/hack#update-crdsh
