### ISSUE TITLE
Image version doesn't match manifest version

### ISSUE THREAD

**Issue by imjasonh** [kubernetes-csi/external-snapshotter#872]
**What happened**:

Installing the deployment at v6.2.2 installs the image at v6.2.1

**What you expected to happen**:

Installing v6.2.2 installs the image tagged v6.2.2

**How to reproduce it**:

```
curl -q https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.2.2/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml | grep image:
          image: registry.k8s.io/sig-storage/snapshot-controller:v6.2.1
```

And it goes back even further:

```
curl -q https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.2.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml | grep image:
          image: registry.k8s.io/sig-storage/snapshot-controller:v6.1.0
```

```
curl -q https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v6.2.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml | grep image:
          image: registry.k8s.io/sig-storage/snapshot-controller:v6.1.0
```

See https://github.com/kubernetes-csi/external-snapshotter/blob/v6.2.2/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml#L36

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`):

KinD on Apple M1

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```

- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by liangyuanpeng** [comment]
Seems like release process have some problem.

**Comment by albertoacebeseviden** [comment]
yes, is unaligned in the tag v6.2.2 [setup-snapshot-controller.yaml#L36](https://github.com/kubernetes-csi/external-snapshotter/blob/v6.2.2/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml#L36)
