### ISSUE TITLE
Provide default resource limits and requests

### ISSUE THREAD

**Issue by EHJ-52n** [kubernetes-csi/external-snapshotter#884]
**Is your feature request related to a problem?/Why is this needed**

Provide resource requests and limits in [setup-snapshot-controller.yaml](https://github.com/kubernetes-csi/external-snapshotter/blob/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml). Atm, these are missing.

**Describe the solution you'd like in detail**
None.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Madhu-1** [comment]
IMO it's not easy to decide on the default resource limits and requests as it completely depends on the workload the snapshot controller is supposed to handle. it should be something the admin should decide during the deployment.
