### ISSUE TITLE
Facing issues while deleting VSC

### ISSUE THREAD

**Issue by ashwinshelke1001** [kubernetes-csi/external-snapshotter#894]
I created VS and VSC using volumesnapshotclass which has our own CSI driver.

During cleanup, I remove CSI driver first and tried to delete VS and VSC resource after that.

It should be removed but, I am observing that deletion is getting stuck,
  
With this same cleanup process, I am NOT observing issues in PVC and PV deletion.

Please help.

**Comment by Madhu-1** [comment]
@ashwinshelke1001 CSI driver needs to be present to delete the VS and VSC as the snapshotter needs to ensure that backend storage snapshots are deleted. if you want it to be deleted you need to remove the finalizers.

>With this same cleanup process, I am NOT observing issues in PVC and PV deletion.

I doubt that. you will be able to delete the PVC but the PV will not get deleted until the the backend storage is deleted.
