### ISSUE TITLE
DeleteSnapshot RPC is sent to CSI driver when clone was in progress.

### ISSUE THREAD

**Issue by Madhu-1** [kubernetes-csi/external-snapshotter#905]
**What happened**:

DeleteSnapshot RPC is sent to the CSI driver when the clone is in progress. 

Note: The clone was created in a different namespace using  https://kubernetes.io/blog/2023/01/02/cross-namespace-data-sources-alpha/#create-a-persistentvolumeclaim-by-using-cross-namespace-data-source and i think https://github.com/kubernetes-csi/external-snapshotter/blob/06548512ab050b6529a7d0662f169511152883d2/pkg/common-controller/snapshot_controller.go#L866 is only applicable when clone and snapshot are in same namespace.

**What you expected to happen**:

Dont send the DeleteSnapshot RPC clone when clone was in progress.

**How to reproduce it**:
Follow the steps in https://kubernetes.io/blog/2023/01/02/cross-namespace-data-sources-alpha/#create-a-persistentvolumeclaim-by-using-cross-namespace-data-source and ensure to delete the volume snapshot when the clone was in progress.

**Anything else we need to know?**:

**Environment**:
- Driver version:
- Kubernetes version (use `kubectl version`): 
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Madhu-1** [comment]
@xing-yang any thoughts?

**Comment by xing-yang** [comment]
I think the cross namespace feature was not there when this was implemented.  It makes sense to fix it.
@Madhu-1 Are you interested in working on a fix?

**Comment by liangyuanpeng** [comment]
I want to work for it and need some guide.
@Madhu-1 @xing-yang 

It's need the external-snapshotter support feature-gates and check isVolumeBeingCreatedFromSnapshot from all of namespace if CrossNamespaceVolumeDataSource=true. Remind me if i missed something,thanks!

here is the simple code:
```code
  CrossNamespaceVolumeDataSource := true
  if CrossNamespaceVolumeDataSource {
    pvcList, err = ctrl.pvcLister.List(labels.Everything())
  }else{
    pvcList, err = ctrl.pvcLister.PersistentVolumeClaims(snapshot.Namespace).List(labels.Everything())
  }
```

/assign

**Comment by Madhu-1** [comment]
@xing-yang i missed the ping, sorry for that, as @liangyuanpeng has already shown interest , please go ahead :)

**Comment by Madhu-1** [comment]
> I want to work for it and need some guide. @Madhu-1 @xing-yang
> 
> It's need the `external-snapshotter` support feature-gates and check isVolumeBeingCreatedFromSnapshot from all of namespace if CrossNamespaceVolumeDataSource=true. Remind me if i missed something,thanks!
> 
> here is the simple code:
> 
> ```
>   CrossNamespaceVolumeDataSource := true
>   if CrossNamespaceVolumeDataSource {
>     pvcList, err = ctrl.pvcLister.List(labels.Everything())
>   }else{
>     pvcList, err = ctrl.pvcLister.PersistentVolumeClaims(snapshot.Namespace).List(labels.Everything())
>   }
> ```
> 
> /assign

@xing-yang are you okay with introducing a new flag or any other alternative do you suggest?

**Comment by Madhu-1** [comment]
> > I want to work for it and need some guide. @Madhu-1 @xing-yang
> > It's need the `external-snapshotter` support feature-gates and check isVolumeBeingCreatedFromSnapshot from all of namespace if CrossNamespaceVolumeDataSource=true. Remind me if i missed something,thanks!
> > here is the simple code:
> > ```
> >   CrossNamespaceVolumeDataSource := true
> >   if CrossNamespaceVolumeDataSource {
> >     pvcList, err = ctrl.pvcLister.List(labels.Everything())
> >   }else{
> >     pvcList, err = ctrl.pvcLister.PersistentVolumeClaims(snapshot.Namespace).List(labels.Everything())
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > /assign
> 
> @xing-yang are you okay with introducing a new flag or any other alternative do you suggest?

@xing-yang any suggestion on this one?

**Comment by xing-yang** [comment]
There should be a finalizer added to VolumeSnapshot that it is used as a source to create a PVC:
https://github.com/kubernetes-csi/external-snapshotter/blob/v8.0.1/pkg/utils/util.go#L81
The finalizer should present the VolumeSnapshot from being deleted until the PVC is created.  Do you see the finalizer?

**Comment by yati1998** [comment]
@liangyuanpeng are you still looking into this?
