### ISSUE TITLE
Snapshot controller failing repetitively to retrieve an image pull secret from another namespace

### ISSUE THREAD

**Issue by electricstrm-redgate** [kubernetes-csi/external-snapshotter#911]
**What happened**:
The following errors happen in the syslog.  

``` 
kubelet_pods.go:897] "Unable to retrieve pull secret, the image pull may not succeed." pod="kube-system/snapshot-controller-84f7b9d567-gdg6c" secret="" err="secret \"cloning-capability-app-registry\" not found"

```

The pull secret is for an image we pull. The image is a registry. The secret and the pod that uses the secret at not in the kube-system namespace. When we use the image for a deployment, it works. 

When i create the secret in kube-system, the messages stop. What's going on ?  Why does the snapshot controller need this secret.

**What you expected to happen**:
No errors messages.

**How to reproduce it**:
Using kubernetes 1.25.4
Image is registry:2.8.2
Use the snapshot controller
Secret is of type kubernetes.io/dockerconfigjson
Create a deployment with a container that pull registry image registry:2.8.2
Create a volume.
The problems arise as soon as the cluster is up.  No need to use the registry.

**Anything else we need to know?**:

These are the 4 volumes we used in the registry deployment.

1. Registry-certs is just a secret mounted as a volume.
2. registry-data is where all the registry images are saved. The PV is using the default storage class.
3. just an empty dir
4. Volume mounted for kube api access. The pod is on the default service account.

volumes:

1. name: registry-certs
   secret:
   defaultMode: 420
   secretName: platform-tls

2. name: registry-data
   persistentVolumeClaim:
   claimName: registry-pvc

3. name: auth-dir
    emptyDir: {}

4. name: kube-api-access-9gfmj
   projected:
   defaultMode: 420
   sources:
   - serviceAccountToken:
     expirationSeconds: 3607
     path: token
   - configMap:
     items:
       key: ca.crt
       path: ca.crt
       name: kube-root-ca.crt
   - downwardAPI:
     items:
       fieldRef:
       apiVersion: v1
       fieldPath: metadata.namespace
       path: namespace

**Environment**:
- Driver version:
```
gcr.io/k8s-staging-sig-storage/snapshot-controller:v6.2.2
```

- Kubernetes version (use `kubectl version`):
```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

- OS (e.g. from /etc/os-release):
```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION_ID="22.04"
```

- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ubuntu 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

- Install tools:  
```
   Kurl
```

- Others:
```
containerd version: "1.6.9"
```

**Comment by xing-yang** [comment]
The snapshot-controller does not have any logic that retrieves the image pull secret.  This logic is from kubelet.

**Comment by liangyuanpeng** [comment]
It would be great if you can provide some yaml to reproduce it.
