### ISSUE TITLE
GetSnapshotStatus is never called

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes-csi/external-snapshotter#95]
In snapshot_controller.go, the function"CreateSnapshot" is called over and over again during  my development and test`.  Thus, a lot of snapshots were created in my test environment.

Finally, I found the function "GetSnapshotStatus" is never called is external-snapshotter. So "ListSnapshots"  function is never called.

I wonder if this is a bug?  If not , I do not think it is a good idea to call "CreateSnapshot"  in the function "checkandUpdateBoundSnapshotStatusOperation".

**Comment by xing-yang** [comment]
Please see my comments in your PR.  "CreateSnapshot" in a CSI driver should be idempotent.  Repeated call should not create lots of snapshots.  The same call with same parameters should only create one snapshot.  If repeated call resulted in lots of snapshots, there is a bug in the CSI driver.

CreateSnapshot is the preferred way to check snapshot status.

**Comment by cwdsuzhou** [comment]
T

> Please see my comments in your PR. "CreateSnapshot" in a CSI driver should be idempotent. Repeated call should not create lots of snapshots. The same call with same parameters should only create one snapshot. If repeated call resulted in lots of snapshots, there is a bug in the CSI driver.
> 
> CreateSnapshot is the preferred way to check snapshot status.

Thank you for your reply, I have make the CSI driver idempotent now. So, "ListSnapshot" is currently useless, I wonder if it would be dropped absolutely in the futrue? Or, if it is better that the external-snapshot  calls "ListSnapshot" in advance when the CSI driver has implemented it.

**Comment by xing-yang** [comment]
ListSnapshots cannot return an gRPC error code.  That is why CreateSnapshot is better when checking the status while the snapshot is being created.

**Comment by cwdsuzhou** [comment]
Thank you
