### ISSUE TITLE
is group snapshot feature fully implemented?

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-csi/external-snapshotter#950]
from this code snippet, it seem this feature is not fully implemented
https://github.com/kubernetes-csi/external-snapshotter/blob/80a7aa9488ceb846e42298e09bbec04086686fdf/cmd/csi-snapshotter/main.go#L88-L89

but per https://kubernetes.io/blog/2023/05/08/kubernetes-1-27-volume-group-snapshot-alpha/#as-a-storage-vendor-how-do-i-add-support-for-group-snapshots-to-my-csi-driver, it's implemented

@xing-yang what's the status of this feature?

```
        // TODO(xing-yang): Enable enableVolumeGroupSnapshots when the feature is fully implemented
        // enableVolumeGroupSnapshots = flag.Bool("enable-volume-group-snapshots", false, "Enables the volume group snapshot feature, allowing the user to create snapshots of groups of volumes.")
```

**Comment by xing-yang** [comment]
Create group snapshot is complete.  The delete group snapshot part is still WIP.

**Comment by nixpanic** [comment]
A `--enable-volume-group-snapshots` option has been added in commit a574b8780ce8fa1d90d8ddca6fa7bf655336fd6e . Everything is in place for dynamic snapshotting. Importing pre-created group-snapshots is in progress through #837.

**Comment by Madhu-1** [comment]
@xing-yang can this be closed as the group snapshot is fully implemented now?

**Comment by ChristianCiach** [comment]
`--enable-volume-group-snapshots` should be documented in README.

**Comment by xing-yang** [comment]
Added an issue to track: https://github.com/kubernetes-csi/external-snapshotter/issues/1117
